### ISSUE TITLE
Uncaught TypeError: el.querySelectorAll is not a function

### ISSUE THREAD

**Issue by johnrizzo1** [OmniSharp/omnisharp-atom#1010]
[Enter steps to reproduce:]

1. ... Start Atom
2. ... Open a VS2017 solution with several projects within it.  In my case they were all asp.net core projects.

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2

### Stack Trace

Uncaught TypeError: el.querySelectorAll is not a function

```
At C:\Users\jrizzo\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:242

TypeError: el.querySelectorAll is not a function
    at OmniNotification._getFromDom (/packages/omnisharp-atom/dist/features/notification-handler.js:217:28)
    at OmniNotification.getDetailElement (/packages/omnisharp-atom/dist/features/notification-handler.js:203:25)
    at OmniNotification.addDetail (/packages/omnisharp-atom/dist/features/notification-handler.js:155:32)
    at PackageRestoreNotification.handleUnresolvedDependencies (/packages/omnisharp-atom/dist/features/notification-handler.js:93:41)
    at SafeSubscriber._next (/packages/omnisharp-atom/dist/features/notification-handler.js:49:57)
    at SafeSubscriber.__tryOrUnsub (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:185:22)
    at Subscriber._next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at RefCountSubscriber.Subscriber._next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at RefCountSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at Subject.next (/packages/omnisharp-atom/node_modules/rxjs/Subject.js:55:25)
    at ConnectableSubscriber.Subscriber._next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at ConnectableSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at SwitchMapSubscriber.notifyNext (/packages/omnisharp-atom/node_modules/rxjs/operator/switchMap.js:124:30)
    at InnerSubscriber._next (/packages/omnisharp-atom/node_modules/rxjs/InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at RefCountSubscriber.Subscriber._next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at RefCountSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at Subject.next (/packages/omnisharp-atom/node_modules/rxjs/Subject.js:55:25)
    at ConnectableSubscriber.Subscriber._next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at ConnectableSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at MapSubscriber._next (/packages/omnisharp-atom/node_modules/rxjs/operator/map.js:83:26)
    at MapSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at FilterSubscriber._next (/packages/omnisharp-atom/node_modules/rxjs/operator/filter.js:88:30)
    at FilterSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at Subject.next (/packages/omnisharp-atom/node_modules/rxjs/Subject.js:55:25)
    at /packages/atom-beautify/node_modules/lodash/lodash.js:4968:19)
    at StdioDriver._handlePacketEvent (/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/StdioDriver.js:260:14)
    at StdioDriver._handlePacket (/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/StdioDriver.js:232:18)
    at StdioDriver._handleData (/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/StdioDriver.js:224:18)
    at /packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/StdioDriver.js:171:54)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
    at Interface.<anonymous> (readline.js:365:12)
```

### Commands

```
  2x -9:17.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  4x -8:12.9.0 application:add-project-folder (atom-pane.pane.active)
  3x -0:29.5.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-beautify 0.30.2 
atom-npm 0.3.1 
atom-shortcuts 0.0.2 
atom-typescript 11.0.3 
autocomplete-python 1.8.64 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.7 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
Hydrogen 1.17.1 
intentions 1.1.2 
json-schema 0.1.15 
language-awk 0.1.12 
language-babel 2.66.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-powershell 4.0.0 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-jsonlint 1.3.0 
linter-ruby 1.2.5 
linter-sass-lint 1.7.4 
linter-tidy 2.3.1 
linter-ui-default 1.6.2 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
minimap-linter 2.0.0 
npm-install 4.0.4 
npm-plus 0.4.0 
nuclide 0.232.0 
nuclide-format-js 0.0.36 
omnisharp-atom 0.31.2 
pigments 0.39.1 
qolor 0.4.2 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by johnrizzo1** [comment]
This is documented here already.

* https://github.com/OmniSharp/omnisharp-atom/issues/1004
* https://github.com/OmniSharp/omnisharp-atom/issues/1003
