### ISSUE TITLE
Failed to load a language-csharp package grammar

### ISSUE THREAD

**Issue by All-the-good-names-were-taken** [OmniSharp/omnisharp-atom#1027]
[Enter steps to reproduce:]

    Start atom.

Or:

    Disable package.
    Restart atom.
    Enable package - error occurs instantly.

Update check finds no outstanding updates.
Bug originally reported against language-csharp plugin (https://github.com/atom/language-csharp/issues/121).

Atom: 1.26.1 x64
Electron: 1.7.11
OS: Mac OS X 10.10.5
Thrown From: language-csharp package 1.0.1
Stack Trace

Failed to load a language-csharp package grammar

At atom.grammars.startIdForScope is not a function in /Applications/Atom.app/Contents/Resources/app.asar/node_modules/language-csharp/grammars/csharp.json

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at GrammarRegistry.module.exports.GrammarRegistry.addGrammar (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:80:26)
    at Grammar.module.exports.Grammar.activate (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:259:54)
    at grammarRegistry.readGrammar (/Applications/Atom.app/Contents/Resources/app/src/package.js:617:53)
    at CSON.readFile (/Applications/Atom.app/Contents/Resources/app/src/grammar-registry.js:468:15)
    at parseContents (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:123:13)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:230:26
    at ELECTRON_ASAR.js:497:9
    at FSReqWrap.wrapper [as oncomplete] (fs.js:629:17)
  at /app.asar/node_modules/language-csharp/grammars/csharp.json:1:1

Commands

Non-Core Packages

advanced-open-file 0.16.8 
atom-beautify 0.32.2 
atom-wrap-in-tag 0.6.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
delete-lines 0.5.0 
double-tag 1.4.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-scala 1.1.9 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-csslint 2.0.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
omnisharp-atom 0.31.2 
open-recent 5.0.0 
recent-finder 0.5.1 
recent-projects 0.13.1 
remember-folds 0.3.0 
script 3.17.3 
simple-drag-drop-text 0.4.0 
Sublime-Style-Column-Selection 1.7.4

**Comment by wegunterjr** [comment]
I am thinking that the team is no longer actively working this atom package project.   I searched for a while to see why i was getting the language errors and someone mentioned omnisharp - I uninstalled omnisharp under 1.27 and no more errors. I tried to install it, and it isn't able to activate. I wonder if the folder layout changed. Cuz my error showed part of the path that doesn't exist under 1.27.
Older folder structure:
`AppData\Local\atom\app-1.17.0\resources\app\node_module\language-csharp\grammars\csharp.json`

the current 1.27 folder structure is:
`AppData\Local\atom\app-1.27.1\resources\app\apm\node_modules`
