### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by SwayStar123** [OmniSharp/omnisharp-atom#1036]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2

### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At C:\Users\Kids.BABAJI\.atom\packages\omnisharp-atom\dist\atom\generator-aspnet.js:62

TypeError: Cannot read property 'then' of undefined
    at GeneratorAspnet.loadCsFile (/packages/omnisharp-atom/dist/atom/generator-aspnet.js:62:28)
    at GeneratorAspnet.newProject (/packages/omnisharp-atom/dist/atom/generator-aspnet.js:78:25)
    at /packages/omnisharp-atom/dist/atom/generator-aspnet.js:42:30)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:350034)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:348509)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:1:669041)
    at EventEmitter.t (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:1:676425)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -1:48.1.0 omnisharp-atom:new-project (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
omnisharp-atom 0.31.2 
```

**Comment by Nafeek30** [comment]
Exact same issue. Is this bug going to be fixed anytime soon?

**Comment by Smootha69** [comment]
I have fixed a issue regarding this omnisharp package, but all I need to know is what to change "then" too or what code to replace it with.
