### ISSUE TITLE
Failed to activate the omnisharp-atom package

### ISSUE THREAD

**Issue by Adeelasd** [OmniSharp/omnisharp-atom#1037]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: "openSUSE Tumbleweed"
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2

### Stack Trace

Failed to activate the omnisharp-atom package

```
At atom.grammars.startIdForScope is not a function

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:516:11)
    at forEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:9344:14)
    at OmniSharpAtom.activate (/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:2921267)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:2920679)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:2918310)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:2920539)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:2920482)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382681)
    at config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:382297)
    at Config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:332481)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/static/<embedded>:11:382247)
    at PackageManager.activate (/usr/share/atom/resources/app/static/<embedded>:11:381865)
    at t.loadState.then (/usr/share/atom/resources/app/static/<embedded>:1:660921)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
omnisharp-atom 0.31.2 
platformio-ide-terminal 2.9.1 
```

**Comment by talkelley3** [comment]
Same happened to me on Windows 10

**Comment by skovsboll** [comment]
Also happens on Macos Mojave.

**Comment by hekto76** [comment]
Same issue here, tryna script for Unity.

**Comment by WalrusPenguins** [comment]
Same here

**Comment by voxsoftware** [comment]
Also on gnu/linux ubuntu 18.04

**Comment by CloudEntity57** [comment]
Also happened on MacOS High Sierra.

**Comment by hoverbird** [comment]
An issue on macOS Mojave (10.14.4)

**Comment by samgovier** [comment]
FYI progress for this exists in [this thread.](https://github.com/OmniSharp/omnisharp-atom/issues/1020)  
You can get the package to install properly making the following changes to `C:\Users\<name>\.atom\packages\omnisharp-atom\dist\omnisharp-atom.js`:  
###### Line 140
`var grammars = atom.grammars;`  
to  
`var grammars = atom.grammars.textmateRegistry || atom.grammars;`  
###### Line 145
Change `atom.grammars` to just `grammars`  
  
However I still couldn't get the OmniSharp server connection working after that ([I'm guessing because of this](https://ci.appveyor.com/project/nosami/omnisharp-atom)). It looks like [this repository has been depricated](https://travis-ci.org/OmniSharp/omnisharp-atom/) in favor of VS Code. Try a different package or switch IDEs.

**Comment by alt3r3dgd** [comment]
Thanks @samgovier, this removed the error, but I can't get the completion to work: it just disappeared. What could I do with this?

**Comment by ThinesCherZz** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2


### Stack Trace

Failed to activate the omnisharp-atom package

```
At atom.grammars.startIdForScope is not a function

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:516:11)
    at forEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:9342:14)
    at OmniSharpAtom.activate (/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3313556)
    at measure (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3312968)
    at Package.measure (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3310578)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3312828)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3312771)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:382554)
    at ~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:940004
    at r (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:934610)
    at n (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1128190)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1128396)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
  4x -2:32.2.0 core:backspace (input.hidden-input)
     -2:26.2.0 editor:newline (input.hidden-input)
     -2:23.1.0 core:backspace (input.hidden-input)
  2x -2:20.9.0 editor:newline (input.hidden-input)
     -1:55.4.0 core:backspace (input.hidden-input)
     -1:54.1.0 editor:newline (input.hidden-input)
     -1:38.8.0 core:backspace (input.hidden-input)
     -1:36.8.0 autocomplete-plus:confirm (input.hidden-input)
     -1:36.7.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:35.3.0 core:undo (input.hidden-input)
  8x -1:33.9.0 core:backspace (input.hidden-input)
     -1:23.7.0 core:select-all (input.hidden-input)
  6x -1:22.8.0 core:backspace (input.hidden-input)
  2x -1:16.6.0 editor:newline (input.hidden-input)
  2x -1:08.3.0 core:backspace (input.hidden-input)
  2x -1:01.9.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-plus-async 0.22.0 
language-asp 1.1.1 
language-aspx 0.5.0 
omnisharp-atom 0.31.2 
teletype 0.13.4 
```

**Comment by alexasahis** [comment]
Also happened on macOS Cataline (10.15.1).

**Comment by unguest** [comment]
Even with the edited file, the error still goes : 
`
atom.grammars.startIdForScope is not a function

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (C:\Users\artpn\.atom\packages\omnisharp-atom\dist\omnisharp-atom.js:145:35)
    at arrayEach (C:\Users\artpn\.atom\packages\omnisharp-atom\node_modules\lodash\lodash.js:516:11)
    at forEach (C:\Users\artpn\.atom\packages\omnisharp-atom\node_modules\lodash\lodash.js:9342:14)
    at OmniSharpAtom.activate (C:\Users\artpn\.atom\packages\omnisharp-atom\dist\omnisharp-atom.js:153:30)
    at Package.activateNow (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3313556)
    at measure (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3312968)
    at Package.measure (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3310578)
    at activationPromise.activationPromise.Promise (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3312828)
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3312771)
    at PackageManager.activatePackage (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:382554)
    at o.forEach.e (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:377720)
    at Array.forEach (<anonymous>)
    at disabledPackagesSubscription.disabledPackagesSubscription.config.onDidChange (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:377704)
    at emitter.on (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:334755)
    at Function.simpleDispatch (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1211909)
    at Emitter.emit (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:1213350)
    at Config.emitChangeEvent (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:337243)
    at Config.setRawValue (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:334483)
    at Config.set (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:330277)
    at Config.removeAtKeyPath (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:332300)
    at Package.enable (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:3310363)
    at PackageManager.enablePackage (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:11:375418)
    at HTMLButtonElement.enablementButtonClickHandler (C:\Users\artpn\AppData\Local\atom\app-1.41.0\resources\app\static\<embedded>:14:2603767)

The error was thrown from the omnisharp-atom package. This issue has already been reported.
`

**Comment by ziad10a** [comment]
Same here in Ubuntu 18.04.3

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2


### Stack Trace

Failed to activate the omnisharp-atom package

```
At atom.grammars.startIdForScope is not a function

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:516:11)
    at forEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:9342:14)
    at OmniSharpAtom.activate (/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3209961)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:3209373)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3206983)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:3209233)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:3209176)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382452)
    at config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:382068)
    at Config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:331716)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/static/<embedded>:11:382018)
    at PackageManager.activate (/usr/share/atom/resources/app/static/<embedded>:11:381568)
    at t.loadState.then (/usr/share/atom/resources/app/static/<embedded>:1:715031)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-unity 0.1.3 
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.1 
omnisharp-atom 0.31.2 
```

**Comment by Pauer1000** [comment]
Failed to acitvate the omnisharp-atom package.
omnisharp-atom 0,31.2
windows 10
atom 1.4.3 x64
TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (C:\Users\home\.atom\packages\omnisharp-atom\dist\omnisharp-atom.js:145:35)
    at arrayEach (C:\Users\home\.atom\packages\omnisharp-atom\node_modules\lodash\lodash.js:516:11)
    at forEach (C:\Users\home\.atom\packages\omnisharp-atom\node_modules\lodash\lodash.js:9342:14)
    at OmniSharpAtom.activate (C:\Users\home\.atom\packages\omnisharp-atom\dist\omnisharp-atom.js:153:30)
    at Package.activateNow (C:\Users\home\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:3317257)
    at measure (C:\Users\home\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:3316669)
    at Package.measure (C:\Users\home\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:3314279)
    at activationPromise.activationPromise.Promise (C:\Users\home\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:3316529)
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\home\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:3316472)
    at PackageManager.activatePackage (C:\Users\home\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:382452)
    at C:\Users\home\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:941017
    at r (C:\Users\home\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:935623)
    at n (C:\Users\home\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:14:1124557)
    at ChildProcess.o.process.on.e (C:\Users\home\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:14:1124763)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)

**Comment by pasimko** [comment]
**Atom**: 1.44.0 x64
**Electron**: 4.2.12
**OS**: "Manjaro Linux"
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2


### Stack Trace

Failed to activate the omnisharp-atom package

```
At atom.grammars.startIdForScope is not a function

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/usr/lib/atom/node_modules/markdown-preview/node_modules/lodash/lodash.js:516:11)
    at forEach (/usr/lib/atom/node_modules/markdown-preview/node_modules/lodash/lodash.js:9344:14)
    at OmniSharpAtom.activate (/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (/usr/lib/atom/src/package.js:241:27)
    at measure (/usr/lib/atom/src/package.js:210:27)
    at Package.measure (/usr/lib/atom/src/package.js:81:19)
    at activationPromise.Promise (/usr/lib/atom/src/package.js:204:14)
    at new Promise (<anonymous>)
    at Package.activate (/usr/lib/atom/src/package.js:202:32)
    at PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:790:36)
    at config.transactAsync (/usr/lib/atom/src/package-manager.js:765:30)
    at Config.transactAsync (/usr/lib/atom/src/config.js:925:22)
    at PackageManager.activatePackages (/usr/lib/atom/src/package-manager.js:763:17)
    at PackageManager.activate (/usr/lib/atom/src/package-manager.js:740:44)
    at loadStatePromise.loadState.then (/usr/lib/atom/src/atom-environment.js:1017:21)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
git-plus 8.7.1 
gpp-compiler 3.0.7 
omnisharp-atom 0.31.2 
```

**Comment by Feofano** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Linux Mint
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2


### Stack Trace

Failed to activate the omnisharp-atom package

```
At atom.grammars.startIdForScope is not a function

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:516:11)
    at forEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:9342:14)
    at OmniSharpAtom.activate (/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3219604)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:3219016)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3216626)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:3218876)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:3218819)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382452)
    at config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:382068)
    at Config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:331716)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/static/<embedded>:11:382018)
    at PackageManager.activate (/usr/share/atom/resources/app/static/<embedded>:11:381568)
    at t.loadState.then (/usr/share/atom/resources/app/static/<embedded>:1:717298)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
file-icons 2.1.40 
git-plus 8.7.1 
gpp-compiler 3.0.7 
Hydrogen 2.14.1 
ide-csharp 0.6.2 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.1 
omnisharp-atom 0.31.2 
platformio-ide-terminal 2.10.0 
```

**Comment by Florain-A** [comment]
similar issue on the macOS BigSur is there a different package for C# ?

**Comment by PlatinumLucario** [comment]
I'm also getting the same error. For anyone else reading this, please take a good look at the latest commit made on the omnisharp-atom repository: It was waaaaaay back on 13 April 2017 lol

And the latest forked commit is by Techcraft7 on 24 September 2020, see [this pull request](https://github.com/OmniSharp/omnisharp-atom/pull/1040) for more information.

With that being said, omnisharp-atom needs more contributors, so if anyone wants to help out, please do so! :)


[Enter steps to reproduce:]

1. Install the plugin
2. Nothing else needs to be done

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 20.04.2
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2


### Stack Trace

Failed to activate the omnisharp-atom package

```
At atom.grammars.startIdForScope is not a function

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:530:11)
    at forEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:9410:14)
    at OmniSharpAtom.activate (/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (<embedded>:11:3388858)
    at <embedded>:11:3388270
    at Package.measure (<embedded>:11:3385848)
    at <embedded>:11:3388130
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3388073)
    at PackageManager.activatePackage (<embedded>:11:385497)
    at <embedded>:11:914488
    at r (<embedded>:11:909094)
    at n (<embedded>:14:1190909)
    at <embedded>:14:1191063
    at Socket.<anonymous> (<embedded>:14:1189665)
    at Socket.emit (events.js:228:7)
    at Pipe.<anonymous> (net.js:664:12)

```

### Commands

```
```

### Non-Core Packages

```
omnisharp-atom 0.31.2 
```

**Comment by Hinthusiast** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2


### Stack Trace

Failed to activate the omnisharp-atom package

```
At atom.grammars.startIdForScope is not a function

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:530:11)
    at forEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:9410:14)
    at OmniSharpAtom.activate (/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508863)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508275
    at Package.measure (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3505853)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508135
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508078)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:385612)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:915033
    at r (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:909639)
    at n (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1194945)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195151)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 2.0.1 
intentions 2.1.1 
kite 0.206.0 
linter 3.4.0 
linter-ui-default 3.4.1 
omnisharp-atom 0.31.2 
```

**Comment by violog** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: "Arch Linux"
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2


### Stack Trace

Failed to activate the omnisharp-atom package

```
At atom.grammars.startIdForScope is not a function

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:530:11)
    at forEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:9410:14)
    at OmniSharpAtom.activate (/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (/usr/lib/atom/src/package.js:242:27)
    at /usr/lib/atom/src/package.js:211:27
    at Package.measure (/usr/lib/atom/src/package.js:82:19)
    at /usr/lib/atom/src/package.js:205:14
    at new Promise (<anonymous>)
    at Package.activate (/usr/lib/atom/src/package.js:203:32)
    at PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:800:36)
    at /usr/lib/atom/node_modules/settings-view/lib/package-manager.js:477:29
    at exit (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:114:16)
    at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:280:9)
    at /usr/lib/atom/src/buffered-process.js:301:9
    at Socket.<anonymous> (/usr/lib/atom/src/buffered-process.js:169:7)
    at Socket.emit (events.js:228:7)
    at Pipe.<anonymous> (net.js:664:12)
```

### Commands

```
     -9:46.1.0 editor:newline (input.hidden-input)
     -9:41.6.0 autocomplete-plus:confirm (input.hidden-input)
     -9:39.1.0 editor:delete-to-beginning-of-word (input.hidden-input)
  6x -9:37 core:undo (input.hidden-input)
     -7:29.6.0 editor:delete-to-beginning-of-word (input.hidden-input)
  2x -7:27.1.0 core:backspace (input.hidden-input)
     -6:37.3.0 editor:delete-to-beginning-of-word (input.hidden-input)
  2x -6:26.3.0 core:backspace (input.hidden-input)
     -4:41.6.0 editor:delete-to-beginning-of-word (input.hidden-input)
```

### Non-Core Packages

```
omnisharp-atom 0.31.2 
vim-mode-plus 1.36.6 
```

**Comment by Islam-alshiki** [comment]
> FYI progress for this exists in [this thread.](https://github.com/OmniSharp/omnisharp-atom/issues/1020) You can get the package to install properly making the following changes to `C:\Users\<name>\.atom\packages\omnisharp-atom\dist\omnisharp-atom.js`:
> 
> ###### Line 140
> `var grammars = atom.grammars;` to `var grammars = atom.grammars.textmateRegistry || atom.grammars;`
> 
> ###### Line 145
> Change `atom.grammars` to just `grammars`
> 
> However I still couldn't get the OmniSharp server connection working after that ([I'm guessing because of this](https://ci.appveyor.com/project/nosami/omnisharp-atom)). It looks like [this repository has been depricated](https://travis-ci.org/OmniSharp/omnisharp-atom/) in favor of VS Code. Try a different package or switch IDEs.

This helps me.

**Comment by Diegosqz** [comment]
Also happened on LMDE 4. ;.;

**Comment by marksagal** [comment]
> FYI progress for this exists in [this thread.](https://github.com/OmniSharp/omnisharp-atom/issues/1020) You can get the package to install properly making the following changes to `C:\Users\<name>\.atom\packages\omnisharp-atom\dist\omnisharp-atom.js`:
> 
> ###### Line 140
> `var grammars = atom.grammars;` to `var grammars = atom.grammars.textmateRegistry || atom.grammars;`
> 
> ###### Line 145
> Change `atom.grammars` to just `grammars`
> 
> However I still couldn't get the OmniSharp server connection working after that ([I'm guessing because of this](https://ci.appveyor.com/project/nosami/omnisharp-atom)). It looks like [this repository has been depricated](https://travis-ci.org/OmniSharp/omnisharp-atom/) in favor of VS Code. Try a different package or switch IDEs.

this totally fixed the issue. why not make a pull request?

**Comment by KRC2000** [comment]
Same issue here:

```
TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/home/krs/.atom/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/home/krs/.atom/packages/omnisharp-atom/node_modules/lodash/lodash.js:530:11)
    at forEach (/home/krs/.atom/packages/omnisharp-atom/node_modules/lodash/lodash.js:9410:14)
    at OmniSharpAtom.activate (/home/krs/.atom/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3388634)
    at /usr/share/atom/resources/app/static/<embedded>:11:3388046
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3385624)
    at /usr/share/atom/resources/app/static/<embedded>:11:3387906
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:3387849)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:385612)
    at /usr/share/atom/resources/app/static/<embedded>:11:915033
    at r (/usr/share/atom/resources/app/static/<embedded>:11:909639)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1194943)
    at /usr/share/atom/resources/app/static/<embedded>:14:1195097
    at Socket.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:1193699)
    at Socket.emit (events.js:228:7)
    at Pipe.<anonymous> (net.js:664:12)
```

Atom: 1.58.0 x64
OS: "Pop!_OS by System76"
Thrown From: omnisharp-atom package 0.31.2

**Comment by jashanpreet-singh-99** [comment]
> FYI progress for this exists in [this thread.](https://github.com/OmniSharp/omnisharp-atom/issues/1020) You can get the package to install properly making the following changes to `C:\Users\<name>\.atom\packages\omnisharp-atom\dist\omnisharp-atom.js`:
> 
> ###### Line 140
> `var grammars = atom.grammars;` to `var grammars = atom.grammars.textmateRegistry || atom.grammars;`
> 
> ###### Line 145
> Change `atom.grammars` to just `grammars`
> 
> However I still couldn't get the OmniSharp server connection working after that ([I'm guessing because of this](https://ci.appveyor.com/project/nosami/omnisharp-atom)). It looks like [this repository has been depricated](https://travis-ci.org/OmniSharp/omnisharp-atom/) in favor of VS Code. Try a different package or switch IDEs.

(2022) Worked for me on Mac OSX  Monterey 12.6
