### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

### ISSUE THREAD

**Issue by bryanwood** [OmniSharp/omnisharp-atom#125]
Had project.json and Program.cs file open. Closed .json file then closed C# file

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.2
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1269

TypeError: Cannot read property 'getBufferPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1269:34)
  at Function.Omni.getEditorContext (/Users/bryanwood/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.ts:15:29)
  at Function.Omni.req (/Users/bryanwood/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.ts:35:28)
  at Function.Omni.codecheck (/Users/bryanwood/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.ts:96:21)
  at LinterCSharp.lintFile (/Users/bryanwood/.atom/packages/omnisharp-atom/lib/omnisharp-atom/linter.ts:43:14)
  at /Users/bryanwood/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/bryanwood/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
  2x -7:06.0 editor:newline (atom-text-editor.editor.is-focused)
     -7:01.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -7:00.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -6:54.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -6:05.3.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -6:02.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:44 core:backspace (atom-text-editor.editor.is-focused)
  3x -1:41.9.0 core:save (atom-text-editor.editor.is-focused)
  5x -0:06.2.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "language-handlebars",
      "atom-handlebars",
      "go-plus",
      "Zen",
      "editor-stats",
      "atom-beautify",
      "emmet"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.0
language-csharp, v0.5.0
language-fsharp, v0.8.4
linter, v0.12.1
omnisharp-atom, v0.3.0

# Dev
No dev packages
```

**Comment by ryan1234** [comment]
+1 for me.

Steps:

1. Open atom.
2. Open .cs file.
3. Go to line with `{` and delete spaces in front of it until aligned leftmost.
4. On same line as (3), hit tab once.
5. Control-S to save file.
6. Control-W to close file.
7. Error is thrown.

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

```
At /Users/ryanmeyer/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1269

TypeError: Cannot read property 'getBufferPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorBufferPosition (/Users/ryanmeyer/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1269:34)
  at Function.module.exports.Omni.getEditorContext (/Users/ryanmeyer/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.coffee:14:23)
  at Function.module.exports.Omni.req (/Users/ryanmeyer/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.coffee:33:18)
  at Function.module.exports.Omni.codecheck (/Users/ryanmeyer/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.coffee:73:8)
  at LinterCSharp.lintFile (/Users/ryanmeyer/.atom/packages/omnisharp-atom/lib/omnisharp-atom/linter.coffee:43:14)
  at /Users/ryanmeyer/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/ryanmeyer/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
  2x -0:35.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:34.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:34.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:34.8.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:34.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:33.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:33.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:33.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:32.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:32.1.0 core:close (atom-text-editor.editor.is-focused)
  2x -0:03.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:02.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:02.8.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:01.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.9.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.0
linter, v0.12.1
omnisharp-atom, v0.3.0

# Dev
No dev packages
```

**Comment by ctolkien** [comment]
@bryanwood pull request or GTFO!

:trollface:

**Comment by nosami** [comment]
This issue is gone in v.0.6.5
