### ISSUE TITLE
Expanding Omnisharp output container

### ISSUE THREAD

**Issue by jmkelly** [OmniSharp/omnisharp-atom#139]
1. Trying to expand the omnisharp output after a failure

**Atom Version**: 0.194.0
**System**: linux 3.13.0-32-generic
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'height' of undefined

```
At /home/james/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/dock-view.ts:32

TypeError: Cannot read property 'height' of undefined
  at DockView.resizeStarted (/home/james/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/dock-view.ts:32:64)
  at HTMLDivElement.<anonymous> (/home/james/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/dock-view.ts:145:92)
  at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.0
linter, v0.12.1
omnisharp-atom, v0.4.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
probably something from the typescript conversion...
