### ISSUE TITLE
Either upgrading, or installing omnisharp-atom

### ISSUE THREAD

**Issue by jmkelly** [OmniSharp/omnisharp-atom#156]
[Enter steps to reproduce below:]

1. Open up Atom
2. Upgrade omnisharp-atom via the settings - packages page

**Atom Version**: 0.194.0
**System**: linux 3.13.0-32-generic
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.1

### Stack Trace

Failed to load the omnisharp-atom package

```
At Cannot find module 'lodash'

Error: Cannot find module 'lodash'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/james/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.ts:1:71)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .ts] (/usr/share/atom/resources/app.asar/src/typescript.js:99:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:677:34)
  at /usr/share/atom/resources/app.asar/src/package.js:170:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:161:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:354:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:433:30)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:276:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
  2x -4:46.2.0 core:backspace (atom-text-editor.editor.mini)
  2x -4:41 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.0
linter, v0.12.1
omnisharp-atom, v0.4.3

# Dev
No dev packages
```

**Comment by willl** [comment]
Hrmmm... That shouldn't happen. it's listed as a package dependency in packages.json, so it should download when you did the install.

If you cloned master to your local, then you'd need to run `npm install` from the omnisharp-atom package folder...

**Comment by jmkelly** [comment]
Fresh install, didn't see this issue now.  Closing out for now.
