### ISSUE TITLE
Uncaught TypeError: Cannot read property 'run' of undefined

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#175]
[Enter steps to reproduce below:]

1. Right click omnisharp
2. New application

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.6

### Stack Trace

Uncaught TypeError: Cannot read property 'run' of undefined

```
At /Users/dfowler/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.ts:35

TypeError: Cannot read property 'run' of undefined
  at atom-workspace.<anonymous> (/Users/dfowler/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.ts:35:115)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -8:16.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:16.5.0 core:save (atom-text-editor.editor.is-focused)
     -7:38 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -6:04.3.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -6:04.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:01.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused)
  2x -6:00.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:59.1.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:58.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:58.8.0 core:save (atom-text-editor.editor.is-focused)
     -5:57.1.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:57 core:backspace (atom-text-editor.editor.is-focused)
     -5:56.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.6.0 omnisharp-atom:new-application (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, vundefined
autocomplete-plus, v2.12.0
language-csharp, v0.5.0
linter, v0.12.1
omnisharp-atom, v0.4.6

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
`atom-yeoman, vundefined` ... that's odd that the version isn't defined.  Maybe try to reinstall?

**Comment by schotime** [comment]
Reinstall of atom-yeoman fixed it for me.

**Comment by david-driscoll** [comment]
Closing for now!
