### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBuffer' of undefined

### ISSUE THREAD

**Issue by copyleftdev** [OmniSharp/omnisharp-atom#211]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.12

### Stack Trace

Uncaught TypeError: Cannot read property 'getBuffer' of undefined

```
At /Users/ops/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client.ts:43

TypeError: Cannot read property 'getBuffer' of undefined
  at Client.makeRequest (/Users/ops/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client.ts:43:34)
  at Function.Omni.makeRequest (/Users/ops/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.ts:25:51)
  at LinterCSharp.lintFile (/Users/ops/.atom/packages/omnisharp-atom/lib/omnisharp-atom/linter.ts:37:43)
  at /Users/ops/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/ops/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -4:20.3.0 editor:indent (atom-text-editor.editor)
     -4:19.3.0 core:backspace (atom-text-editor.editor)
     -4:16.7.0 editor:newline (atom-text-editor.editor)
     -4:15.7.0 core:backspace (atom-text-editor.editor)
  3x -4:15.3.0 editor:newline (atom-text-editor.editor)
     -4:01.0 core:backspace (atom-text-editor.editor)
     -4:00.1.0 autocomplete:toggle (atom-text-editor.editor)
  4x -3:49.6.0 core:move-left (atom-text-editor.editor)
     -3:48.3.0 core:backspace (atom-text-editor.editor)
  4x -3:47.1.0 core:move-right (atom-text-editor.editor)
     -3:36.6.0 core:save (atom-text-editor.editor)
     -3:33 core:select-all (atom-text-editor.editor)
     -3:24.9.0 omnisharp-atom:toggle (atom-text-editor.editor)
  3x -3:19.3.0 omnisharp-atom:toggle-output (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
  6x -0:10.5.0 core:backspace (atom-text-editor.editor.mini)
     -0:07.2.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
autocomplete-plus, v2.12.1
autocomplete-plus-async, v0.22.0
build, v0.30.0
color-picker, v1.7.0
language-csharp, v0.5.0
linter, v0.12.1
omnisharp-atom, v0.4.12

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Any additional details as to what you were doing at the time?

Trying to open a file, had a file already open, no files open.

Thanks!

**Comment by massimiliano-mantione** [comment]
Hi, I have the same issue (the stack trace is identical).
I am on Linux (with mono 4.0.1) and not on a mac as the other poster.
Apart from that, atom and omnisharp versions are the same,

What triggers the error is executing "atom ." in a directory that is the root of a C# project (the directory contains the sln file).
No other file was open: atom was closed before this invocation.

**Comment by nosami** [comment]
I just got the same error by launching `atom /path/to/omnisharp-roslyn'

Atom opened with the install package screen.

**Comment by nosami** [comment]
fixed in v0.4.13

**Comment by nosami** [comment]
I

**Comment by nosami** [comment]
I'm getting the same error when starting atom with a browser tab.
