### ISSUE TITLE
After uninstalling and reinstalling omnisharp-atom getting "Cannot read property 'split' of undefined"

### ISSUE THREAD

**Issue by willl** [OmniSharp/omnisharp-atom#213]
[Enter steps to reproduce below:]

1. Uninstall omnisharp-atom from command line (apm uninstall omnisharp-atom)
2. Install omnisharp-atom from command line (apm install omnisharp-atom).
3. Launch Atom. After launching, I get the described error.

**Atom Version**: 0.196.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.12

### Stack Trace

Failed to activate the omnisharp-atom package

```
At Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at ClientManager.getClientForEditor (C:\Users\william\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client-manager.ts:50:33)
    at ClientManager.getClientForActiveEditor (C:\Users\william\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client-manager.ts:39:25)
    at Function.Omni.toggle (C:\Users\william\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni.ts:15:24)
    at OmniSharpAtom.toggle (C:\Users\william\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.ts:145:18)
    at OmniSharpAtom.detectGrammar (C:\Users\william\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.ts:113:22)
    at OmniSharpAtom.detectAutoToggleGrammar (C:\Users\william\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.ts:104:14)
    at C:\Users\william\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.ts:98:19
    at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\william\AppData\Local\atom\app-0.196.0\resources\app.asar\src\workspace.js:267:9)
    at OmniSharpAtom.subscribeToEvents (C:\Users\william\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.ts:86:46)
    at OmniSharpAtom.activate (C:\Users\william\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.ts:51:18)
    at Package.module.exports.Package.activateNow (C:\Users\william\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:222:19)
    at C:\Users\william\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:203:30
    at Package.module.exports.Package.measure (C:\Users\william\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:147:15)
    at Package.module.exports.Package.activate (C:\Users\william\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\william\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package-manager.js:434:21)
    at C:\Users\william\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package-manager.js:418:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".suo",
      ".vsmdi",
      ".vscc",
      ".dll"
    ],
    "disabledPackages": [
      "data-atom",
      "emmet",
      "wrap-guide",
      "js-refactor",
      "refactor"
    ],
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, vundefined
atom-yeoman, v0.2.0
autoclose-html, v0.15.0
autocomplete-plus, v2.12.1
highlight-selected, v0.9.2
linter, v0.12.1
monokai, v0.14.0
omnisharp-atom, v0.4.12
tabs-to-spaces, v0.10.0

# Dev
No dev packages
```

**Comment by willl** [comment]
Just noticed that atom-typescript says "vundefined".

Removing it, and also removing atom-typescript seems to have fixed the issue. 

So closing this issue for now.
