### ISSUE TITLE
Uncaught TypeError: Cannot read property 'typelookupPromise' of undefined

### ISSUE THREAD

**Issue by mishfit** [OmniSharp/omnisharp-atom#217]
### Steps to Reproduce

1. open atom at solution root
2. attempt to toggle on OmniSharp server (have never managed to turn it on)

##### Aside
Should I not have installed both "autocomplete-plus" _and_ "autocomplete-plus-async"?

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.12

### Stack Trace

Uncaught TypeError: Cannot read property 'typelookupPromise' of undefined

```
At /Users/mishochu/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/lookup.ts:79

TypeError: Cannot read property 'typelookupPromise' of undefined
  at Tooltip.showExpressionType (/Users/mishochu/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/lookup.ts:79:20)
  at /Users/mishochu/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/lookup.ts:46:75

```

### Commands

```
     -9:07.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  7x -5:25.8.0 omnisharp-atom:toggle-output (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:05.2.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack.remove)
     -1:15.7.0 omnisharp-atom:toggle (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -1:05.6.0 omnisharp-atom:find-usages (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -1:02.3.0 omnisharp-atom:go-to-definition (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:25.2.0 omnisharp-atom:toggle (atom-text-editor.editor.vim-mode.is-focused.command-mode)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
autocomplete-css, v0.6.0
autocomplete-html, v0.6.0
autocomplete-plus, v2.12.1
autocomplete-plus-async, v0.22.0
linter, v0.12.1
omnisharp-atom, v0.4.12
vim-mode, v0.46.0

# Dev
No dev packages
```

**Comment by nosami** [comment]
autocomplete-plus-async should not be installed.

**Comment by mishfit** [comment]
understood
