### ISSUE TITLE
Uncaught TypeError: Cannot read property 'codecheckPromise' of undefined

### ISSUE THREAD

**Issue by Camypaper** [OmniSharp/omnisharp-atom#219]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Unknown Windows Version
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.12

### Stack Trace

Uncaught TypeError: Cannot read property 'codecheckPromise' of undefined

```
At C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\linter.ts:37

TypeError: Cannot read property 'codecheckPromise' of undefined
  at LinterCSharp.lintFile (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\linter.ts:37:20)
  at C:\Users\camypaper\.atom\packages\linter\lib\linter-view.coffee:163:18
  at Array.forEach (native)
  at C:\Users\camypaper\.atom\packages\linter\lib\linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -0:25.2.0 application:open-file (atom-text-editor.editor)
     -0:22.3.0 application:new-file (atom-text-editor.editor)
     -0:18.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:14.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
autocomplete-plus, v2.12.1
autocomplete-snippets, v1.4.0
file-icons, v1.5.5
japanese-wrap, v0.2.7
linter, v0.12.1
omnisharp-atom, v0.4.12

# Dev
No dev packages
```

**Comment by nosami** [comment]
I get this error when I open a cs file that isn't part of the solution that I started omnisharp with.
