### ISSUE TITLE
Uncaught TypeError: Cannot read property 'autocomplete' of undefined

### ISSUE THREAD

**Issue by joeizang** [OmniSharp/omnisharp-atom#229]
[Enter steps to reproduce below:]

1. ...Was editing a file from an mvc 5 project and this happened when I was to get an autocompletion
2. ...

**Atom Version**: 0.198.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.14

### Stack Trace

Uncaught TypeError: Cannot read property 'autocomplete' of undefined

```
At C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:579

TypeError: Cannot read property 'autocomplete' of undefined
  at getResults (C:\Users\IZANG\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\lib\completion-provider.ts:10:27)
  at AnonymousObserver.justResults [as _onNext] (C:\Users\IZANG\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\lib\completion-provider.ts:25:38)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1962:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1894:35)
  at AnonymousObserver.tryCatcher (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.next (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1894:35)
  at InnerObserver.onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:3552:90)
  at InnerObserver.tryCatcher (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.next (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1894:35)
  at MapObserver.onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:4595:19)
  at MapObserver.tryCatcher (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.next (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1894:35)
  at FilterObserver.onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:4899:34)
  at FilterObserver.tryCatcher (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.next (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1894:35)
  at next (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:3837:20)
  at AnonymousObserver._onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:3857:13)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1962:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1894:35)
  at AnonymousObserver.tryCatcher (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.next (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5018:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1894:35)
  at AnonymousObserver._onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:4772:13)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1962:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1894:35)
  at Subject.Rx.Subject.addProperties.onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5138:19)
  at Object.dataSource.onNext (C:\Users\IZANG\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\lib\completion-provider.ts:63:28)
  at Object.exports.CompletionProvider.getSuggestions (C:\Users\IZANG\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\lib\completion-provider.ts:96:20)
  at C:\Users\IZANG\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:152:45
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\IZANG\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:135:15)
  at AutocompleteManager.getSuggestionsFromProviders (C:\Users\IZANG\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\IZANG\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:129:6)
  at C:\Users\IZANG\.atom\packages\autocomplete-plus\lib\autocomplete-manager.coffee:1:1

```

### Commands

```
     -0:33.6.0 core:delete (atom-text-editor.editor.is-focused)
     -0:33 editor:newline (atom-text-editor.editor.is-focused)
     -0:28.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:13.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:13.5.0 snippets:expand (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.1
linter, v0.12.1
omnisharp-atom, v0.4.14

# Dev
No dev packages
```

**Comment by nosami** [comment]
talking to @joeizang in JabbR... seems this error may just have been caused by the server not being started.

**Comment by david-driscoll** [comment]
Try `0.4.33` and let us know if it's still an issue!
