### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by Camypaper** [OmniSharp/omnisharp-atom#231]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0
**System**: Unknown Windows Version
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.16

### Stack Trace

Uncaught TypeError: Cannot read property 'toString' of undefined

```
At C:\Users\camypaper\.atom\packages\omnisharp-atom\node_modules\omnisharp-node-client\lib\drivers\stdio.js:93

TypeError: Cannot read property 'toString' of undefined
  at StdioDriver.disconnect (C:\Users\camypaper\.atom\packages\omnisharp-atom\node_modules\omnisharp-node-client\lib\drivers\stdio.js:93:76)
  at ChildProcess.<anonymous> (C:\Users\camypaper\.atom\packages\omnisharp-atom\node_modules\omnisharp-node-client\lib\drivers\stdio.js:66:62)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Socket.<anonymous> (child_process.js:1166:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -0:28.8.0 application:new-file (atom-pane.pane.active)
     -0:27.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:26.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
autocomplete-plus, v2.13.1
autocomplete-snippets, v1.5.1
file-icons, v1.5.5
git-plus, v4.5.0
japanese-wrap, v0.2.7
linter, v0.12.2
omnisharp-atom, v0.4.16

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Try `0.4.33` and let us know if it's still an issue!
