### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isOff' of undefined

### ISSUE THREAD

**Issue by usersxm** [OmniSharp/omnisharp-atom#233]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.16

### Stack Trace

Uncaught TypeError: Cannot read property 'isOff' of undefined

```
At /Users/ionic/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.ts:138

TypeError: Cannot read property 'isOff' of undefined
  at OmniSharpAtom.toggle (/Users/ionic/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.ts:138:24)
  at atom-workspace.<anonymous> (/Users/ionic/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.ts:44:97)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/atom.app/Contents/Resources/app.asar/src/window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -7:12.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:52.8.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:02.2.0 omnisharp-atom:toggle (div.deprecation-cop.pane-item.native-key-bindings)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.13.1
omnisharp-atom, v0.4.16

# Dev
No dev packages
```

**Comment by L4D15** [comment]
I have the same error with similar setup.

**Comment by david-driscoll** [comment]
Try `0.4.33` and let us know if it's still an issue!

**Comment by nosami** [comment]
Please re-open if this isn't fixed for you.
