### ISSUE TITLE
Uncaught TypeError: Cannot read property 'codeformatPromise' of undefined

### ISSUE THREAD

**Issue by Binjaaa** [OmniSharp/omnisharp-atom#247]
1. In Atom, Packages/omnisharp => toggle
2. In the omnisharp menu => Code Format

**Atom Version**: 0.198.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.21

### Stack Trace

Uncaught TypeError: Cannot read property 'codeformatPromise' of undefined

```
At C:\Users\Imre\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\code-format.ts:11

TypeError: Cannot read property 'codeformatPromise' of undefined
  at atom-workspace.<anonymous> (C:\Users\Imre\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\code-format.ts:11:28)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Imre\AppData\Local\atom\app-0.198.0\resources\app.asar\src\command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (C:\Users\Imre\AppData\Local\atom\app-0.198.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Imre\AppData\Local\atom\app-0.198.0\resources\app.asar\src\command-registry.js:153:19)
  at EventEmitter.<anonymous> (C:\Users\Imre\AppData\Local\atom\app-0.198.0\resources\app.asar\src\window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -1:07.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:06.9.0 omnisharp-atom:show-build (atom-text-editor.editor.is-focused)
     -1:05.9.0 bracket-matcher:select-inside-brackets (atom-text-editor.editor.is-focused)
     -1:04.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:04.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:03.6.0 core:delete (atom-text-editor.editor.is-focused)
  2x -1:03.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:02.9.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -1:02.3.0 core:copy (atom-text-editor.editor.is-focused)
  2x -1:02.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:01.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:59 editor:newline (atom-text-editor.editor.is-focused)
     -0:57.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:57.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.8.0 omnisharp-atom:toggle (atom-text-editor.editor.is-focused)
     -0:03.5.0 omnisharp-atom:code-format (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
autocomplete-plus, v2.13.1
linter, v0.12.2
omnisharp-atom, v0.4.21

# Dev
No dev packages
```

**Comment by nosami** [comment]
please could you try v0.4.22?

**Comment by david-driscoll** [comment]
Try `0.4.33` and let us know if it's still an issue!
