### ISSUE TITLE
Gulp install issue

### ISSUE THREAD

**Issue by sgwill** [OmniSharp/omnisharp-atom#257]
I just got latest from master, did an `npm install` and had this issue:

```
> omnisharp-node-client@1.2.1 postinstall C:\Users\Sam\projects\omnisharp-atom\node_modules\omnisharp-node-client
> gulp & tsd reinstall

[12:56:23] Using gulpfile ~\projects\omnisharp-atom\node_modules\omnisharp-node-client\gulpfile.js
[12:56:23] Starting 'default'...
[12:56:23] 'default' errored after 10 ms
[12:56:23] Error: ENOENT, no such file or directory 'C:\Users\Sam\projects\omnisharp-atom\node_modules\omnisharp-node-client\node_modules\omnisharp-server-roslyn-binaries\lib\server\omnisharp-server.d.ts'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at Gulp.<anonymous> (C:\Users\Sam\projects\omnisharp-atom\node_modules\omnisharp-node-client\gulpfile.js:35:52)
    at module.exports (C:\Users\Sam\projects\omnisharp-atom\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\Sam\projects\omnisharp-atom\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\Sam\projects\omnisharp-atom\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\Sam\projects\omnisharp-atom\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\Sam\projects\omnisharp-atom\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
```

It appears to be looking for `roslyn-server-binaries` in the `omnisharp-node-client` modules, but it's not there. I deleted node_modules and re-ran `npm-install`, just in case windows locked something, but no joy.

**Comment by sgwill** [comment]
Perhaps this belongs on https://github.com/OmniSharp/omnisharp-node-client?

**Comment by david-driscoll** [comment]
I'm hoping to have this sorted with https://github.com/OmniSharp/omnisharp-node-client/pull/9

**Comment by nosami** [comment]
@sgwill could you see if this issue has gone?

**Comment by sgwill** [comment]
I fetched upstream just now, still getting the same issue.

WAIT

I deleted `omnisharp-node-client` from my packages and it was fixed. Looks like it's been changed to `omnisharp-client` now?

Anyhow, `npm install` worked, but omnisharp won't start. `if (editor.omniProject)` is undefined in `\lib\omni-sharp-server\client-manager`

**Comment by sgwill** [comment]
Okay. When I removed node_modules and tried again it worked. I'm calling this fixed.

**Comment by Mpdreamz** [comment]
yeah npm does a horrible job cleaning up :) 

`rm -rf node_modules && npm install` will fix it
