### ISSUE TITLE
DirectoryNotFoundException when starting Omnisharp server in Atom

### ISSUE THREAD

**Issue by douglasstarnes** [OmniSharp/omnisharp-atom#276]
I'm getting similar errors on both OS X and Ubuntu 14.04 (I haven't tried Windows yet).  Basically it's throwing a DirectoryNotFoundException and complaining about a path that always ends in null which of course doesn't exist or the exception would not be present.  Here is the stack track from OS X (Atom on Ubuntu won't let me select the trace text) :

```
System.IO.DirectoryNotFoundException: Directory '/null' not found.
  at System.IO.Directory.ValidateDirectoryListing (System.String path, System.String searchPattern, System.Boolean& stop) [0x00000] in :0 
  at System.IO.Directory+c__Iterator0.MoveNext () [0x00000] in :0 
  at System.IO.DirectoryInfo+c__Iterator1.MoveNext () [0x00000] in :0 
  at System.Linq.Enumerable.Any[FileInfo] (IEnumerable`1 source) [0x00000] in :0 
  at OmniSharp.AspNet5.AspNet5Paths.ResolveRootDirectory (System.String projectPath) [0x00000] in :0 
  at OmniSharp.AspNet5.AspNet5Paths.GetRuntimePath () [0x00000] in :0 
  at OmniSharp.AspNet5.AspNet5Paths..ctor (IOmnisharpEnvironment env, OmniSharp.Options.OmniSharpOptions options, ILoggerFactory loggerFactory) [0x00000] in :0 
  at OmniSharp.AspNet5.AspNet5ProjectSystem..ctor (OmniSharp.OmnisharpWorkspace workspace, IOmnisharpEnvironment env, IOptions`1 optionsAccessor, ILoggerFactory loggerFactory, IMetadataFileReferenceCache metadataFileReferenceCache, IApplicationLifetime lifetime, IFileSystemWatcher watcher, IEventEmitter emitter, OmniSharp.AspNet5.AspNet5Context context) [0x00000] in :0 
  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00000] in :0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in :0 
  at Microsoft.Framework.DependencyInjection.ServiceLookup.Service+ConstructorCallSite.Invoke (Microsoft.Framework.DependencyInjection.ServiceProvider provider) [0x00000] in :0 
  at Microsoft.Framework.DependencyInjection.ServiceProvider+ScopedCallSite.Invoke (Microsoft.Framework.DependencyInjection.ServiceProvider provider) [0x00000] in :0 
  at Microsoft.Framework.DependencyInjection.ServiceProvider+SingletonCallSite.Invoke (Microsoft.Framework.DependencyInjection.ServiceProvider provider) [0x00000] in :0 
  at Microsoft.Framework.DependencyInjection.ServiceLookup.ClosedIEnumerableService+CallSite.Invoke (Microsoft.Framework.DependencyInjection.ServiceProvider provider) [0x00000] in :0 
  at Microsoft.Framework.DependencyInjection.ServiceProvider+TransientCallSite.Invoke (Microsoft.Framework.DependencyInjection.ServiceProvider provider) [0x00000] in :0 
  at Microsoft.Framework.DependencyInjection.ServiceProvider+<>c__DisplayClass8_0.b__0 (Microsoft.Framework.DependencyInjection.ServiceProvider provider) [0x00000] in :0 
  at Microsoft.Framework.DependencyInjection.ServiceProvider.GetService (System.Type serviceType) [0x00000] in :0 
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService (IServiceProvider provider, System.Type serviceType) [0x00000] in :0 
  at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[IEnumerable`1] (IServiceProvider provider) [0x00000] in :0 
  at OmniSharp.Startup.Configure (IApplicationBuilder app, ILoggerFactory loggerFactory, IOmnisharpEnvironment env, ISharedTextWriter writer) [0x00000] in :0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in :0
```

**Comment by Mpdreamz** [comment]
Got this too when starting omnisharp e.g in our omnisharp-atom project, pushed a fix here: https://github.com/OmniSharp/omnisharp-node-client/pull/10

**Comment by nosami** [comment]
This should be fixed in v0.4.30. You'll need to make sure you have Atom v0.199. Please re-open if it's not fixed!

**Comment by douglasstarnes** [comment]
I'm still seeing the exception in the OmniSharp output panel.  I'm also still seeing alerts from Atom with the following error report:

```
1. Create a new C# file
2. Start typing 
3. Or open a C# file

**Atom Version**: 0.199.0
**System**: linux 3.13.0-52-generic
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.30


### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of null

At /home/userhome/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:130

TypeError: Cannot read property 'stdin' of null
  at StdioDriver.request (/home/userhome/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:130:22)
  at Client.OmnisharpClient.request (/home/userhome/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/omnisharp-client.js:108:35)
  at Client.OmnisharpClient.codecheck (/home/userhome/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/omnisharp-client.js:217:21)
  at Client.OmnisharpClient.codecheckPromise (/home/userhome/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/omnisharp-client.js:220:21)
  at LinterCSharp.lintFile (/home/userhome/.atom/packages/omnisharp-atom/lib/omnisharp-atom/linter.ts:41:21)
  at /home/userhome/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /home/userhome/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -2:14.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:11.2.0 core:close (ul.list-inline.tab-bar.inset-panel)
     -0:08.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:00.3.0 omnisharp-atom:code-format-on-semicolon (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
linter, v0.12.2
omnisharp-atom, v0.4.30

# Dev
No dev packages
```

**Comment by nosami** [comment]
@douglasstarnes Please could you try v0.6.5? 

There was a bug in omnisharp-roslyn that caused it to not launch for a large number of msbuild solutions.

**Comment by douglasstarnes** [comment]
@nosami I will try it tonight. Thanks!

**Comment by douglasstarnes** [comment]
At first when I tried to install omnisharp-atom it failed.  Then the second time it worked.  However, I am getting the same error as in #301 but a different file.  I'll post the new stack trace in the other issue.  But omnisharp-atom does load correctly in 0.6.5 and Atom 0.200.

**Comment by nosami** [comment]
@douglasstarnes is anything working? Do you get the green flame?

**Comment by douglasstarnes** [comment]
@nosami I get the flame but it doesn't turn green when I click on it.  Just shows the OmniSharp pane.  Ctrl-Opt-O does nothing on the Mac either.  And I don't get any output in the OmniSharp pane either.  But when I put a semicolon at the end of a statement I get the error in #301.  And I should point out that this is a fresh install.  I removed Atom and wiped out my .atom directory and started from nothing.

**Comment by nosami** [comment]
Unfortunately, I don't think I have enough information (even with the stack traces) to understand what's going on here.

What happens if you quit atom and type `atom /folder/containing/your/sln` from the terminal?

**Comment by nosami** [comment]
What happens if you 
```bash
cd /src/folder/containing/sln
~/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/omnisharp
```
