### ISSUE TITLE
Uncaught Error: Cannot find module './drivers/stdio'

### ISSUE THREAD

**Issue by joeizang** [OmniSharp/omnisharp-atom#284]
[Enter steps to reproduce below:]

1. ...just tried to open a folder containing an asp.net mvc 5 app
2. ...

**Atom Version**: 0.199.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.29

### Stack Trace

Uncaught Error: Cannot find module './drivers/stdio'

```
At module.js:330

Error: Cannot find module './drivers/stdio'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\IZANG\AppData\Local\atom\app-0.199.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Client.OmnisharpClient (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\omnisharp-node-client\lib\omnisharp-client.js:49:29)
  at new Client (C:\Users\IZANG\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client.ts:12:16)
  at C:\Users\IZANG\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client-manager.ts:28:26
  at arrayEach (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\lodash\index.js:1361:13)
  at Function.<anonymous> (C:\Users\IZANG\.atom\packages\omnisharp-atom\node_modules\lodash\index.js:3405:13)
  at ClientManager.updatePaths (C:\Users\IZANG\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client-manager.ts:27:11)
  at C:\Users\IZANG\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client-manager.ts:15:71
  at Emitter.module.exports.Emitter.emit (C:\Users\IZANG\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Project.module.exports.Project.addPath (C:\Users\IZANG\AppData\Local\atom\app-0.199.0\resources\app.asar\src\project.js:274:29)
  at EventEmitter.<anonymous> (C:\Users\IZANG\AppData\Local\atom\app-0.199.0\resources\app.asar\src\window-event-handler.js:37:32)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "base16-tomorrow-light-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
linter, v0.12.2
omnisharp-atom, v0.4.29

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Try `0.4.33` and let us know if it's still an issue!
