### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdin' of null

### ISSUE THREAD

**Issue by hmemcpy** [OmniSharp/omnisharp-atom#298]
Hmm, no idea what happened.
This worked perfectly before, I put the computer to sleep. Came back later - this started happening.
Also after restarting Atom.

**Atom Version**: 0.199.0
**System**: Microsoft Windows 10 Enterprise Insider Preview
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.29

### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of null

```
At C:\Users\Igal\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:130

TypeError: Cannot read property 'stdin' of null
  at StdioDriver.request (C:\Users\Igal\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:130:22)
  at Client.OmnisharpClient.request (C:\Users\Igal\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\omnisharp-client.js:108:35)
  at Client.OmnisharpClient.typelookup (C:\Users\Igal\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\omnisharp-client.js:400:21)
  at Client.OmnisharpClient.typelookupPromise (C:\Users\Igal\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\omnisharp-client.js:403:21)
  at Tooltip.showToolTip (C:\Users\Igal\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\lookup.ts:115:21)
  at Tooltip.showExpressionTypeOnMouseOver (C:\Users\Igal\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\lookup.ts:94:14)
  at C:\Users\Igal\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\lookup.ts:46:75

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
autoclose-html, v0.16.0
browser-refresh, v0.8.3
git-plus, vundefined
language-spec, v0.1.0
linter, v0.12.2
monokai, v0.14.0
omnisharp-atom, v0.4.29
open-in-browser, vundefined
spec-maker, v0.4.0

# Dev
settings-view, v0.185.0
```

**Comment by nosami** [comment]
This should be fixed in v0.4.30. You'll need to make sure you have Atom v0.199. Please re-open if it's not fixed!

**Comment by nosami** [comment]
I just noticed that I get this error if the server fails to start.

**Comment by nosami** [comment]
@hmemcpy Could you try this with v0.6.5? There was an issue with the server failing for msbuild projects that could have caused this error.

**Comment by rschweter** [comment]
I'm getting this in 0.9.1 / 0.204.0

**Comment by LiquaFoo** [comment]
I'm also receiving this error.

## Stack Trace

```
Uncaught TypeError: Cannot read property 'stdin' of null

At /Users/liquafoo/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

TypeError: Cannot read property 'stdin' of null
  at StdioDriver.request (/Users/liquafoo/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:134:22)
  at Client.ServerClient.handleResult (/Users/liquafoo/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/clients/server-client.js:144:35)
  at AnonymousObserver._onNext (/Users/liquafoo/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/clients/server-client.js:123:58)
  at Client.ServerClient.request (/Users/liquafoo/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/clients/server-client.js:187:29)
  at Client.request (/Users/liquafoo/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client.js:93:69)
  at Client.ServerClient.gotodefinition (/Users/liquafoo/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/clients/server-client.js:385:21)
  at /Users/liquafoo/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:92:64
  at clientCallback (/Users/liquafoo/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:84:21)
  at ConnectableObservable.connect (/Users/liquafoo/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.binding.js:471:67)
  at /Users/liquafoo/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.binding.js:486:62
  at Omni.request (/Users/liquafoo/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:105:16)
  at GoToDefinition.underlineIfNavigable (/Users/liquafoo/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:92:14)
  at /Users/liquafoo/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:34:79
From previous event:
  at ClientManager.getClientForEditor (/Users/liquafoo/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client-manager.js:182:44)
  at Omni.request (/Users/liquafoo/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:94:30)
  at GoToDefinition.underlineIfNavigable (/Users/liquafoo/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:92:14)
  at /Users/liquafoo/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:34:79
From previous event:
  at Omni.request (/Users/liquafoo/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:95:18)
  at GoToDefinition.underlineIfNavigable (/Users/liquafoo/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:92:14)
  at /Users/liquafoo/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:34:79
From previous event:
  at Omni.request (/Users/liquafoo/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:96:18)
  at GoToDefinition.underlineIfNavigable (/Users/liquafoo/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:92:14)
  at /Users/liquafoo/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:34:79

```

## Packages

```
atom-beautify@0.27.9
atom-yeoman@0.3.1
color-picker@2.0.2
emmet@2.3.10
file-icons@1.5.6
javascript-snippets@1.0.0
linter@0.12.6
linter-csslint@0.0.13
linter-jshint@0.1.5
linter-shellcheck@0.0.8
linter-tslint@0.2.2
merge-conflicts@1.3.2
monokai@0.14.0
omnisharp-atom@0.10.0
```

**Comment by nosami** [comment]
@LiquaFoo this error occurs when the server fails to start. Could you look at the 'OmniSharp output' panel and paste the results in here?

**Comment by LiquaFoo** [comment]
### OmniSharp Output
```
Starting OmniSharp server (pid:9928)
OmniSharp Location: /Users/signup4/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/omnisharp
Change the location that OmniSharp is loaded from by setting the OMNISHARP environment variable
OmniSharp Path: /Users/liquafoo/Sites/Hello World
System.Composition.Hosting.CompositionFailedException: No importing constructor was found on type 'Microsoft.CodeAnalysis.Options.OptionsServiceFactory'.
  at System.Composition.TypedParts.Discovery.DiscoveredPart+<GetPartActivatorDependencies>d__d.MoveNext () [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable+<CreateConcatIterator>c__Iterator1`1[System.Composition.Hosting.Core.CompositionDependency].MoveNext () [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable+<CreateWhereIterator>c__Iterator1E`1[System.Composition.Hosting.Core.CompositionDependency].MoveNext () [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.ToArray[CompositionDependency] (IEnumerable`1 source) [0x00000] in <filename unknown>:0 
  at System.Composition.TypedParts.Discovery.DiscoveredPart.GetDependencies (System.Composition.Hosting.Core.DependencyAccessor definitionAccessor) [0x00000] in <filename unknown>:0 
  at System.Composition.TypedParts.Discovery.DiscoveredExport+<>c__DisplayClass2.<GetExportDescriptorPromise>b__0 () [0x00000] in <filename unknown>:0 
  at System.Composition.Hosting.Core.ExportDescriptorPromise+<>c__DisplayClass4.<.ctor>b__0 () [0x00000] in <filename unknown>:0 
  at System.Lazy`1[System.Collections.ObjectModel.ReadOnlyCollection`1[System.Composition.Hosting.Core.CompositionDependency]].InitValue () [0x00000] in <filename unknown>:0

```

**Comment by nosami** [comment]
@LiquaFoo what's the output from 'dnvm list'?

**Comment by LiquaFoo** [comment]
Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta4          mono         ~/.dnx/runtimes      default

**Comment by nosami** [comment]
@LiquaFoo no idea what's causing that. What mono version are you using? There are some known issues with mono 4.01

**Comment by ludos1978** [comment]
i am getting this error as well. i am using it with unity3d 5.1.1.

[Enter steps to reproduce below:]

1. opened unity and set atom as editor for the project
2. got this error on opening an existing project

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.17.0


### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of null

```
At /Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

TypeError: Cannot read property 'stdin' of null
    at StdioDriver.request (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:156:22)
    at ClientBase.handleResult (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/clients/client-base.js:208:35)
    at AnonymousObserver._onNext (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/clients/client-base.js:183:58)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1778:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at AnonymousObserver._onNext (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.backpressure.js:230:21)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1778:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at AnonymousObserver.tryCatcher (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at next (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.backpressure.js:170:13)
    at AnonymousObserver._onNext (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.backpressure.js:178:13)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1778:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at AnonymousObserver.tryCatcher (/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
```

### Commands

```
     -7:34 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:15.3.0 window:install-shell-commands (atom-pane.pane.active)
     -6:29.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -6:14.7.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -6:14.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -6:13.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:08.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:08.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -6:05.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  4x -5:28.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -2:35.1.0 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
     -2:21.1.0 tree-view:toggle-focus (atom-pane.pane.active)
     -2:07.3.0 symbols-view:toggle-file-symbols (atom-pane.pane.active)
     -1:54.9.0 pane:split-left (atom-pane.pane.active)
     -1:39.1.0 pane:close (atom-pane.pane.active)
     -1:33.5.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
omnisharp-atom, v0.17.0

# Dev
No dev packages
```

**Comment by ludos1978** [comment]
omnisharp output also gives

```

Errors & WarningsOmnisharp output
Starting OmniSharp server (pid:18764)
OmniSharp Location: /Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/omnisharp
Change the location that OmniSharp is loaded from by setting the OMNISHARP environment variable
OmniSharp Path: /Users/rspoerri/_REPOSITORIES/_PROJECTS/_Elefant_Landesmuseum_Fotoarchiv/_LandiFotoArchiv_REPO
Can't find custom attr constructor image: /Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/packages/Microsoft.AspNet.Cryptography.Internal/1.0.0-beta4/lib/dnx451/Microsoft.AspNet.Cryptography.Internal.dll mtoken: 0x0a000004
* Assertion at class.c:5695, condition `!mono_loader_get_last_error ()' not met
unknown
* Assertion at class.c:5695, condition `!mono_loader_get_last_error ()' not met
unknown
Stacktrace:

  at <unknown> <0xffffffff>
  at Microsoft.Framework.DependencyInjection.DataProtectionServices/<GetDefaultServices>d__0.MoveNext () <0x0021b>
  at Microsoft.Framework.DependencyInjection.ServiceCollectionExtensions.TryAdd (Microsoft.Framework.DependencyInjection.IServiceCollection,System.Collections.Generic.IEnumerable`1<Microsoft.Framework.DependencyInjection.ServiceDescriptor>) <0x00064>
  at Microsoft.Framework.DependencyInjection.DataProtectionServiceCollectionExtensions.AddDataProtection (Microsoft.Framework.DependencyInjection.IServiceCollection) <0x0002b>
  at Microsoft.Framework.DependencyInjection.MvcServiceCollectionExtensions.ConfigureDefaultServices (Microsoft.Framework.DependencyInjection.IServiceCollection) <0x0001b>
  at Microsoft.Framework.DependencyInjection.MvcServiceCollectionExtensions.AddMvc (Microsoft.Framework.DependencyInjection.IServiceCollection) <0x00013>
  at OmniSharp.Startup.ConfigureServices (Microsoft.Framework.DependencyInjection.IServiceCollection) <0x0003f>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr) <0xffffffff>
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <0xffffffff>
0Assets/_SCRIPTS/DragableImage.cs*35:1
UTF-8C#master+35
Uncaught TypeError: Cannot read property 'stdin' of null
/Users/rspoerri/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579
Show Stack Trace
The error was thrown from the omnisharp-atom package. This issue has already been reported.
View Issue
```

**Comment by ludos1978** [comment]
updating mono to version 4 did fix this error.
http://www.mono-project.com/download/

**Comment by david-driscoll** [comment]
Tracking on #433
