### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#299]
[Enter steps to reproduce below:]

1. Update omnisharp-atom
2. BOOM

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.30

### Stack Trace

Failed to activate the linter package

```
At L3: Declaration or statement expected.
L3: ';' expected.

Error: L3: Declaration or statement expected.
L3: ';' expected.
    at TypeScriptSimple.toJavaScript (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/typescript-simple/index.js:118:23)
    at TypeScriptSimple.compile (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/typescript-simple/index.js:50:25)
    at transpile (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/typescript.js:86:14)
    at Object.loadFile [as .ts] (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/typescript.js:98:67)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/dfowler/.atom/packages/omnisharp-atom/lib/omnisharp-atom/linter.ts:9:12)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .ts] (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/typescript.js:99:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at LinterInitializer.activate (/Users/dfowler/.atom/packages/linter/lib/init.coffee:107:30)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "git-diff",
      "language-git"
    ]
  },
  "omnisharp-atom": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
language-csharp, v0.5.0
linter, v0.12.2
omnisharp-atom, v0.4.30

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Try `0.4.33`.

**Comment by davidfowl** [comment]
Fixed
