### ISSUE TITLE
Failed to load the omnisharp-atom package after upgrading to 0.4.30

### ISSUE THREAD

**Issue by hmemcpy** [OmniSharp/omnisharp-atom#300]
```
Error: L3: Declaration or statement expected.
L3: ';' expected.
    at TypeScriptSimple.toJavaScript (C:\Users\Igal\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\typescript-simple\index.js:118:23)
    at TypeScriptSimple.compile (C:\Users\Igal\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\typescript-simple\index.js:50:25)
    at transpile (C:\Users\Igal\AppData\Local\atom\app-0.199.0\resources\app.asar\src\typescript.js:86:14)
    at Object.loadFile [as .ts] (C:\Users\Igal\AppData\Local\atom\app-0.199.0\resources\app.asar\src\typescript.js:98:67)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\Igal\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.ts:5:12)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .ts] (C:\Users\Igal\AppData\Local\atom\app-0.199.0\resources\app.asar\src\typescript.js:99:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\Igal\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:707:34)
```

**Comment by nosami** [comment]
I just nuked my git repo and installed the package from the atom repo and got the same error on install.

I 'fixed' it by cd'ing to `~/.atom/packages/omnisharp-atom` and running `npm install`

**Comment by david-driscoll** [comment]
Looks like we have a fix for this now, sorry!

Try `0.4.33` and let us know if it works for you!

**Comment by archerface** [comment]
I am getting this error. I tried the previous mentioned temporary fix and got a bunch of errors from node.
![capture](https://cloud.githubusercontent.com/assets/7389510/12874727/bc3ce3be-cd96-11e5-9f96-5f1260f4701c.PNG)
