### ISSUE TITLE
Uncaught TypeError: Cannot read property 'gotodefinitionPromise' of undefined

### ISSUE THREAD

**Issue by hmemcpy** [OmniSharp/omnisharp-atom#308]
[Enter steps to reproduce below:]

1. Created a new atom window (File -> New Window)
2. Create a new file (File -> New File)
3. Press the 'Show Markdown Preview' shortcut (Ctrl-Shift-M)

**Atom Version**: 0.199.0
**System**: Microsoft Windows 10 Enterprise Insider Preview
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.4.33

### Stack Trace

Uncaught TypeError: Cannot read property 'gotodefinitionPromise' of undefined

```
At C:\Users\Igal\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\go-to-definition.ts:94

TypeError: Cannot read property 'gotodefinitionPromise' of undefined
  at GoToDefinition.underlineIfNavigable (C:\Users\Igal\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\go-to-definition.ts:94:20)
  at C:\Users\Igal\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\go-to-definition.ts:47:79

```

### Commands

```
     -0:01.5.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
autoclose-html, v0.16.0
browser-refresh, v0.8.3
git-plus, vundefined
language-spec, v0.1.0
linter, v0.12.2
monokai, v0.14.0
omnisharp-atom, v0.4.33
open-in-browser, vundefined
spec-maker, v0.4.0

# Dev
settings-view, v0.185.0
```

**Comment by nosami** [comment]
Should be fixed in v0.5.0. Please re-open if it isn't!
