### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filesChangedPromise' of undefined

### ISSUE THREAD

**Issue by davidfowl** [OmniSharp/omnisharp-atom#312]
[Enter steps to reproduce below:]

1. Save project.json
2. BOOM

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'filesChangedPromise' of undefined

```
At /Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:759

TypeError: Cannot read property 'filesChangedPromise' of undefined
  at /Users/dfowler/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/package-restore.ts:16:32
  at Emitter.module.exports.Emitter.emit (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:917:20)
  at TextBuffer.module.exports.TextBuffer.save (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:899:19)
  at TextEditor.module.exports.TextEditor.save (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:567:26)
  at Pane.module.exports.Pane.saveItem (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:585:35)
  at atom-workspace.atom.commands.add.core:save (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:310:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/dfowler/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:02.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-diff",
      "language-git"
    ],
    "themes": [
      "unity-ui",
      "atom-github-2014-syntax"
    ]
  },
  "omnisharp-atom": {}
}
```

### Installed Packages

```coffee
# User
atom-github-2014-syntax, v1.5.0
atom-yeoman, v0.2.0
language-csharp, v0.5.0
linter, v0.12.3
omnisharp-atom, v0.5.0
unity-ui, v2.0.8

# Dev
No dev packages
```

**Comment by nosami** [comment]
fixed by https://github.com/OmniSharp/omnisharp-atom/commit/388c1857d5e957a9c56f842a4e3124a14ceb8c12
