### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addListener' of undefined

### ISSUE THREAD

**Issue by weima-sage** [OmniSharp/omnisharp-atom#352]
1. Split a source file vertically;
2. Open another source file;
3. Try to drag the newly opened file to panel below.

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.9.1

### Stack Trace

Uncaught TypeError: Cannot read property 'addListener' of undefined

```
At /Users/wema/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.async.js:425

TypeError: Cannot read property 'addListener' of undefined
  at Function.Observable.fromEvent (/Users/wema/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.async.js:425:16)
  at /Users/wema/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/go-to-definition.js:31:43
  at Emitter.module.exports.Emitter.emit (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/wema/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:142:31
  at /Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:272:16
  at /Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:329:18
  at Emitter.module.exports.Emitter.emit (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-container.js:375:27)
  at /Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-container.js:362:26
  at Emitter.module.exports.Emitter.emit (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:326:20)
  at Pane.module.exports.Pane.moveItemToPane (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:415:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:571:18)
  at TabBarView.module.exports.TabBarView.onDrop (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:491:23)
  at space-pen-ul.<anonymous> (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Users/wema/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  7x -5:38 blur (atom-text-editor.editor.mini.is-focused)
     -5:04.9.0 vim-mode:activate-characterwise-visual-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
 22x -5:04.7.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -5:00.4.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
 13x -4:58.8.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  6x -4:52.9.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -4:50.9.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -4:50.5.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -4:50.2.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -4:50.1.0 blur (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -4:49.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -4:49.9.0 blur (atom-text-editor.editor.mini.is-focused)
 24x -4:49.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
 23x -4:04.5.0 blur (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -1:08.3.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-atom-light-ui)
 14x -1:08.2.0 blur (div.deprecation-cop-status.inline-block.text-warning)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ],
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.9
atom-pair, v1.1.6
atom-yeoman, v0.3.1
atomatigit, v1.5.2
editor-stats, v0.17.0
ex-mode, v0.5.1
language-fsharp, v0.8.4
linter, v0.12.6
omnisharp-atom, v0.9.1
vim-mode, v0.49.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Nice catch... I can repro, fixing now.

**Comment by nosami** [comment]
I just got this error. I had a tab open (on startup) for a cs file that no longer existed because of a branch change

**Comment by david-driscoll** [comment]
Clearly you shouldn't do that. ;)

That helps though, thanks!
