### ISSUE TITLE
Uncaught TypeError: Cannot read property 'model' of undefined

### ISSUE THREAD

**Issue by austincummings** [OmniSharp/omnisharp-atom#357]
Just booted up Atom and opened a C# file.

**Atom Version**: 0.204.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.9.1

### Stack Trace

Uncaught TypeError: Cannot read property 'model' of undefined

```
At C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:579

TypeError: Cannot read property 'model' of undefined
  at MapObserver.selector (C:\Users\Austin\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni.js:108:68)
  at ReplaySubject.Rx.ReplaySubject.addProperties.onNext (C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.binding.js:410:20)
  at AnonymousObserver._onNext (C:\Users\Austin\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client-manager.js:69:66)
  at AnonymousObserver._onNext (C:\Users\Austin\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client-manager.js:246:21)
  at handler (C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.async.js:373:20)
  at C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\node_modules\globby\index.js:74:3
  at C:\Users\Austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:251:17
  at done (C:\Users\Austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:132:19)
  at C:\Users\Austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:32:16
  at C:\Users\Austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:248:21
  at C:\Users\Austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\request\node_modules\form-data\node_modules\async\lib\async.js:572:34
  at C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\node_modules\globby\index.js:65:5
  at f (C:\Users\Austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\babel-core\node_modules\regenerator\node_modules\commoner\node_modules\glob\node_modules\once\once.js:17:25)
  at Glob.<anonymous> (C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\glob\glob.js:132:7)
  at emitOne (events.js:77:13)
  at Glob.emit (events.js:166:7)
  at Glob._finish (C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\glob\glob.js:171:8)
  at done (C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\glob\glob.js:158:12)
  at Glob._processReaddir2 (C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\glob\glob.js:353:12)
  at C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\glob\glob.js:345:17
  at RES (C:\Users\Austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\babel-core\node_modules\regenerator\node_modules\commoner\node_modules\glob\node_modules\inflight\inflight.js:23:14)
  at f (C:\Users\Austin\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\babel-core\node_modules\regenerator\node_modules\commoner\node_modules\glob\node_modules\once\once.js:17:25)
  at Glob._readdirError (C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\glob\glob.js:579:10)
  at C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\glob\glob.js:521:12
  at FSReqWrap.oncomplete (fs.js:77:15)
From previous event:
    at Function.Object.defineProperty.get [as activeModel] (C:\Users\Austin\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni.js:108:41)
    at FindPaneWindow.ReactClientComponent.componentDidMount (C:\Users\Austin\.atom\packages\omnisharp-atom\lib\omnisharp-atom\views\react-client-component.js:20:33)
    at FindPaneWindow.componentDidMount (C:\Users\Austin\.atom\packages\omnisharp-atom\lib\omnisharp-atom\views\find-pane-view.js:24:34)
    at CallbackQueue.assign.notifyAll (C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\react\lib\CallbackQueue.js:68:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\react\lib\ReactReconcileTransaction.js:81:26)
    at ReactReconcileTransaction.Mixin.closeAll (C:\Users\Austin\.atom\packages\omnisharp-atom\node_modules\react\lib\Transaction.js:207:25)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.1
autocomplete-emojis, vundefined
linter, v0.12.6
minimap, v4.9.0
omnisharp-atom, v0.9.1

# Dev
No dev packages
```

**Comment by diman3241** [comment]
+1

**Comment by somnuk-wk** [comment]
+1 same problem on osx.

**Comment by pauliusnorkus** [comment]
+1

**Comment by nosami** [comment]
What output is there from the 'Omnisharp output' panel? I just got this error when the server failed to start.

The latest version of omnisharp-atom requires mono 4.0.1 and dnx beta4 installed.

**Comment by mishfit** [comment]
$mono --version
Mono JIT compiler version 4.0.1 (tarball Fri Jun  5 13:22:30 PDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$ dnvm list

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta4          mono         ~/.dnx/runtimes      default
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting OmniSharp server (pid:6836)
OmniSharp Location: /Users/mishochu/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/omnisharp
Change the location that OmniSharp is loaded from by setting the OMNISHARP environment variable
OmniSharp Path: /Users/mishochu/Source/Github/Spectra/RTBA/Solutions/RealtimeWeb
Can't find custom attr constructor image: /Users/mishochu/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/packages/Microsoft.AspNet.Cryptography.Internal/1.0.0-beta4/lib/dnx451/Microsoft.AspNet.Cryptography.Internal.dll mtoken: 0x0a000004
* Assertion at class.c:5695, condition `!mono_loader_get_last_error ()' not met
unknown
* Assertion at class.c:5695, condition `!mono_loader_get_last_error ()' not met
unknown
Stacktrace:

  at <unknown> <0xffffffff>
  at Microsoft.Framework.DependencyInjection.DataProtectionServices/<GetDefaultServices>d__0.MoveNext () <0x0021b>
  at Microsoft.Framework.DependencyInjection.ServiceCollectionExtensions.TryAdd (Microsoft.Framework.DependencyInjection.IServiceCollection,System.Collections.Generic.IEnumerable`1<Microsoft.Framework.DependencyInjection.ServiceDescriptor>) <0x00064>
  at Microsoft.Framework.DependencyInjection.DataProtectionServiceCollectionExtensions.AddDataProtection (Microsoft.Framework.DependencyInjection.IServiceCollection) <0x0002b>
  at Microsoft.Framework.DependencyInjection.MvcServiceCollectionExtensions.ConfigureDefaultServices (Microsoft.Framework.DependencyInjection.IServiceCollection) <0x0001b>
  at Microsoft.Framework.DependencyInjection.MvcServiceCollectionExtensions.AddMvc (Microsoft.Framework.DependencyInjection.IServiceCollection) <0x00013>
  at OmniSharp.Startup.ConfigureServices (Microsoft.Framework.DependencyInjection.IServiceCollection) <0x00057>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr) <0xffffffff>
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) <0xffffffff>
0RealtimeWeb/Global.asax.cs1:1
Command
UTF-8C#master

**Comment by 4fthawaiian** [comment]
weirdly enough, mine was working fine, then "developed" this issue. Yayyyy, so +1 I guess :/

**Comment by nosami** [comment]
@mishfit is it possible that you have another installation of mono somewhere? maybe installed by brew?
Atom will use the brew version of mono if it's installed.

The error that you are seeing is definitely caused by an older version of mono being used.

**Comment by mishfit** [comment]
Interestingly enough my brew version of mono is 4.0.1 while Xamarin was still on 3.x. It wasn't until I updated Xamarin that omnisharp-atom started working...so I imagine it isn't using my brew install. Nevertheless, omnisharp-atom is now working!

**Comment by robbennet** [comment]
+1

**Comment by kiran94** [comment]
+1

**Comment by davidsvson** [comment]
+1

**Comment by nosami** [comment]
+1 doesn't help

OS / mono versions? dnvm list output? brew install / xamarin install / both?

What's the output from the server?

![screen shot 2015-06-27 at 18 49 02](https://cloud.githubusercontent.com/assets/667194/8393203/3dd4ce3c-1cfd-11e5-9b96-0003759003b6.png)

**Comment by robbennet** [comment]
I can confirm that omnisharp is not using homebrew'd mono if you have xamarin installed.  Updated all the Xamarin things and it works now.  3 of us in the office did this with success. Granted I still don't have code completion or any omnisharp-ness actually working, but no errors anymore (I am the only 1 of the 3 of us who still is having problems, other 2 guys are good just by updating xamarin and Xamarin deps).

**Comment by nosami** [comment]
@robbennet I think you need to install dnvm - https://github.com/aspnet/Home

**Comment by MichaelAquilina** [comment]
Have the same problem on Ubuntu 14.04

**Comment by nosami** [comment]
+1 doesn't help

OS / mono versions? dnvm list output? brew install / xamarin install / both?

What's the output from the server?

![screen shot 2015-06-27 at 18 49 02](https://cloud.githubusercontent.com/assets/667194/8393203/3dd4ce3c-1cfd-11e5-9b96-0003759003b6.png)

**Comment by nosami** [comment]
You need mono 4.0.1 and dnx 1.0.0-beta4

**Comment by MateyByrd** [comment]
For anyone that encounters this problem (on OS X), I fixed it by removing my installation of mono, do this by running the script from their [website](http://www.mono-project.com/docs/about-mono/supported-platforms/osx/), make sure all mono applications are closed so for example Atom. Then install mono via [brew](http://brew.sh), [here's](http://podtynnyi.com/2013/02/02/install-mono-on-mac-os-x-via-homebrew/) how to do that. Start up Atom and in my case it was fixed.

**Comment by MichaelAquilina** [comment]
What version of mono does brew install? What version did you have before that? Might help us on the linux side too if it's just an issue in a specific mono version.

**Comment by MateyByrd** [comment]
There is no way to figure out which version I had before since I don't know and it's removed. So thats a bummer. The version installed with brew right now is mono 4.0.2.5 (I got this from entering $ brew list mono in the terminal app).

**Comment by MichaelAquilina** [comment]
My Mono version is pretty outdated compared to yours 
```
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu2.1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

so the issue might be to do with old versions.

**Comment by nosami** [comment]
If you have both homebrew and Xamarin official versions of mono installed, then currently Atom is using the Xamarin version first.

I submitted a PR to make the plugin prefer the homebrew version here https://github.com/OmniSharp/omnisharp-node-client/pull/18
