### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by Camypaper** [OmniSharp/omnisharp-atom#360]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.204.0
**System**: Unknown Windows Version
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.10.0

### Stack Trace

Uncaught TypeError: object is not a function

```
At C:\Users\camypaper\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:579

TypeError: object is not a function
  at new Feature (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:26:26)
  at MapObserver.<anonymous> (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:130:43)
  at handler (C:\Users\camypaper\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.async.js:373:20)
  at FSReqWrap.oncomplete (fs.js:77:15)
From previous event:
  at ConnectableObservable.Rx.ConnectableObservable.ConnectableObservable.refCount (C:\Users\camypaper\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.binding.js:483:14)
  at C:\Users\camypaper\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.async.js:378:24
  at OmniSharpAtom.loadFeatures (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:124:68)
  at OmniSharpAtom.activate (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:78:18)
  at Package.module.exports.Package.activateNow (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:238:19)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:219:30
  at Package.module.exports.Package.measure (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:163:15)
  at Package.module.exports.Package.activate (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package-manager.js:435:21)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:292:29
  at exit (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:41:16)
  at triggerExitCallback (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
From previous event:
  at OmniSharpAtom.loadFeatures (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:125:14)
  at OmniSharpAtom.activate (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:78:18)
  at Package.module.exports.Package.activateNow (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:238:19)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:219:30
  at Package.module.exports.Package.measure (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:163:15)
  at Package.module.exports.Package.activate (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package-manager.js:435:21)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:292:29
  at exit (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:41:16)
  at triggerExitCallback (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
From previous event:
  at OmniSharpAtom.loadFeatures (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:125:14)
  at OmniSharpAtom.activate (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:78:18)
  at Package.module.exports.Package.activateNow (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:238:19)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:219:30
  at Package.module.exports.Package.measure (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:163:15)
  at Package.module.exports.Package.activate (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package-manager.js:435:21)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:292:29
  at exit (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:41:16)
  at triggerExitCallback (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
From previous event:
  at OmniSharpAtom.loadFeatures (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:126:14)
  at OmniSharpAtom.activate (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:78:18)
  at Package.module.exports.Package.activateNow (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:238:19)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:219:30
  at Package.module.exports.Package.measure (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:163:15)
  at Package.module.exports.Package.activate (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package-manager.js:435:21)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:292:29
  at exit (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:41:16)
  at triggerExitCallback (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
From previous event:
  at OmniSharpAtom.loadFeatures (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:127:14)
  at OmniSharpAtom.activate (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:78:18)
  at Package.module.exports.Package.activateNow (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:238:19)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:219:30
  at Package.module.exports.Package.measure (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:163:15)
  at Package.module.exports.Package.activate (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package-manager.js:435:21)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:292:29
  at exit (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:41:16)
  at triggerExitCallback (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
From previous event:
  at OmniSharpAtom.loadFeatures (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:127:14)
  at OmniSharpAtom.activate (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:78:18)
  at Package.module.exports.Package.activateNow (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:238:19)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:219:30
  at Package.module.exports.Package.measure (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:163:15)
  at Package.module.exports.Package.activate (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package-manager.js:435:21)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:292:29
  at exit (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:41:16)
  at triggerExitCallback (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
From previous event:
  at OmniSharpAtom.loadFeatures (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:128:14)
  at OmniSharpAtom.activate (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:78:18)
  at Package.module.exports.Package.activateNow (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:238:19)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:219:30
  at Package.module.exports.Package.measure (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:163:15)
  at Package.module.exports.Package.activate (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package-manager.js:435:21)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:292:29
  at exit (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:41:16)
  at triggerExitCallback (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
From previous event:
  at OmniSharpAtom.loadFeatures (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:130:14)
  at OmniSharpAtom.activate (C:\Users\camypaper\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:78:18)
  at Package.module.exports.Package.activateNow (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:238:19)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:219:30
  at Package.module.exports.Package.measure (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:163:15)
  at Package.module.exports.Package.activate (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\package-manager.js:435:21)
  at C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:292:29
  at exit (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:41:16)
  at triggerExitCallback (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\camypaper\AppData\Local\atom\app-0.204.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
```

### Commands

```
     -1:38 tree-view:toggle (div.settings-view.pane-item)
     -1:35.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:30.7.0 application:new-file (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:23.2.0 editor:newline (atom-text-editor.editor.is-focused)
  9x -0:58.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:21.8.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:14.8.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.1
file-icons, v1.5.6
japanese-wrap, v0.2.10
linter, v0.12.6
omnisharp-atom, v0.10.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
If you're deving locally make sure to re-run gulp from the command line, this last release had a bunch of changes in it.

**Comment by Camypaper** [comment]
@david-driscoll I see. It seemed to be due to the update from ATOM, not command line. After the restart, I have not encounter this problem.
Thanks.

**Comment by weima-sage** [comment]
I had the same issue. It occurred when I performed an auto-update within atom.
