### ISSUE TITLE
Uncaught TypeError: Cannot read property 'concat' of null

### ISSUE THREAD

**Issue by michaelblyons** [OmniSharp/omnisharp-atom#362]
[Enter steps to reproduce below:]

1. Try to update O# to 0.10.0 from 0.6.2 or so.
2. Get an error that points me to #208 
3. See that a suggested workaround is to remove & reinstall package
4. Reinstall gave this error

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.10.0

### Stack Trace

Uncaught TypeError: Cannot read property 'concat' of null

```
At ~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

TypeError: Cannot read property 'concat' of null
  at AnonymousObserver._onNext (~/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:134:44)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1778:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at AnonymousObserver.tryCatcher (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at InnerObserver.onNext (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4810:14)
  at InnerObserver.tryCatcher (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at InnerObserver.onCompleted (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2393:16)
  at InnerObserver.tryCatcher (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at InnerObserver.onCompleted (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4816:59)
  at InnerObserver.tryCatcher (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at InnerObserver.onCompleted (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5157:59)
  at InnerObserver.tryCatcher (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at InnerObserver.onCompleted (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:3639:58)
  at InnerObserver.tryCatcher (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at InnerObserver.onCompleted (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4816:59)
  at InnerObserver.tryCatcher (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at AsyncSubject.Rx.AsyncSubject.addProperties.onCompleted (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5485:17)
  at AsyncSubject.tryCatcher (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at AutoDetachObserver.tryCatcher (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at handler (~/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.async.js:373:20)
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -1:06.2.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "geojson-preview",
      "autocomplete-plus-async"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.1
file-icons, v1.5.6
highlight-selected, v0.9.3
language-aspx, v0.4.0
language-batch, v0.3.3
language-csharp, v0.5.0
linter, v0.12.6
minimap, v4.9.2
omnisharp-atom, v0.10.0

# Dev
No dev packages
```

**Comment by michaelblyons** [comment]
Error occurs after every O# package update.

**Comment by chrisdrogaris** [comment]
Same issue, please help :(

**Comment by OctoD** [comment]
Same here. Tried to uninstall and reinstall the package, the monolib and every dep on it but it is still not working :(

**Comment by Andorbal** [comment]
I'm getting this, too, with 19.2.  I'm going to see if I can figure out what's going on.

**Comment by david-driscoll** [comment]
Should be fixed with #431

**Comment by timothy-r-koski** [comment]
I got this error today using Atom 1.0.

**Comment by willl** [comment]
@timothy-r-koski Any other details you can tell us? Which version of omnisharp-atom were you running? And what were you doing when you got the error?

**Comment by timothy-r-koski** [comment]
I honestly can't remember what version I updated from. I attempted to update to Omnisharp .20 and Atom updated to 1.02 at the same time. I was only attempting to update Atom and omnisharp-atom. Unfortunately I'm not at the computer with Atom at the moment but I can provide and more details you might like this evening.

**Comment by jchannon** [comment]
I updated from 0.17.x to 0.22.6 today and I got this error

**Comment by michaelblyons** [comment]
I updated today from 0.20.0 to 0.22.6 today and did not get the error. Atom 1.0.2

**Comment by daniel-gustafsson** [comment]
Got this error today. Updated from (pretty sure it was) 0.17.1 to 0.23.1 in Atom 1.0.5.

**Comment by david-driscoll** [comment]
Any version prior to the one that had the changes (I believe it was 0.20.0)
is expected to still break.  If upgrading from 0.23.1 to the next version
breaks, I'd love to know though!

On Mon, Aug 10, 2015 at 6:03 AM, Daniel Gustafsson <notifications@github.com
