### ISSUE TITLE
Error when trying to filter refactorings

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#372]
/Users/jason/.atom/packages/omnisharp-atom/node_modules/fuzzaldrin/lib/scorer.js:60
Hide Stack Trace
TypeError: undefined is not a function
  at Object.exports.score (/Users/jason/.atom/packages/omnisharp-atom/node_modules/fuzzaldrin/lib/scorer.js:60:31)
  at module.exports (/Users/jason/.atom/packages/omnisharp-atom/node_modules/fuzzaldrin/lib/filter.js:25:24)
  at module.exports.filter (/Users/jason/.atom/packages/omnisharp-atom/node_modules/fuzzaldrin/lib/fuzzaldrin.js:21:14)
  at CodeActionsView.module.exports.SelectListView.populateList (/Users/jason/.atom/packages/omnisharp-atom/node_modules/atom-space-pen-views/lib/select-list-view.js:195:25)
  at /Users/jason/.atom/packages/omnisharp-atom/node_modules/atom-space-pen-views/lib/select-list-view.js:350:26

**Comment by david-driscoll** [comment]
what are you breaking now?
