### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#376]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.12.0

### Stack Trace

Uncaught TypeError: Cannot read property 'top' of undefined

```
At /Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/solution-status-view.js:67

TypeError: Cannot read property 'top' of undefined
  at SolutionStatusCard.verifyPosition (/Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/solution-status-view.js:67:24)
  at /Users/jason/.atom/packages/omnisharp-atom/node_modules/lodash/index.js:1777:43

```

### Commands

```
     -6:31.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 18x -6:30.2.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -6:29.3.0 omnisharp-atom:get-code-actions (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -6:28.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:53.7.0 application:quit (atom-text-editor.editor.vim-mode.command-mode.is-focused)
 54x -5:06.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
 76x -4:59.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -4:45.4.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-gruvbox.theme-atom-dark-ui.editor-background.find-visible)
     -4:43.1.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-gruvbox.theme-atom-dark-ui.editor-background.find-visible)
     -4:37.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:37.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:24.9.0 omnisharp-atom:code-format (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -4:20.2.0 vim-mode:scroll-half-screen-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  2x -4:12.8.0 omnisharp-atom:code-format (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:53.6.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-gruvbox.theme-atom-dark-ui.editor-background)
     -0:02.7.0 omnisharp-atom:restart-server (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-gruvbox.theme-atom-dark-ui.editor-background)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "autocomplete",
      "web-browser",
      "atom-browser-webview"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-dark-ui",
      "gruvbox"
    ]
  },
  "omnisharp-atom": {
    "developerMode": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-fuzzy-grep, v0.2.0
atom-typescript, v4.5.7
atom-yeoman, v0.3.2
editor-background, v0.15.6
editorconfig, v1.0.0
gruvbox, v0.3.2
language-csharp, v0.5.0
language-cshtml, v0.1.1
linter, v0.12.6
omnisharp-atom, v0.12.0
sync-settings, v0.2.2
vim-mode, v0.51.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
doing anything special at the time this happened?

**Comment by nosami** [comment]
Opened NRefactory.sln. Had to remove one of the slns to make it load.

**Comment by nosami** [comment]
There was another error too... but the stack trace was too big to post to github.

**Comment by willl** [comment]
I was getting the same error on both Windows and OS X. It happened when you stop/restart the server from the solution info card.

However, after updating to 0.12.4, it only seems to happen on Windows.

**Comment by david-driscoll** [comment]
I haven't seen this recently and looking at the code there is a null check in place now.
