### ISSUE TITLE
Uncaught TypeError: Cannot read property 'connect' of undefined

### ISSUE THREAD

**Issue by nicetrysean** [OmniSharp/omnisharp-atom#384]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.208.0
**System**: Mac OS X 10.11
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.12.5

### Stack Trace

Uncaught TypeError: Cannot read property 'connect' of undefined

```
At /Users/sean/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/solution-information.js:35

TypeError: Cannot read property 'connect' of undefined
  at atom-workspace.<anonymous> (/Users/sean/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/solution-information.js:35:55)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/sean/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Users/sean/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/sean/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at buttons.push.React.DOM.button.onClick (/Users/sean/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/solution-status-view.js:86:61)
  at Object.executeDispatch (/Users/sean/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginUtils.js:110:21)
  at SimpleEventPlugin.executeDispatch (/Users/sean/.atom/packages/omnisharp-atom/node_modules/react/lib/SimpleEventPlugin.js:305:40)
  at forEachEventDispatch (/Users/sean/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginUtils.js:98:5)
  at Object.executeDispatchesInOrder (/Users/sean/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginUtils.js:119:3)
  at executeDispatchesAndRelease (/Users/sean/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginHub.js:46:22)
  at Array.forEach (native)
  at forEachAccumulated (/Users/sean/.atom/packages/omnisharp-atom/node_modules/react/lib/forEachAccumulated.js:23:9)
  at Object.EventPluginHub.processEventQueue (/Users/sean/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginHub.js:253:5)
  at runEventQueueInBatch (/Users/sean/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
  at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Users/sean/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactEventEmitterMixin.js:44:5)
  at handleTopLevelImpl (/Users/sean/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactEventListener.js:80:24)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/sean/.atom/packages/omnisharp-atom/node_modules/react/lib/Transaction.js:134:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/sean/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
  at Object.batchedUpdates (/Users/sean/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactUpdates.js:110:20)
  at ReactEventListener.dispatchEvent (/Users/sean/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactEventListener.js:174:20)

```

### Commands

```
     -0:44.8.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  3x -0:33.7.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:06.0 omnisharp-atom:restart-server (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:01.3.0 omnisharp-atom:start-server (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "symbol-gen",
      "linter-coffeelint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-eco, v0.2.0
atom-yeoman, v0.3.1
language-ect, v0.2.0
linter, v0.12.6
omnisharp-atom, v0.12.5

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
@nicetrysean If you give the latest version a shot, and let us know if you're still having this problem.  this could be related #433

**Comment by nomatics** [comment]
Having this issue with latest version of Atom and Omnisharp-Atom. Cannot get server running.

**Comment by dkniffin** [comment]
I'm having this issue now as well.

**Comment by arberpolis** [comment]
I have the same issue with Atom 1.8.0 and omnisharp-atom 0.30.4 in windows 10 x64

**Comment by pcewing** [comment]
I'm seeing this issue as well, versions are:

OS: Windows 10 (x64)
Atom: 1.9.0
Electron: 0.37.8
Chrome: 49.0.2623.75
Node: 5.10.0
Omnisharp: 0.30.4
dotnet: 1.0.0-preview2-003121 (.NET core)

If I can provide any useful information just let me know.

**Comment by filipw** [comment]
@david-driscoll this issue is back with 1.9.0. My atom updated itself from 1.8.0 to 1.9.0 today and now any solution with multiple projects crashes omnisharp at startup. Try upgrading Atom to 1.9.0 and open i.e. `omnisharp-roslyn` sln, and you will see the problem.

When I rolled Atom back to 1.8.0 things are fine again.

**Comment by sethmurphy18** [comment]
+1 for you @filipw, turns out something about OmniSharp-atom is not compatible with Atom 1.9.0+. I think this issue should be reopened and looked into. Downgrading manually to 1.8.0 does make it work.

**Comment by CyanBlob** [comment]
I can confirm that I was having this issue with Atom 1.9.9, and that downgrading to 1.8.0 resolved the issue

**Comment by david-driscoll** [comment]
I think the issue is related to the deprecated async repository work they were doing.  I've gone back to the sync version.

I've also fixed a few issues with loading that appears to cause issues.

**Comment by zebus3d** [comment]
I have the same problem with Atom 1.11.2 in osx 10.10.3  :(

**Comment by AkihiroImada** [comment]
I have also the same problem with Atom-beta 1.12.0 beta3 in osx 10.12

**Comment by sdumasy** [comment]
Same problem on osx 10.12, atom 1.11.2

**Comment by renegadevi** [comment]
I can't get it to start the server either. 
OSX 10.11.6; Atom 1.11.2.

**Comment by selemming** [comment]
Same issue here: OSX 10.12, Atom 1.12.5

**Comment by tezine** [comment]
I have the same problem with atom 1.12.6 under Windows 10 64bits. 
It seems Omnisharp is never activated. I tried several asp.net core projects, but none worked.

**Comment by Incand** [comment]
Same issue under Linux Mint 18, based on Ubuntu 16.04.
Even downgrading to Atom 1.8.0 didn't work for me. Compiling OmniSharp also leads to errors, which seem to relate to this issue.

**Comment by dabbeg** [comment]
Same issue here: Windows 10, atom 1.12.7

**Comment by jlmakes** [comment]
Why was this closed before a fix was confirmed? 🤔

Encountering the same issue on OSX 10.11 and Atom 1.13.0. I can also confirm that downgrading to Atom 1.8 didn't work, and in fact caused a lot of other problems.

**Comment by Armour** [comment]
Same Issue here, MacOS Sieera, Atom 1.13.0, really hope we can fix this, cause I don't want to code with monodevelop, (I tried vscode too, but still not a perfect solution for me to write C# with Unity3d)

**Comment by Shurelia** [comment]
Same issue. Atom 1.13.1, Windows 10 x64. Trying to work on a unity project.
```
TypeError: Cannot read property 'connect' of undefined
    at atom-workspace.<anonymous> (C:\Users\Shurelia\.atom\packages\omnisharp-atom\dist\atom\solution-information.js:63:86)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Shurelia\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\Shurelia\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Shurelia\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Shurelia\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\Shurelia\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Shurelia\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\Shurelia\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Shurelia\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Shurelia\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Shurelia\AppData\Local\atom\app-1.13.1\resources\app.asar\src\window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (C:\Users\Shurelia\AppData\Local\atom\app-1.13.1\resources\app.asar\src\window-event-handler.js:3:59)
```

**Comment by ruwidoresearch** [comment]
Same Problem here
windows 10 x64 
Atom 1.13.1
Same result with unity or c# projects

`Uncaught TypeError: Cannot read property 'connect' of undefined`

**Comment by Takaya213** [comment]
Also getting this error.
Atom 1.22.1 x64, MacOS 10.12.6

```
TypeError: Cannot read property 'connect' of undefined
    at HTMLElement.<anonymous> (/Users/nicolelambon/.atom/packages/omnisharp-atom/dist/atom/solution-information.js:59:86)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:144:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

**Comment by quasiblob** [comment]
I still get this error, is this not solved?

-----------
Atom v1.23.3
Windows 10 x64 Pro

I cant' get  the Omnisharp icon turn green.
When I try Ctrl+shift+p, and select "Omnisharp Atom:  Start Server" ...I get the error message.

Trying to get this working for Unity / C# use...

I have .net  4.5.1 and 4.6.1 installed... but I'm not sure which of those is needed... if at all - there are three different kinds installed.

**Comment by Conando025** [comment]
Same error. And I thought I'd found a good IDE extension for working with Unity:

**Comment by xihnik** [comment]
How fix this problem?
