### ISSUE TITLE
error update

### ISSUE THREAD

**Issue by DkoSoftware** [OmniSharp/omnisharp-atom#390]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.15.0

### Stack Trace

Uncaught TypeError: Cannot read property 'concat' of null

```
At C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:579

TypeError: Cannot read property 'concat' of null
  at AnonymousObserver._onNext (C:\Users\riguelf\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:139:44)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1778:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1710:35)
  at AnonymousObserver.tryCatcher (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.next (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1710:35)
  at InnerObserver.onNext (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:4810:14)
  at InnerObserver.tryCatcher (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.next (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1710:35)
  at InnerObserver.onCompleted (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:2393:16)
  at InnerObserver.tryCatcher (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.completed (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1730:14)
  at InnerObserver.onCompleted (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:4816:59)
  at InnerObserver.tryCatcher (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.completed (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1730:14)
  at InnerObserver.onCompleted (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5157:59)
  at InnerObserver.tryCatcher (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.completed (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1730:14)
  at InnerObserver.onCompleted (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:3639:58)
  at InnerObserver.tryCatcher (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.completed (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1730:14)
  at InnerObserver.onCompleted (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:4816:59)
  at InnerObserver.tryCatcher (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.completed (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1730:14)
  at AsyncSubject.Rx.AsyncSubject.addProperties.onCompleted (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5485:17)
  at AsyncSubject.tryCatcher (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.completed (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1730:14)
  at AutoDetachObserver.tryCatcher (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.completed (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1730:14)
  at handler (C:\Users\riguelf\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.async.js:373:20)
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  },
  "omnisharp-atom": {
    "developerMode": true,
    "showDiagnosticsForAllSolutions": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
angularjs-styleguide-snippets, v0.7.0
atom-yeoman, v0.3.6
build, v0.38.0
emmet, v2.3.10
flex-tool-bar, v0.4.2
grunt-runner, v0.10.0
highlight-line, v0.11.0
linter, v0.12.7
omnisharp-atom, v0.15.0
seti-ui, v0.7.1
Sublime-Style-Column-Selection, v1.3.0
tool-bar, v0.1.7
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Hopefully will be fixed by #431
