### ISSUE TITLE
Uncaught TypeError: Cannot read property 'uniqueId' of undefined

### ISSUE THREAD

**Issue by chrisdrogaris** [OmniSharp/omnisharp-atom#394]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.15.1

### Stack Trace

Uncaught TypeError: Cannot read property 'uniqueId' of undefined

```
At /Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

TypeError: Cannot read property 'uniqueId' of undefined
  at SolutionStatusCard.componentWillUpdate (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/solution-status-view.js:39:58)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactCompositeComponent.js:717:12)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactCompositeComponent.js:642:12)
  at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactCompositeComponent.js:539:12)
  at Object.ReactReconciler.performUpdateIfNecessary (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactReconciler.js:115:22)
  at runBatchedUpdates (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactUpdates.js:151:21)
  at ReactReconcileTransaction.Mixin.perform (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/Transaction.js:134:20)
  at ReactUpdatesFlushTransaction.Mixin.perform (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/Transaction.js:134:20)
  at ReactUpdatesFlushTransaction.assign.perform (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactUpdates.js:95:38)
  at Object.flushBatchedUpdates (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactUpdates.js:175:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/Transaction.js:207:25)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/Transaction.js:148:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
  at Object.enqueueUpdate (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactUpdates.js:215:22)
  at enqueueUpdate (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactUpdateQueue.js:30:18)
  at Object.ReactUpdateQueue.enqueueSetState (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactUpdateQueue.js:208:5)
  at SolutionStatusCard.ReactComponent.setState (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactComponent.js:69:20)
  at SolutionStatusCard.updateCard (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/solution-status-view.js:60:14)
  at SolutionInformation.updateSelectedItem (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/solution-information.js:50:23)
  at AnonymousObserver._onNext (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/solution-information.js:63:19)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1778:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at AnonymousObserver.tryCatcher (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at Subject.Rx.Subject.addProperties.onNext (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5394:19)
  at Subject.tryCatcher (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at AutoDetachObserver.tryCatcher (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at InnerObserver.onNext (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4810:14)
  at InnerObserver.tryCatcher (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at observerFn (/Users/chrisdrogaris/.atom/packages/omnisharp-atom/lib/omnisharp-atom/configure-rx.js:32:26)

```

### Commands

```
  3x -0:57.4.0 core:undo (atom-text-editor.editor.is-focused)
     -0:56.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:16.4.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:08.4.0 omnisharp-atom:toggle-errors (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:01.8.0 omnisharp-atom:restart-server (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {},
  "omnisharp-atom": {
    "useLeftLabelColumnForSuggestions": true,
    "developerMode": true,
    "showDiagnosticsForAllSolutions": true,
    "useAdvancedFileNew": true
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.1.4
atom-yeoman, v0.3.11
autocomplete-ctags, v0.1.1
language-csharp, v0.6.0
linter, v0.12.7
omnisharp-atom, v0.15.1

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Is this still happening?
