### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by GeertVL** [OmniSharp/omnisharp-atom#396]
When installing the latest version of omnisharp-atom (apm install ...) and open Atom I get:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.15.1

### Stack Trace

Failed to load the omnisharp-atom package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (C:\Users\2483\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client.js:4:21)
    at C:\Users\2483\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client.js:19:5
    at Object.<anonymous> (C:\Users\2483\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client.js:128:3)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\2483\AppData\Local\atom\app-0.211.0\resources\app.asar\src\babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\2483\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client-manager.js:4:16)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
autocomplete-haskell, v0.4.4
color-picker, v2.0.7
haskell-ghc-mod, v0.7.8
ide-haskell, v0.5.13
linter-cpplint, v0.1.4
omnisharp-atom, v0.15.1

# Dev
No dev packages
```

**Comment by davidtme** [comment]
I have the same issue with a new install of atom and omnisharp-atom

**Comment by GeertVL** [comment]
This is
