### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by macshaggy** [OmniSharp/omnisharp-atom#404]
[Enter steps to reproduce below:]

1. Right clicked on ReadMe.md file 
2. Selected Markdown Preview
3. Exception popped up.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.17.0

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /Users/macshaggy/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:32

TypeError: Cannot read property 'name' of undefined
  at /Users/macshaggy/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:32:52
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:298:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "github-issues",
      "autocomplete-clang",
      "language-rust",
      "racer",
      "linter-rust"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "projectHome": "/Users/macshaggy/workspace"
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.11
git-control, v0.3.0
git-tab-status, v1.9.2
linter, v1.0.9
linter-clang, v2.26.0
linter-jshint, v0.1.7
linter-tidy, v1.0.1
minimap, v4.10.0
omnisharp-atom, v0.17.0
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by Meligy** [comment]
Just got this myself

[Enter steps to reproduce below:]

1. Updated packages, which only updated markdown-writer at the time
2. Switched to a plain text non-saved tab

I don't know if either of these have a relation, but quite often when I switch to plain text or Markdown tab on app open or after some idle time I get some Omnisharp exception (not sure if the same as now, most likely yes).

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.24.0


### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /Users/Meligy/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

TypeError: Cannot read property 'name' of undefined
  at AnonymousObserver._onNext (/Users/Meligy/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:138:71)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/Meligy/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1778:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Meligy/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at AnonymousObserver.tryCatcher (/Users/Meligy/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/Meligy/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Meligy/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at /Users/Meligy/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.time.js:276:54
  at invokeAction (/Users/Meligy/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:948:7)
  at /Users/Meligy/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1432:60

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "base16-syntax"
    ],
    "disabledPackages": [
      "markdown-preview-plus",
      "markdown-preview-plus-opener"
    ]
  },
  "omnisharp-atom": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v5.5.0
atom-yeoman, v0.3.12
autoclose-html, v0.18.0
base16-syntax, v1.5.0
build-markdown, v1.0.2
file-icons, v1.6.7
json-schema, v0.1.11
language-api-blueprint, v1.0.2
linter, v1.4.3
linter-eslint, v3.0.2
markdown-deluxe, v1.0.0
markdown-scroll-sync, v0.4.0
omnisharp-atom, v0.24.0
save-session, v0.15.7
seti-icons, v0.4.2
sync-settings, v0.6.0
typewriter, v0.3.4

# Dev
No dev packages
```

**Comment by Meligy** [comment]
Just happaned again after updating markdown-preview-plus, with no C# files opened at alll, just some plain text (syntax: auto) and Markdown files opened (all unsaved)
