### ISSUE TITLE
Uncaught TypeError: Cannot read property 'abort' of undefined

### ISSUE THREAD

**Issue by sagasu** [OmniSharp/omnisharp-atom#420]
[Enter steps to reproduce below:]

1. Install OmniSharp as a package, with dependencies
2. Open C# project

**Atom Version**: 1.0.2
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.17.3

### Stack Trace

Uncaught TypeError: Cannot read property 'abort' of undefined

```
At C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:579

TypeError: Cannot read property 'abort' of undefined
  at Client.request (C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\lib\omni-sharp-server\client.js:93:20)
  at ClientV1.projects (C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\clients\client-v1.js:275:21)
  at AnonymousObserver._onNext (C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\lib\omni-sharp-server\view-model.js:71:21)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1778:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1710:35)
  at AnonymousObserver.tryCatcher (C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
  at AutoDetachObserverPrototype.next (C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1710:35)
  at InnerObserver.onNext (C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5151:29)
  at Subject.Rx.Subject.addProperties.onNext (C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5394:19)
  at StdioDriver.handlePacketEvent (C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:205:36)
  at StdioDriver.handlePacket (C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:179:18)
  at StdioDriver.handleData (C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:171:18)
  at Interface.<anonymous> (C:\Users\mateusz.kopij\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:115:54)
  at emitOne (events.js:77:13)
  at Interface.emit (events.js:166:7)
  at Interface._onLine (readline.js:195:10)
  at Interface.<anonymous> (readline.js:325:12)
  at Array.forEach (native)
  at Interface._normalWrite (readline.js:324:11)
  at Socket.ondata (readline.js:71:10)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
     -8:43.2.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:45.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.11.0
omnisharp-atom, v0.17.3

# Dev
No dev packages
```

**Comment by Yantrio** [comment]
i'm also getting this, also, https://www.youtube.com/watch?v=shCYA2J-De8

**Comment by ncthbrt** [comment]
I'm receiving the same error, same steps to reproduce.
Error report:

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.17.3


### Stack Trace

Uncaught TypeError: Cannot read property 'abort' of undefined

```
At /home/nick/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

TypeError: Cannot read property 'abort' of undefined
    at Client.request (/home/nick/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client.js:93:20)
    at ClientV1.projects (/home/nick/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/clients/client-v1.js:275:21)
    at AnonymousObserver._onNext (/home/nick/.atom/packages/omnisharp-atom/lib/omni-sharp-server/view-model.js:71:21)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/home/nick/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1778:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/nick/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at AnonymousObserver.tryCatcher (/home/nick/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/home/nick/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/nick/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at InnerObserver.onNext (/home/nick/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5151:29)
    at Subject.Rx.Subject.addProperties.onNext (/home/nick/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5394:19)
    at StdioDriver.handlePacketEvent (/home/nick/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:205:36)
    at StdioDriver.handlePacket (/home/nick/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:179:18)
    at StdioDriver.handleData (/home/nick/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:171:18)
    at Interface.<anonymous> (/home/nick/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:115:54)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:166:7)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.11
css-color-underline, v1.0.1
linter, v1.2.3
omnisharp-atom, v0.17.3

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
This should be fixed with the latest release, let us know if its still a problem.
