### ISSUE TITLE
Uncaught TypeError: Cannot read property 'rootElement' of undefined

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-atom#423]
[Enter steps to reproduce below:]

1. ... Open settings tab
2. ... Switch to c# tab
3. ... Restart atom so that the settings tab appears on startup
4. ... Switch to settings tab

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.18.1

### Stack Trace

Uncaught TypeError: Cannot read property 'rootElement' of undefined

```
At /Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

TypeError: Cannot read property 'rootElement' of undefined
  at Tooltip.getFromShadowDom (/Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/lookup.js:178:23)
  at new Tooltip (/Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/lookup.js:51:27)
  at AnonymousObserver._onNext (/Users/jason/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/lookup.js:24:53)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1778:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at AnonymousObserver.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at AutoDetachObserver.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at /Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1855:51
  at /Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1884:13
  at scheduleInnerRecursive (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1085:7)
  at recursiveAction (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1039:9)
  at [object Object].invokeRecImmediate [as action] (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1056:7)
  at [object Object].ScheduledItem.invokeCore (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:929:17)
  at [object Object].ScheduledItem.invoke (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:917:40)
  at runTrampoline (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1237:37)
  at tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at Scheduler.scheduleNow [as _schedule] (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1248:45)
  at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:970:19)
  at Scheduler.schedulerProto.scheduleRecursiveWithState (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1104:19)
  at Scheduler.schedulerProto.scheduleRecursive (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1094:19)
  at ScheduledObserver.Rx.internals.ScheduledObserver.ScheduledObserver.ensureActive (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1875:54)
  at ReplaySubject.Rx.ReplaySubject.addProperties.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.binding.js:410:20)
  at ReplaySubject.tryCatcher (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at BehaviorSubject.Rx.BehaviorSubject.addProperties.onNext (/Users/jason/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.binding.js:306:17)
  at /Users/jason/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:54:40
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:238:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:302:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:210:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "autocomplete",
      "web-browser",
      "atom-browser-webview"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "visual-studio-code",
      "one-dark-syntax"
    ]
  },
  "omnisharp-atom": {
    "developerMode": true,
    "autoAdjustTreeView": true,
    "autoAddExternalProjects": true,
    "useAdvancedFileNew": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v4.6.10
atom-yeoman, v0.3.11
auto-indent, v0.5.0
editor-background, v1.0.1
editorconfig, v1.0.1
language-csharp, v0.6.0
language-cshtml, v0.1.1
linter, v1.1.0
minimap, v4.10.0
omnisharp-atom, v0.18.1
tool-bar, v0.1.8
tool-bar-main, v0.0.8
tree-view-open-files, v0.2.4
vim-mode, v0.54.0
visual-studio-code, v0.4.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
This should be fixed, I had seen something related and fixed it.  If you see it agian let me know.
