### ISSUE TITLE
Cannot read property 'paths' of undefined

### ISSUE THREAD

**Issue by Mpdreamz** [OmniSharp/omnisharp-atom#426]
TypeError: Cannot read property 'paths' of undefined

```
    at SolutionManager.findSolutionForUnderlyingPath (/Users/mpdreamz/Projects/omnisharp-atom/lib/omni-sharp-server/client-manager.js:280:66)
    at SolutionManager.getClientForEditor (/Users/mpdreamz/Projects/omnisharp-atom/lib/omni-sharp-server/client-manager.js:230:21)
    at Omni.request (/Users/mpdreamz/Projects/omnisharp-atom/lib/omni-sharp-server/omni.js:197:30)
    at Object.exports.provider.lint (/Users/mpdreamz/Projects/omnisharp-atom/lib/omnisharp-atom/features/lib/linter-provider.js:82:25)
    at /Users/mpdreamz/.atom/packages/linter/lib/editor-linter.coffee:110:37
    at currentLinter (/Users/mpdreamz/.atom/packages/linter/lib/editor-linter.coffee:109:20)
    at /Users/mpdreamz/.atom/packages/linter/lib/editor-linter.coffee:132:34
    at Set.forEach (native)
    at EditorLinter.triggerLinters (/Users/mpdreamz/.atom/packages/linter/lib/editor-linter.coffee:99:32)
    at /Users/mpdreamz/.atom/packages/linter/lib/editor-linter.coffee:87:36
```

As soon as I open `omnisharp-roslyn`

**Comment by Mpdreamz** [comment]
Fixed in https://github.com/OmniSharp/omnisharp-atom/pull/428
