### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Projects' of undefined

### ISSUE THREAD

**Issue by Andorbal** [OmniSharp/omnisharp-atom#430]
[Enter steps to reproduce below:]

1. I created a new folder from the terminal
2. I added an empty global.json in the folder (Contents were simply {})
3. I opened the folder in Atom.io
4. I added two new class library projects to the folder through Omnisharp's New Application menu
5. I toggled Omnisharp through the menu (because the flame wasn't visible), and the error popped up

**Atom Version**: 1.0.2
**System**: Linux Mint
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.19.2

### Stack Trace

Uncaught TypeError: Cannot read property 'Projects' of undefined

```
At /home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

TypeError: Cannot read property 'Projects' of undefined
    at AnonymousObserver._onNext (/home/andrew/.atom/packages/omnisharp-atom/lib/omni-sharp-server/view-model.js:139:42)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1778:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at AnonymousObserver.tryCatcher (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at InnerObserver.onNext (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4810:14)
    at InnerObserver.tryCatcher (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at InnerObserver.onNext (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5151:29)
    at InnerObserver.tryCatcher (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at Subject.Rx.Subject.addProperties.onNext (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5394:19)
    at Subject.tryCatcher (/home/andrew/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
```

### Commands

```
     -1:05.9.0 omnisharp-atom:new-application (atom-pane.pane.active)
     -1:00.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:42.9.0 omnisharp-atom:new-application (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:38.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:37.1.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:35.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:24.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:19 core:save (atom-text-editor.editor.is-focused)
     -0:04.0 omnisharp-atom:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {},
  "omnisharp-atom": {
    "developerMode": true
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.11
linter, v1.2.3
omnisharp-atom, v0.19.2

# Dev
No dev packages
```

**Comment by nosami** [comment]
Did the server start up correctly? Any useful information in the server output window?

**Comment by Andorbal** [comment]
There wasn't a server output window, unfortunately.  Restarting Atom solved the problem, and I'll see if I can replicate the issue in a few hours.

**Comment by nosami** [comment]
ok.. thanks

**Comment by david-driscoll** [comment]
@Andorbal any idea how to replicate?  I've seen it a few times, but never in a situation that lets me recreate it.

It almost seems like it's a race condition with the status bar, where the status bar somehow gets restarted (and it eliminates anything that might have been put in it by then).

**Comment by david-driscoll** [comment]
@Andorbal If this happens again, let us know and we can reopen this issue!
