### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, open '/Users/jorgemendez/Desktop/Person.cs/.gitignore'

### ISSUE THREAD

**Issue by jolu14** [OmniSharp/omnisharp-atom#440]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.20.0

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, open '/Users/jorgemendez/Desktop/Person.cs/.gitignore'

```
At fs.js:519

Error: ENOTDIR: not a directory, open '/Users/jorgemendez/Desktop/Person.cs/.gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.writeFileSync (fs.js:1155:15)
    at write (/Users/jorgemendez/.atom/packages/omnisharp-atom/node_modules/generator-aspnet/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/commit.js:15:6)
    at DestroyableTransform._transform (/Users/jorgemendez/.atom/packages/omnisharp-atom/node_modules/generator-aspnet/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/commit.js:42:7)
    at DestroyableTransform.Transform._read (/Users/jorgemendez/.atom/packages/atom-yeoman/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/jorgemendez/.atom/packages/atom-yeoman/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/jorgemendez/.atom/packages/atom-yeoman/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/jorgemendez/.atom/packages/atom-yeoman/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/jorgemendez/.atom/packages/atom-yeoman/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/jorgemendez/.atom/packages/atom-yeoman/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/jorgemendez/.atom/packages/atom-yeoman/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/jorgemendez/.atom/packages/atom-yeoman/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:163:7)
    at emitReadable_ (/Users/jorgemendez/.atom/packages/atom-yeoman/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/jorgemendez/.atom/packages/atom-yeoman/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/jorgemendez/.atom/packages/atom-yeoman/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/jorgemendez/.atom/packages/atom-yeoman/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/jorgemendez/.atom/packages/atom-yeoman/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at Object.callback (/Users/jorgemendez/.atom/packages/omnisharp-atom/node_modules/generator-aspnet/node_modules/yeoman-generator/lib/base.js:784:16)
```

### Commands

```
     -0:19 omnisharp-atom:new-application (atom-text-editor.editor.is-focused)
     -0:06.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "omnisharp-atom": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.11
linter, v1.2.3
omnisharp-atom, v0.20.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
I put in a fix into atom-yeoman that fixed this issue (it was previously letting you select the `.gitignore` file as a directory).

 Let me know if you still have a problem.
