### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by ncthbrt** [OmniSharp/omnisharp-atom#443]
1. Open a C# project
2. Click the "All" button in the bottom right corner of the atom window.

**Atom Version**: 1.0.2
**System**: Ubuntu 15.04
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.20.0

### Stack Trace

Uncaught ReferenceError: $ is not defined

```
At /home/nick/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/framework-selector-view.js:76

ReferenceError: $ is not defined
    at FrameworkSelectorSelectListView.show (/home/nick/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/framework-selector-view.js:76:24)
    at React.DOM.a.onClick (/home/nick/.atom/packages/omnisharp-atom/lib/omnisharp-atom/views/framework-selector-view.js:39:22)
    at Object.executeDispatch (/home/nick/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginUtils.js:110:21)
    at SimpleEventPlugin.executeDispatch (/home/nick/.atom/packages/omnisharp-atom/node_modules/react/lib/SimpleEventPlugin.js:305:40)
    at forEachEventDispatch (/home/nick/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginUtils.js:98:5)
    at Object.executeDispatchesInOrder (/home/nick/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginUtils.js:119:3)
    at executeDispatchesAndRelease (/home/nick/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginHub.js:46:22)
    at Array.forEach (native)
    at forEachAccumulated (/home/nick/.atom/packages/omnisharp-atom/node_modules/react/lib/forEachAccumulated.js:23:9)
    at Object.EventPluginHub.processEventQueue (/home/nick/.atom/packages/omnisharp-atom/node_modules/react/lib/EventPluginHub.js:253:5)
    at runEventQueueInBatch (/home/nick/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/home/nick/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactEventEmitterMixin.js:44:5)
    at handleTopLevelImpl (/home/nick/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactEventListener.js:80:24)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/home/nick/.atom/packages/omnisharp-atom/node_modules/react/lib/Transaction.js:134:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/home/nick/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
    at Object.batchedUpdates (/home/nick/.atom/packages/omnisharp-atom/node_modules/react/lib/ReactUpdates.js:110:20)
```

### Commands

```
     -7:19.3.0 advanced-new-file:toggle (atom-text-editor.editor.is-focused)
     -7:18.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -7:18.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -7:13.5.0 omnisharp-atom:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:11.3.0 application:open-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:01.6.0 omnisharp-atom:toggle (atom-text-editor.editor.is-focused)
     -6:55.1.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  4x -6:47.3.0 omnisharp-atom:toggle-errors (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -6:42.7.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:48 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "omnisharp-atom": {}
}
```

### Installed Packages

```coffee
# User
advanced-new-file, v0.4.3
atom-yeoman, v0.3.11
css-color-underline, v1.0.1
linter, v1.2.3
omnisharp-atom, v0.20.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Landing with #438

**Comment by ncthbrt** [comment]
Thanks
