### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by dopare** [OmniSharp/omnisharp-atom#446]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.22.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At /Users/dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at StdioDriver.connect (/Users/dopare/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:108:45)
  at ClientBase.connect (/Users/dopare/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/clients/client-base.js:234:22)
  at Client.connect (/Users/dopare/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client.js:38:24)
  at SolutionManager.getClientForEditor (/Users/dopare/.atom/packages/omnisharp-atom/lib/omni-sharp-server/client-manager.js:213:31)
  at Omni.getProject (/Users/dopare/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:218:24)
  at /Users/dopare/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/highlight.js:153:49
  at /Users/dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4924:20
  at tryCatcher (/Users/dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at InnerObserver.onNext (/Users/dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4806:43)
  at InnerObserver.tryCatcher (/Users/dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at /Users/dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.time.js:276:54
  at invokeAction (/Users/dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:948:7)
  at /Users/dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1432:60

```

### Commands

```
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false
  },
  "omnisharp-atom": {
    "enhancedHighlighting": true
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.11
language-cshtml, v0.1.1
linter, v1.2.4
omnisharp-atom, v0.22.0

# Dev
No dev packages
```

**Comment by nosami** [comment]
Do you have mono 4.0.1 (or higher) installed?

**Comment by dopare** [comment]
Mono JIT compiler version 4.0.2 (Stable 4.0.2.5/c99aa0c Wed Jul  1 14:19:56 PDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by Kf4btg** [comment]
I had this problem, too, on two machines both running Linux.  Seems the 0.22.0 update removed the executable bit from a couple of files, namely the omnisharp and dnx scripts. I fixed that with:

`chmod +x ~/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/omnisharp ~/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/packages/dnx-mono.1.0.0-beta4/bin/dnx`

Making the omnisharp script executable again revealed a new "ENOENT" error, or file not found, but the atom error popup wasn't telling me _which_ file wasn't found.  So I ran the command the server omnisharp was calling in my terminal:

`.atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/omnisharp --stdio -s /dev/myProject/ --hostPID 54321` 

and got this error from the shell:
`zsh: .atom/packages/omnisharp-atom/node_modules/omnisharp-client/roslyn/omnisharp: bad interpreter: /bin/bash^M: no such file or directory`

Seems the script was confused by the Windows CRLF line-endings and couldn't find the /bin/bash executable since it considered the ^M part of the file name.  So I ran the omnisharp script through the dos2unix utility and NOW everything works.

Interestingly, my first response was just to uninstall and reinstall 0.20.0 as that version worked fine, but even after doing this the permissions were still incorrect for these files.

**Comment by david-driscoll** [comment]
Yeah we had an issue with npm not installing correctly.  If it's still
happening, let us know, and I'll try publishing a new version (which should
the client that was built by travis properly)

**Comment by Kf4btg** [comment]
Issue reoccurred with 0.22.1 update. Same process as before took care of it.

**Comment by nosami** [comment]
Should be fixed in 0.22.2

**Comment by Kf4btg** [comment]
Yep, works for me now. :tada:

**Comment by dopare** [comment]
Yea, it's fixed. Thank you guys.
