### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by ccbentlee** [OmniSharp/omnisharp-atom#451]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.22.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At /Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

TypeError: Cannot read property 'getGrammar' of undefined
    at /Users/Lee/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/highlight.js:190:61
    at tryCatcher (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at InnerObserver.onNext (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5147:49)
    at InnerObserver.tryCatcher (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at InnerObserver.onNext (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4810:14)
    at InnerObserver.tryCatcher (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at Subject.Rx.Subject.addProperties.onNext (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5394:19)
    at Subject.tryCatcher (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at AutoDetachObserver.tryCatcher (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Lee/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "solarized-dark-syntax"
    ],
    "projectHome": "/Users/Lee/Documents",
    "ignoredNames": [
      "*.git",
      "*.meta",
      ".DS_Store",
      "obj",
      "Temp",
      "Library",
      "ProjectSettings",
      "*.csproj",
      "*.unityproj",
      "*.sln",
      "*.userprefs",
      ".gitignore"
    ],
    "disabledPackages": [
      "javascript-snippets",
      "autocomplete-paths",
      "atom-yeoman",
      "advanced-new-file",
      "minimap-highlight-selected",
      "minimap-find-and-replace",
      "git-log",
      "jshint",
      "docblockr",
      "pretty-json",
      "script",
      "vim-mode"
    ]
  },
  "omnisharp-atom": {
    "autoAdjustTreeView": true,
    "autoAddExternalProjects": true,
    "enhancedHighlighting": true,
    "hideLinterInterface": false
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.5.9
file-icons, v1.5.8
highlight-selected, v0.10.1
linter, v1.2.4
minimap, v4.12.0
omnisharp-atom, v0.22.2
pigments, v0.9.0

# Dev
No dev packages
```

**Comment by nosami** [comment]
fix included in v0.22.5
