### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by Kurnosov** [OmniSharp/omnisharp-atom#463]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.6
**System**: Mac OS X 10.10.4
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.23.2

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/ykurnosov/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

TypeError: Cannot read property 'path' of undefined
    at /Users/ykurnosov/.atom/packages/omnisharp-atom/lib/omni-sharp-server/view-model.js:219:74
    at tryCatcher (/Users/ykurnosov/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at InnerObserver.onNext (/Users/ykurnosov/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5147:49)
    at Subject.Rx.Subject.addProperties.onNext (/Users/ykurnosov/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5394:19)
    at /Users/ykurnosov/.atom/packages/omnisharp-atom/lib/omni-sharp-server/view-model.js:267:43
    at Array.map (native)
    at AnonymousObserver._onNext (/Users/ykurnosov/.atom/packages/omnisharp-atom/lib/omni-sharp-server/view-model.js:263:18)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/ykurnosov/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1778:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/ykurnosov/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at AnonymousObserver.tryCatcher (/Users/ykurnosov/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/Users/ykurnosov/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/ykurnosov/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at InnerObserver.onNext (/Users/ykurnosov/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4810:14)
    at InnerObserver.tryCatcher (/Users/ykurnosov/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/Users/ykurnosov/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/ykurnosov/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at InnerObserver.onNext (/Users/ykurnosov/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5151:29)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*.meta"
    ]
  },
  "omnisharp-atom": {}
}
```

### Installed Packages

```coffee
# User
atom-perforce, v1.5.3
atom-yeoman, v0.3.12
json-schema, v0.1.11
linter, v1.3.4
minimap, v4.12.2
omnisharp-atom, v0.23.2
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by willl** [comment]
I've been able to replicate this when trying to open a folder with an .sln file (MVC5 project). ASP.NET 5 apps don't produce the issue.

**Comment by tmunro** [comment]
I get this against the Unity3D project I'm working on with `0.23.2`. I installed `0.23.1` and everything is fine again, so I'll stick with that until this is closed.

**Comment by david-driscoll** [comment]
If your project is open source I will add it to the tests suite

-----Original Message-----

**Comment by willl** [comment]
@david-driscoll I can repo it on both Windows and OS X with this small test project. https://github.com/willl/DualSolutions

**Comment by david-driscoll** [comment]
I started work on this last night, I'm going to include tests for https://github.com/willl/DualSolutions and https://github.com/stormtek/unity-rts-demo

At the beginning it will only be a few tests, but my hope is that we can add a full suite over time that will exercise all functionality against a real (at albeit small) example set of applications.

**Comment by david-driscoll** [comment]
Closing this as it should be fixed now.  I still have the outstanding PR for adding these external solutions... I'll try and get back to that sometime soon.
