### ISSUE TITLE
On startup, omnisharp.cmd cannot be found if username includes spaces

### ISSUE THREAD

**Issue by kylos101** [OmniSharp/omnisharp-atom#466]
Here is the corresponding output from the Omnisharp console in Atom

Errors & WarningsOmnisharp output
Starting OmniSharp server (pid:3760)
OmniSharp Location: C:\Users\Fname Lname\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\roslyn\omnisharp.cmd
Change the location that OmniSharp is loaded from by setting the OMNISHARP environment variable
OmniSharp Path: C:\Users\Fname LName\Documents\Github\test\WebAPIApplication
'C:\Users\Fname' is not recognized as an internal or external command,
operable program or batch file.

**Comment by david-driscoll** [comment]
looks like a client issue... wonderful, I'll try and tackle this asap.

**Comment by nosami** [comment]
This was fixed on the server here https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.3.0 so should be coming to Atom soon

**Comment by kylos101** [comment]
Thanks for the heads up, Jason!

**Comment by Andegawen** [comment]
I have the same issue as kylo101.
I'm working on Win8.1, Atom version:1.4.3, Omnisharp-atom package version:0.26.11.
I did what message says to me: "Change the location that OmniSharp is loaded from by setting the OMNISHARP environment variable"
So I made environment variable (OMNISHARP) with path in question marks - Win needs it to expand path with spaces, but I've got the belowed error:

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn "C:\Users\Fname Lname\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\clr\run.cmd" ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:129:18)
    at node.js:981:3

**Comment by david-driscoll** [comment]
Yeah I need to figure out how to get node to behave, I'll see if I can look at this shortly.

**Comment by Andegawen** [comment]
I don't know if it helps, but when I changed run.cmd with stright foreward values
for example: DNX_PATH as
"C:\Users\Fname Lname\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\clr\runtimes\dnx-clr-win-x86.1.0.0-rc2-16444\bin\dnx.exe"

I have got this ugly exception when I run this script:
> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNet.Server.Kestrel' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.AspNet.Server.Kestrel'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.Server.ServerLoader.LoadServerFactory(String assemblyName)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at OmniSharp.Program.Main(String[] args)
   at Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
