### ISSUE TITLE
Omnisharp Cannot Read Property 'add'

### ISSUE THREAD

**Issue by kingbari** [OmniSharp/omnisharp-atom#473]
Whenever I launch atom, I get the error below. Does anyone how to resolve this?

[Enter steps to reproduce below:]

1. Open atom editor (atom.exe)

**Atom Version**: 1.0.7
**System**: Microsoft Windows 10 Home
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.24.0

### Stack Trace

Uncaught TypeError: Cannot read property 'add' of undefined

```
At C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:579

TypeError: Cannot read property 'add' of undefined
    at Dock.addWindow (C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\lib\omnisharp-atom\atom\dock.js:73:24)
    at CodeCheck.activate (C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\lib\omnisharp-atom\features\code-check.js:64:41)
    at C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:133:23
    at arrayEach (C:\Users\Ari\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1289:13)
    at Function.<anonymous> (C:\Users\Ari\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:3345:13)
    at AnonymousObserver._onNext (C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:132:19)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1778:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1710:35)
    at AnonymousObserver.tryCatcher (C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
    at AutoDetachObserverPrototype.next (C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1710:35)
    at Subject.Rx.Subject.addProperties.onNext (C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5394:19)
    at Subject.tryCatcher (C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
    at AutoDetachObserverPrototype.next (C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1710:35)
    at AutoDetachObserver.tryCatcher (C:\Users\Ari\AppData\Local\atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-fsharp, v0.12.2
atom-yeoman, v0.3.12
go-plus, v3.4.5
json-schema, v0.1.11
linter, v1.4.3
linter-flake8, v1.6.1
linter-jshint, v1.1.5
omnisharp-atom, v0.24.0
SquirrelTemp, vundefined

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
@hemantsathe looks like this dockWindow.add issue has been fixed, let me know if you still have it with the latest version.
