### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by hemantsathe** [OmniSharp/omnisharp-atom#478]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.24.0

### Stack Trace

Uncaught TypeError: Cannot read property 'add' of undefined

```
At C:\Users\146556\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:579

TypeError: Cannot read property 'add' of undefined
    at Dock.addWindow (C:\Users\146556\.atom\packages\omnisharp-atom\lib\omnisharp-atom\atom\dock.js:73:24)
    at CodeCheck.activate (C:\Users\146556\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\code-check.js:64:41)
    at C:\Users\146556\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:133:23
    at arrayEach (C:\Users\146556\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1289:13)
    at Function.<anonymous> (C:\Users\146556\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:3345:13)
    at AnonymousObserver._onNext (C:\Users\146556\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:132:19)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\146556\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1778:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\146556\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1710:35)
    at AnonymousObserver.tryCatcher (C:\Users\146556\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
    at AutoDetachObserverPrototype.next (C:\Users\146556\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\146556\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1710:35)
    at Subject.Rx.Subject.addProperties.onNext (C:\Users\146556\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5394:19)
    at Subject.tryCatcher (C:\Users\146556\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
    at AutoDetachObserverPrototype.next (C:\Users\146556\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\146556\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1710:35)
    at AutoDetachObserver.tryCatcher (C:\Users\146556\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:567:29)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.12
json-schema, v0.1.11
linter, v1.4.3
omnisharp-atom, v0.24.0
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by gsscoder** [comment]
Got the same, again. On OS X Yosemite... This package (or atom itself) has really a lot of problem with Mac Book machines. (Or maybe it's something on my system, it's a dev machine full of stuff!).

Hope it stabilizes, because I love it!

**Comment by david-driscoll** [comment]
We're working on it, any help you can offer is always appreciated (and
logging issues is helping!) :)

I personally am trying to always dogfood with the editor whenever I'm
working in C#, so any hints as to what happened are always appreciated!  I
personally only have access to windows machines, so sometimes with cross
plat issues I'm in the dark on what happened.

I have seen some performance problems, as well as some problems after
running for a little while, they are some of the next items on my hit list.

**Comment by gsscoder** [comment]
@david-driscoll, you're right, I'ven't hitted the button for not adding to many data overhead; but if for you is a good thing, I'll send every crash!

Thanks again.

**Comment by jugglingnutcase** [comment]
i'm seeing this issue as well. i'll post my information in case that's helpful:

1. Open Atom
2. The bug shows up

Again, i'm not sure if this is helpful, but i have two project folders open, both containing .NET solutions. One is a .NET 4.5.2 solution, and the other is .NET 4.0 and contains a large number of different projects.

**Atom Version**: 1.0.11
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.24.5


### Stack Trace

Uncaught TypeError: Cannot read property 'add' of undefined

```
At C:\Users\Administrator\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:71

TypeError: Cannot read property 'add' of undefined
    at Dock.addWindow (C:\Users\Administrator\.atom\packages\omnisharp-atom\lib\omnisharp-atom\atom\dock.js:76:24)
    at CodeCheck.activate (C:\Users\Administrator\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\code-check.js:67:41)
    at C:\Users\Administrator\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:154:31
    at arrayEach (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1289:13)
    at Function.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:3345:13)
    at AnonymousObserver._onNext (C:\Users\Administrator\.atom\packages\omnisharp-atom\lib\omnisharp-atom\omnisharp-atom.js:134:19)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\Administrator\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1691:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Administrator\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
    at AnonymousObserver.tryCatcher (C:\Users\Administrator\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
    at AutoDetachObserverPrototype.next (C:\Users\Administrator\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Administrator\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
    at Subject.Rx.Subject.addProperties.onNext (C:\Users\Administrator\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5334:19)
    at Subject.tryCatcher (C:\Users\Administrator\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
    at AutoDetachObserverPrototype.next (C:\Users\Administrator\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Administrator\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
    at AutoDetachObserver.tryCatcher (C:\Users\Administrator\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".hg",
      "node_modules",
      ".nuget",
      ".vs",
      "TestResults",
      "*.orig"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.13
json-schema, v0.1.13
language-cshtml, v0.1.1
language-powershell, v2.1.0
language-vbdotnet, v0.1.0
linter, v1.5.0
omnisharp-atom, v0.24.5
vim-mode, v0.59.0

# Dev
No dev packages
```

**Comment by jugglingnutcase** [comment]
Oops, didn't see that there's an update for this package. i'll see if that changes things here.

**Comment by david-driscoll** [comment]
@hemantsathe looks like this dockWindow.add issue has been fixed, let me know if you still have it with the latest version.

**Comment by gsscoder** [comment]
Also this :ok_hand: ! Thanks. Excellent job!
