### ISSUE TITLE
Exception when opening a C# project

### ISSUE THREAD

**Issue by gsscoder** [OmniSharp/omnisharp-atom#481]
The following exception occurred only one time when opening this project: https://github.com/gsscoder/CSharpx.

```
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.24.0


### Stack Trace

Uncaught TypeError: Cannot read property 'add' of undefined


At /Users/giacomo/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

TypeError: Cannot read property 'add' of undefined
    at Dock.addWindow (/Users/giacomo/.atom/packages/omnisharp-atom/lib/omnisharp-atom/atom/dock.js:73:24)
    at CodeCheck.activate (/Users/giacomo/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-check.js:64:41)
    at /Users/giacomo/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:133:23
    at arrayEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3345:13)
    at AnonymousObserver._onNext (/Users/giacomo/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:132:19)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/giacomo/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1778:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/giacomo/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at AnonymousObserver.tryCatcher (/Users/giacomo/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/Users/giacomo/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/giacomo/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at Subject.Rx.Subject.addProperties.onNext (/Users/giacomo/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5394:19)
    at Subject.tryCatcher (/Users/giacomo/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/Users/giacomo/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/giacomo/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
    at AutoDetachObserver.tryCatcher (/Users/giacomo/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)


### Commands




### Config

json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}


### Installed Packages

coffee
# User
Paket, v1.0.2
atom-fsharp, v0.12.5
atom-yeoman, v0.3.12
json-schema, v0.1.11
language-fsharp, v0.8.4
language-opencl, v0.1.1
linter, v1.4.3
omnisharp-atom, v0.24.0

# Dev
No dev packages
```

To me it's not a real issue because now everything works fine, but I thought that for team could deserve a further investigation.

Regards, Giacomo.

**Comment by david-driscoll** [comment]
I'm no longer seeing that exception with the code in that project, so that's a good thing!

**Comment by gsscoder** [comment]
You're right after latest updates no more problems of this kind. Thank you :smile:!
