### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of undefined

### ISSUE THREAD

**Issue by wmeints** [OmniSharp/omnisharp-atom#499]
I'm getting this error while closing a file:

TypeError: Cannot read property 'getSelectedBufferRange' of undefined
  at CodeAction.getRequest (/Users/willem/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-action.js:94:27)
  at /Users/willem/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-action.js:51:100
  at clientCallback (/Users/willem/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:233:21)
  at tryCatcher (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at InnerObserver.onNext (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2010:45)
  at InnerObserver.tryCatcher (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at InnerObserver.onNext (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5094:29)
  at InnerObserver.tryCatcher (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at AnonymousObserver._onNext (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5022:13)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1691:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at AnonymousObserver.tryCatcher (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at InnerObserver.onNext (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5094:29)
  at InnerObserver.tryCatcher (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at DistinctUntilChangedObserver.next (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4152:16)
  at DistinctUntilChangedObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at DistinctUntilChangedObserver.tryCatcher (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at /Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1768:51
  at tryCatcher (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at /Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1796:35
  at [object Object].invokeRecImmediate [as action] (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:942:7)
  at [object Object].ScheduledItem.invokeCore (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:834:17)
  at [object Object].ScheduledItem.invoke (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:822:40)
  at runTrampoline (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1149:37)
  at tryCatcher (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at Scheduler.scheduleNow [as _schedule] (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1159:45)
  at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:875:19)
  at AnonymousObservable.innerSubscribe [as _subscribe] (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5185:32)
  at AnonymousObservable.Rx.Observable.observableProto.subscribeOnCompleted (/Users/willem/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1927:19)
  at Omni.request (/Users/willem/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:254:16)
  at makeLightbulbRequest (/Users/willem/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-action.js:51:37)
  at /Users/willem/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-action.js:67:17
  at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
  at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)

**Comment by tmunro** [comment]
I'm still seeing this on v0.24.14

1. ???
2. Open settings view

**Atom Version**: 1.0.19-5f4f6d2
**System**: Mac OS X 10.10.5
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.24.14


### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of undefined

```
At /Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:71

TypeError: Cannot read property 'getSelectedBufferRange' of undefined
  at CodeAction.getRequest (/Users/tommunro/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-action.js:97:27)
  at /Users/tommunro/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-action.js:53:108
  at clientCallback (/Users/tommunro/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:251:21)
  at tryCatcher (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at InnerObserver.onNext (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2010:45)
  at InnerObserver.tryCatcher (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at InnerObserver.onNext (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5094:29)
  at InnerObserver.tryCatcher (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at scheduleItem (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2942:16)
  at JustSink.run (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2950:9)
  at JustObservable.subscribeCore (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2931:19)
  at JustObservable.tryCatcher (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at setDisposable (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1943:46)
  at JustObservable.subscribe [as _subscribe] (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1957:9)
  at JustObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1895:19)
  at FilterObservable.subscribeCore (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5069:26)
  at FilterObservable.tryCatcher (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at setDisposable (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1943:46)
  at FilterObservable.subscribe [as _subscribe] (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1957:9)
  at FilterObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1895:19)
  at FlatMapObservable.subscribeCore (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1987:28)
  at FlatMapObservable.tryCatcher (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at setDisposable (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1943:46)
  at FlatMapObservable.subscribe [as _subscribe] (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1957:9)
  at FlatMapObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1895:19)
  at MergeAllObservable.subscribeCore (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:3587:35)
  at MergeAllObservable.tryCatcher (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at setDisposable (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1943:46)
  at MergeAllObservable.subscribe [as _subscribe] (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1957:9)
  at MergeAllObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1895:19)
  at AnonymousObservable.subscribe [as __subscribe] (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4074:50)
  at AnonymousObservable.tryCatcher (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at setDisposable (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5173:44)
  at AnonymousObservable.innerSubscribe [as _subscribe] (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5187:9)
  at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1895:19)
  at ConnectableObservable.connect (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.binding.js:467:67)
  at AnonymousObservable.__subscribe (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.binding.js:482:62)
  at AnonymousObservable.tryCatcher (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at [object Object].setDisposable [as action] (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5173:44)
  at [object Object].ScheduledItem.invokeCore (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:834:17)
  at [object Object].ScheduledItem.invoke (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:822:40)
  at runTrampoline (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1149:37)
  at tryCatcher (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at Scheduler.scheduleNow [as _schedule] (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1159:45)
  at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:875:19)
  at AnonymousObservable.innerSubscribe [as _subscribe] (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5185:32)
  at AnonymousObservable.Rx.Observable.observableProto.subscribeOnCompleted (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1927:19)
  at Omni.request (/Users/tommunro/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:272:16)
  at makeLightbulbRequest (/Users/tommunro/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-action.js:53:37)
  at update (/Users/tommunro/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-action.js:69:17)
  at AnonymousObserver._onNext (/Users/tommunro/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-action.js:78:55)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1691:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at AnonymousObserver.tryCatcher (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at /Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.time.js:320:54
  at invokeAction (/Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:853:7)
  at /Users/tommunro/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1343:60

```

### Commands

```
  3x -0:13 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:11.9.0 vim-mode-plus:move-to-first-character-of-line-and-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
 18x -0:11.1.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:07.2.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:05.4.0 settings-view:open (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  3x -0:04.8.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_STORE",
      "._*",
      "Thumbs.db",
      ".png",
      ".prefab",
      ".scene",
      ".meta",
      "spine-runtimes/spine-!(csharp)*"
    ],
    "packagesWithKeymapsDisabled": [
      "omnisharp-atom",
      "advanced-new-file",
      "recent-files-fuzzy-finder"
    ],
    "disabledPackages": [
      "vim-mode",
      "isearch"
    ]
  },
  "omnisharp-atom": {
    "nagAddExternalProjects": false,
    "nagAdjustTreeView": false,
    "codeLens": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
advanced-open-file, v0.10.0
atom-yeoman, v0.3.14
clipboard-plus, v0.5.1
cursor-history, v0.4.18
custom-search, v0.0.1
fuzzy-finder, v0.90.0
git-plus, v5.4.7
json-schema, v0.1.13
language-csharp, v0.10.0
linter, v1.6.0
linter-coffeelint, v1.1.0
omnisharp-atom, v0.24.14
recent-files-fuzzy-finder, v0.2.0
remember-file-positions, v0.1.5
save-session, vundefined
symbols-tree-view, v0.10.0
theme-switcher, v1.1.0
vim-mode-clipboard-plus, v0.1.0
vim-mode-plus, v0.1.1
zentabs, v0.8.6

# Dev
omnisharp-atom, v0.22.5
settings-view, v0.219.0
```
