### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by rafalt** [OmniSharp/omnisharp-atom#502]
```c#
public partial class PageA : System.Web.UI.Page
{
	public List<short> ListaA { get; set; }
	public List<short> ListaB { get; set; }
	public List<string> ListaC { get; set; }
       //(2) Right on ListaC (maybe B) and click Go to definition 
	public PackingOrder()
	{
		ListaA = new List<short>();ListaB = new List<short>();ListaC = new List<string>();
	}
	protected void Page_Load(object sender, EventArgs e)
	{
		ListaA.Add(2);
		ListaA.Add(3);//(1)Right on ListaA Go to definition. Reponse not find or something that
		ListaA.Add(4);ListaA.Add(5);ListaB.Add(2013);ListaC.Add("PL");
	}
}
```

**Atom Version**: 1.0.11
**System**: Unknown Windows Version (Windows 7 x64)
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.24.6

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:71

TypeError: Cannot read property 'length' of null
  at C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\find-usages.js:22:63
  at tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at InnerObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5090:49)
  at InnerObserver.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at AutoDetachObserverPrototype.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at Subject.Rx.Subject.addProperties.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5334:19)
  at Subject.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at AutoDetachObserverPrototype.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at AutoDetachObserver.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at AutoDetachObserverPrototype.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at InnerObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:3803:55)
  at InnerObserver.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at AutoDetachObserverPrototype.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at InnerObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:3635:90)
  at InnerObserver.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at AutoDetachObserverPrototype.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at Subject.Rx.Subject.addProperties.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5334:19)
  at Subject.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at AutoDetachObserverPrototype.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at AutoDetachObserver.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at AutoDetachObserverPrototype.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at Subject.Rx.Subject.addProperties.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5334:19)
  at AnonymousObserver._onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\clients\client-base.js:278:55)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1691:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at AnonymousObserver.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at AutoDetachObserverPrototype.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at InnerObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:3635:90)
  at Subject.Rx.Subject.addProperties.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5334:19)
  at AnonymousObserver._onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\clients\client-base.js:217:35)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1691:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at AnonymousObserver.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at AutoDetachObserverPrototype.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at AnonymousObserver._onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.time.js:751:13)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1691:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at AsyncSubject.Rx.AsyncSubject.addProperties.onCompleted (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5424:17)
  at StdioDriver.handlePacketResponse (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:225:22)
  at StdioDriver.handlePacket (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:209:18)
  at StdioDriver.handleData (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:204:18)
  at Interface.<anonymous> (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:145:54)
  at emitOne (events.js:77:13)
  at Interface.emit (events.js:166:7)
  at Interface._onLine (readline.js:195:10)
  at Interface.<anonymous> (readline.js:325:12)
  at Array.forEach (native)
  at Interface._normalWrite (readline.js:324:11)
  at Socket.ondata (readline.js:71:10)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.13
color-picker, v2.0.11
json-schema, v0.1.13
language-aspx, v0.4.0
linter, v1.5.0
omnisharp-atom, v0.24.6

# Dev
No dev packages
```

**Comment by RichiCoder1** [comment]
Getting this error now too

**Comment by rafalt** [comment]
I can't recreate this error again. I trying few time and nothing. Error must have deeper cause.

**Comment by david-driscoll** [comment]
I may have seen this and fixed it with my perf branch, let me know if you
can recreate any problems once we get this next release out.

**Comment by fourq** [comment]
**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.29.4


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:227

TypeError: Cannot read property 'length' of null
    at SafeSubscriber._next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/lib/features/find-usages.js:105:45)
    at SafeSubscriber.__tryOrUnsub (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:223:16)
    at SafeSubscriber.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:172:22)
    at Subscriber._next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at RefCountSubscriber.Subscriber._next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at RefCountSubscriber.Subscriber.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at Subject.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subject.js:55:25)
    at ConnectableSubscriber.Subscriber._next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at ConnectableSubscriber.Subscriber.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at SwitchMapSubscriber.notifyNext (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/operator/switchMap.js:123:30)
    at InnerSubscriber._next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at RefCountSubscriber.Subscriber._next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at RefCountSubscriber.Subscriber.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at Subject.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subject.js:55:25)
    at ConnectableSubscriber.Subscriber._next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at ConnectableSubscriber.Subscriber.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at FilterSubscriber._next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/operator/filter.js:88:30)
    at FilterSubscriber.Subscriber.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at Subject.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subject.js:55:25)
    at SafeSubscriber._next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/omnisharp-client/lib/reactive/reactive-client.js:197:32)
    at SafeSubscriber.__tryOrUnsub (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:223:16)
    at SafeSubscriber.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:172:22)
    at Subscriber._next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at TimeoutSubscriber._next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/operator/timeout.js:84:26)
    at TimeoutSubscriber.Subscriber.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at AsyncSubject.Subject.next (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/Subject.js:55:25)
    at AsyncSubject.complete (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/rxjs/AsyncSubject.js:39:35)
    at StdioDriver.handlePacketResponse (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:275:30)
    at StdioDriver.handlePacket (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:261:22)
    at StdioDriver.handleData (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:254:22)
    at Interface.<anonymous> (/Users/rocky.assad/.dotfiles/atom.symlink/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:149:31)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
    at Socket.ondata (readline.js:86:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

### Commands

```
     -3:24.9.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -3:11.5.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -3:09.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:54 command-palette:toggle (atom-text-editor.editor.is-focused.vim-mode.normal-mode.omnisharp-editor)
 16x -2:50.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -2:31.3.0 omnisharp-atom:solution-status (atom-text-editor.editor.vim-mode.normal-mode.omnisharp-editor)
     -2:18.8.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.omnisharp-editor.is-focused)
     -2:14 omnisharp-atom:settings (atom-text-editor.editor.vim-mode.normal-mode.omnisharp-editor)
  2x -0:25.3.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:10 vim-mode:move-down (atom-text-editor.editor.vim-mode.omnisharp-editor.is-focused.visual-mode)
     -0:09.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.omnisharp-editor.is-focused.visual-mode)
     -0:08.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.omnisharp-editor.is-focused.normal-mode)
     -0:08.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.omnisharp-editor.is-focused.normal-mode)
 23x -0:07.8.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.omnisharp-editor.is-focused.normal-mode)
     -0:01.8.0 omnisharp-atom:go-to-implementation (atom-text-editor.editor.vim-mode.omnisharp-editor.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "background-tips",
      "exception-reporting",
      "metrics",
      "vim-mode-plus-ex-mode",
      "atom-terminal-panel",
      "neon-cursor",
      "neon-selection",
      "symbols-tree-view",
      "talk-like-a-pirate",
      "tree-view-git-branch",
      "npm-outdated",
      "autoupdate-packages",
      "file-icons"
    ],
    "followSymlinks": false,
    "hideGitIgnoredFiles": false,
    "ignoredNames": [
      ".bundle",
      ".git",
      "log",
      "repositories",
      "tmp",
      "vendor"
    ]
  },
  "omnisharp-atom": {
    "altGotoDefinition": true,
    "enhancedHighlighting": true,
    "showDiagnosticsForAllSolutions": true,
    "useLeftLabelColumnForSuggestions": true,
    "wantMetadata": true
  }
}
```

### Installed Packages

```coffee
# User
atom-clock, v0.0.8
atom-ternjs, v0.14.1
atom-yeoman, v0.3.15
auto-update-packages, v1.0.1
autocomplete-elixir, v1.5.13
autocomplete-modules, v1.5.1
clipboard-plus, v0.5.1
docblock-format-helper, v0.3.0
docblockr, v0.7.3
editorconfig, v1.4.1
git-diff-details, v1.3.0
highlight-selected, v0.11.2
iex, v0.9.27
json-schema, v0.1.15
language-docker, v1.1.6
language-dotfiles, v0.3.0
language-elixir, v0.13.1
language-hombrew-formula, v1.0.2
language-ignore, v1.5.0
language-sql-mysql, v0.3.1
linter, v1.11.8
linter-docker, v0.1.2
linter-eslint, v7.2.2
merge-conflicts, v1.4.4
nerd-treeview, v0.4.2
node-debugger, v1.7.0
omnisharp-atom, v0.29.4
pretty-json, v1.4.1
regex-railroad-diagram, v0.16.0
tree-view-git-status, v1.0.0
vim-mode, v0.65.1
vim-mode-clipboard-plus, v0.2.0
yuno-commit-plus, v0.2.1

# Dev
No dev packages
```
