### ISSUE TITLE
Uncaught TypeError: dock_1.dock.addButton is not a function

### ISSUE THREAD

**Issue by jchannon** [OmniSharp/omnisharp-atom#518]
Got the below when upgrading the package

**Atom Version**: 1.0.18
**System**: Mac OS X 10.10.4
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.24.13

### Stack Trace

Uncaught TypeError: dock_1.dock.addButton is not a function

```
At /Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:579

TypeError: dock_1.dock.addButton is not a function
  at FeatureButtons._makeButton (/Users/jonathan/.atom/packages/omnisharp-atom/lib/omnisharp-atom/atom/feature-buttons.js:148:44)
  at /Users/jonathan/.atom/packages/omnisharp-atom/lib/omnisharp-atom/atom/feature-buttons.js:122:38
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:568:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
  at FeatureButtons._button (/Users/jonathan/.atom/packages/omnisharp-atom/lib/omnisharp-atom/atom/feature-buttons.js:117:41)
  at /Users/jonathan/.atom/packages/omnisharp-atom/lib/omnisharp-atom/atom/feature-buttons.js:108:72
  at arrayEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1289:13)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3345:13)
  at FeatureButtons.activate (/Users/jonathan/.atom/packages/omnisharp-atom/lib/omnisharp-atom/atom/feature-buttons.js:108:18)
  at /Users/jonathan/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:133:23
  at arrayEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1289:13)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3345:13)
  at AnonymousObserver._onNext (/Users/jonathan/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:132:19)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1778:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at AnonymousObserver.tryCatcher (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at Subject.Rx.Subject.addProperties.onNext (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5394:19)
  at Subject.tryCatcher (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at AutoDetachObserver.tryCatcher (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.next (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5274:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1710:35)
  at InnerObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2393:16)
  at InnerObserver.tryCatcher (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at MergeAllObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:3607:39)
  at MergeAllObserver.tryCatcher (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at InnerObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4816:59)
  at InnerObserver.tryCatcher (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at InnerObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5157:59)
  at InnerObserver.tryCatcher (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at InnerObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:3639:58)
  at InnerObserver.tryCatcher (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at InnerObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4816:59)
  at InnerObserver.tryCatcher (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at InnerObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5157:59)
  at InnerObserver.tryCatcher (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at InnerObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:3639:58)
  at InnerObserver.tryCatcher (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at InnerObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4816:59)
  at InnerObserver.tryCatcher (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at AsyncSubject.Rx.AsyncSubject.addProperties.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5485:17)
  at AsyncSubject.tryCatcher (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at AutoDetachObserver.tryCatcher (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:567:29)
  at AutoDetachObserverPrototype.completed (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5288:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1730:14)
  at handler (/Users/jonathan/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.async.js:373:20)
  at FSReqWrap.oncomplete (fs.js:82:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "isotope-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-pair, v2.0.10
atom-yeoman, v0.3.14
highlight-selected, v0.10.1
isotope-ui, v2.5.1
json-schema, v0.1.13
language-docker, v1.1.3
linter, v1.6.0
monokai, v0.18.0
node-debugger, v1.1.8
omnisharp-atom, v0.24.13

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
@jchannon was it just after the update, or has it continued to happen since?

**Comment by jchannon** [comment]
just on the upgrade

**Comment by david-driscoll** [comment]
Going to close for now... I'll have to think about how to test an incremental upgrade while atom is still running... without breaking shit.

**Comment by Daniel15** [comment]
For what it's worth, I just encountered this same error while upgrading. I haven't seen it since the upgrade though.
