### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by PavelAgejkin** [OmniSharp/omnisharp-atom#519]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.18
**System**: Microsoft Windows 10 Pro
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.24.13

### Stack Trace

Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

```
At C:\Users\Pavel\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:71

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
  at Object.Rx.helpers.isIterable (C:\Users\Pavel\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.experimental.js:90:13)
  at InnerObserver.onNext (C:\Users\Pavel\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:2017:55)
  at InnerObserver.tryCatcher (C:\Users\Pavel\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at AutoDetachObserverPrototype.next (C:\Users\Pavel\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Pavel\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at C:\Users\Pavel\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.time.js:320:54
  at invokeAction (C:\Users\Pavel\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:853:7)
  at C:\Users\Pavel\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1343:60

```

### Commands

```
```

### Config

```json
{
  "core": {},
  "omnisharp-atom": {
    "enhancedHighlighting": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-wallaby, v1.0.4
atom-yeoman, v0.3.14
highlight-selected, v0.10.1
json-schema, v0.1.13
linter, v1.6.0
omnisharp-atom, v0.24.13

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
Were you doing anything of note, that might help figure out what line is throwing here.

**Comment by willl** [comment]
[Enter steps to reproduce below:]

1. Opened omnisharp-server repo on OS X.
2. Turn on code lens and syntax highlighting.
3. Opened FakeAssembly.cs, FakeFileSystem.cs and FakeSolution.cs.
4. Used keyboard shortcuts to close the 3 files.
5. Once the last is closed, *boom* error.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.24.14


### Stack Trace

Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

```
At /Users/willl/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:71

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
  at Object.Rx.helpers.isIterable (/Users/willl/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.experimental.js:90:13)
  at InnerObserver.onNext (/Users/willl/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2017:55)
  at InnerObserver.tryCatcher (/Users/willl/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/Users/willl/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/willl/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at /Users/willl/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.time.js:320:54
  at invokeAction (/Users/willl/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:853:7)
  at /Users/willl/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1343:60

```

### Commands

```
     -2:03.3.0 omnisharp-atom:toggle-errors (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
     -2:00.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
  4x -1:22.1.0 core:close (atom-text-editor.editor.is-focused)
  2x -1:08.1.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
  2x -1:01.5.0 omnisharp-atom:toggle-errors (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
  2x -0:47.7.0 core:close (atom-text-editor.editor.is-focused)
  2x -0:28.8.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui)
  3x -0:11 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "omnisharp-atom": {
    "enhancedHighlighting": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v6.0.18
atom-yeoman, v0.3.14
browser-plus, v0.0.34
editorconfig, v1.2.0
json-schema, v0.1.13
language-cshtml, v0.1.1
linter, v1.6.0
monokai, v0.18.0
omnisharp-atom, v0.24.14

# Dev
No dev packages
```

**Comment by tugberkugurlu** [comment]
:+1: 

It may help: I am seeing this error frequently in Linux (Ubuntu) with Atom editor.

**Comment by david-driscoll** [comment]
@willl I tried the close all tabs command, and closing tabs one by one with the keyboard, and didn't see this popup.  Able to still get it to happen?

**Comment by willl** [comment]
@david-driscoll Seems to be working now. I am no longer able to reproduce the issue.
