### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of undefined

### ISSUE THREAD

**Issue by rafalt** [OmniSharp/omnisharp-atom#527]
``` C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:71
Hide Stack Trace
TypeError: Cannot read property 'getSelectedBufferRange' of undefined
  at CodeAction.getRequest (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\code-action.js:97:27)
  at C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\code-action.js:53:108
  at clientCallback (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni.js:251:21)
  at tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at InnerObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:2010:45)
  at InnerObserver.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at AutoDetachObserverPrototype.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at InnerObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5094:29)
  at InnerObserver.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at AutoDetachObserverPrototype.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at scheduleItem (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:2942:16)
  at JustSink.run (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:2950:9)
  at JustObservable.subscribeCore (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:2931:19)
  at JustObservable.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at setDisposable (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1943:46)
  at JustObservable.subscribe [as _subscribe] (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1957:9)
  at JustObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1895:19)
  at FilterObservable.subscribeCore (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5069:26)
  at FilterObservable.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at setDisposable (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1943:46)
  at FilterObservable.subscribe [as _subscribe] (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1957:9)
  at FilterObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1895:19)
  at FlatMapObservable.subscribeCore (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1987:28)
  at FlatMapObservable.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at setDisposable (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1943:46)
  at FlatMapObservable.subscribe [as _subscribe] (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1957:9)
  at FlatMapObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1895:19)
  at MergeAllObservable.subscribeCore (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:3587:35)
  at MergeAllObservable.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at setDisposable (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1943:46)
  at MergeAllObservable.subscribe [as _subscribe] (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1957:9)
  at MergeAllObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1895:19)
  at AnonymousObservable.subscribe [as __subscribe] (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:4074:50)
  at AnonymousObservable.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at setDisposable (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5173:44)
  at AnonymousObservable.innerSubscribe [as _subscribe] (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5187:9)
  at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1895:19)
  at ConnectableObservable.connect (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.binding.js:467:67)
  at AnonymousObservable.__subscribe (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.binding.js:482:62)
  at AnonymousObservable.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at [object Object].setDisposable [as action] (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5173:44)
  at [object Object].ScheduledItem.invokeCore (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:834:17)
  at [object Object].ScheduledItem.invoke (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:822:40)
  at runTrampoline (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1149:37)
  at tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at Scheduler.scheduleNow [as _schedule] (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1159:45)
  at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:875:19)
  at AnonymousObservable.innerSubscribe [as _subscribe] (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5185:32)
  at AnonymousObservable.Rx.Observable.observableProto.subscribeOnCompleted (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1927:19)
  at Omni.request (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\lib\omni-sharp-server\omni.js:272:16)
  at makeLightbulbRequest (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\code-action.js:53:37)
  at update (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\code-action.js:69:17)
  at AnonymousObserver._onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\lib\omnisharp-atom\features\code-action.js:78:55)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1691:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at AnonymousObserver.tryCatcher (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:59:31)
  at AutoDetachObserverPrototype.next (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1625:31)
  at C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.time.js:320:54
  at invokeAction (C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:853:7)
  at C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1343:60
```

Hi,
I have folder with one file example.cs,
I have open this file,

```
using System;

namespace OmniSharpDemo{
    public class Todo{
        public String Title {get;set;}
        public bool Complate {get;set;}
        public Todo(String title = "New Task"){
            Title = title;
            Complete = false;
        }
    }
}
```

In Omnisharp output I have

```
Errors & WarningsOmnisharp output
Starting OmniSharp server (pid:11036)
OmniSharp Location: C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\roslyn\omnisharp.cmd
Change the location that OmniSharp is loaded from by setting the OMNISHARP environment variable
OmniSharp Path: F:\MyTests\TestVS
Omnisharp server running using stdio at location 'F:\MyTests\TestVS' on host 11036.
Using runtime 'C:\Users\rafal.tynski\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7'.
Scanning 'F:\MyTests\TestVS' for DNX projects
No project.json based projects found

Errors & WarningsOmnisharp output
Starting OmniSharp server (pid:11036)
OmniSharp Location: C:\Users\rafal.tynski\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\roslyn\omnisharp.cmd
Change the location that OmniSharp is loaded from by setting the OMNISHARP environment variable
OmniSharp Path: F:\MyTests\TestVS
Omnisharp server running using stdio at location 'F:\MyTests\TestVS' on host 11036.
Using runtime 'C:\Users\rafal.tynski\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7'.
Scanning 'F:\MyTests\TestVS' for DNX projects
No project.json based projects found
started
Could not find any CSX files
No solution files found in 'F:\MyTests\TestVS'
Solution has finished loading
Detecting CSX files in 'F:\MyTests\TestVS'.
/projects: 200 203ms
/packagesource: 200 245ms
/codecheck: 200 17ms
.....
```

Click on settings and I get error.

**Comment by adamralph** [comment]
I get this too.
