### ISSUE TITLE
Uncaught Error: request.FileName must not be null

### ISSUE THREAD

**Issue by sgarcia39** [OmniSharp/omnisharp-atom#538]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.24.16

### Stack Trace

Uncaught Error: request.FileName must not be null

```
At /Users/sgarcia/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:71

Error: request.FileName must not be null
    at isNotNull (/Users/sgarcia/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/clients/client-v1.js:9:15)
    at Solution.ClientV1.typelookup (/Users/sgarcia/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/clients/client-v1.js:316:9)
    at /Users/sgarcia/.atom/packages/omnisharp-atom/lib/omni-sharp-server/solution.js:145:98
    at Solution._fixupRequest (/Users/sgarcia/.atom/packages/omnisharp-atom/lib/omni-sharp-server/solution.js:93:16)
    at Solution.(anonymous function) [as typelookup] (/Users/sgarcia/.atom/packages/omnisharp-atom/lib/omni-sharp-server/solution.js:145:29)
    at /Users/sgarcia/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/lookup.js:141:60
    at solutionCallback (/Users/sgarcia/.atom/packages/omnisharp-atom/lib/omni-sharp-server/omni.js:225:21)
    at tryCatcher (/Users/sgarcia/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
    at InnerObserver.onNext (/Users/sgarcia/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2010:45)
    at InnerObserver.tryCatcher (/Users/sgarcia/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
    at AutoDetachObserverPrototype.next (/Users/sgarcia/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/sgarcia/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
    at InnerObserver.onNext (/Users/sgarcia/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5094:29)
    at InnerObserver.tryCatcher (/Users/sgarcia/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
    at AutoDetachObserverPrototype.next (/Users/sgarcia/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/sgarcia/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
```

### Commands

```
     -1:14.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:14 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:09.5.0 core:save (atom-text-editor.editor.omnisharp-editor.is-focused)
     -1:06.8.0 core:copy (atom-text-editor.editor.omnisharp-editor.is-focused)
  6x -1:05.7.0 find-and-replace:select-next (atom-text-editor.editor.omnisharp-editor.is-focused)
     -1:01.7.0 core:paste (atom-text-editor.editor.omnisharp-editor.is-focused)
     -1:01.5.0 core:save (atom-text-editor.editor.omnisharp-editor.is-focused)
     -1:00.6.0 find-and-replace:show (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:59.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:59.2.0 core:save (atom-text-editor.editor.mini.is-focused)
  3x -0:42.7.0 find-and-replace:select-next (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:31.7.0 core:save (atom-text-editor.editor.omnisharp-editor.is-focused.autocomplete-active)
     -0:22.2.0 core:copy (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:22.1.0 find-and-replace:show (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:21.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:21.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.meta"
    ]
  },
  "omnisharp-atom": {
    "codeLens": false
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
json-schema, v0.1.15
linter, v1.8.1
minimap, v4.13.4
node-debugger, v1.1.8
omnisharp-atom, v0.24.16
unity-shader-files, v0.1.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
@sgarcia39 is this still happening?  I think I might have fixed this one already.
