### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by k0st1x** [OmniSharp/omnisharp-atom#543]
[Enter steps to reproduce below:]

1. update "omnisharp atom" to 0.25.1

**Atom Version**: 1.0.19
**System**: Ubuntu 15.04
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.25.1

### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:71

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/home/k0st1x/.atom/packages/omnisharp-atom/lib/omni-sharp-server/solution.js:4:78)
  at /home/k0st1x/.atom/packages/omnisharp-atom/lib/omni-sharp-server/solution.js:11:5
  at Object.<anonymous> (/home/k0st1x/.atom/packages/omnisharp-atom/lib/omni-sharp-server/solution.js:130:3)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/k0st1x/.atom/packages/omnisharp-atom/lib/omni-sharp-server/solution-manager.js:4:18)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/k0st1x/.atom/packages/omnisharp-atom/lib/omnisharp-atom/atom/solution-information.js:4:26)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at loadFeature (/home/k0st1x/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:218:26)
  at Object.load (/home/k0st1x/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:230:31)
  at /home/k0st1x/.atom/packages/omnisharp-atom/lib/omnisharp-atom/omnisharp-atom.js:119:48
  at tryCatcher (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at InnerObserver.onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2010:45)
  at InnerObserver.tryCatcher (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at InnerObserver.onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5094:29)
  at InnerObserver.tryCatcher (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at AnonymousObserver._onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:3306:28)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1691:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at AnonymousObserver.tryCatcher (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at InnerObserver.onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4792:14)
  at InnerObserver.tryCatcher (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at InnerObserver.onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5094:29)
  at InnerObserver.tryCatcher (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at InnerObserver.onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:3635:90)
  at InnerObserver.tryCatcher (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at InnerObserver.onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4792:14)
  at InnerObserver.tryCatcher (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:59:31)
  at AutoDetachObserverPrototype.next (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5214:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1625:31)
  at AsyncSubject.Rx.AsyncSubject.addProperties.onCompleted (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5424:17)
  at handler (/home/k0st1x/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.async.js:317:7)
  at FSReqWrap.oncomplete (fs.js:82:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
json-schema, v0.1.15
linter, v1.8.1
omnisharp-atom, v0.25.1

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
I have not seen this before myself.  Let me know if this issue persists, or it may been fixed recently.
