### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by xasx** [OmniSharp/omnisharp-atom#549]
[Enter steps to reproduce below:]

1. Not sure. The error occurs randomly. Will Report as soon as I find a pattern.

**Atom Version**: 1.0.19
**System**: AWXPW
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.25.9

### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:77

TypeError: Path must be a string. Received null
  at assertPath (path.js:8:11)
  at Object.win32.normalize (path.js:148:3)
  at AnonymousObserver._onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\lib\omni-sharp-server\view-model.js:120:31)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1787:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
  at AnonymousObserver.tryCatcher (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
  at AutoDetachObserverPrototype.next (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5793:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
  at InnerObserver.next (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5283:14)
  at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
  at InnerObserver.tryCatcher (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
  at AutoDetachObserverPrototype.next (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5793:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
  at InnerObserver.next (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5669:29)
  at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
  at InnerObserver.tryCatcher (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
  at AutoDetachObserverPrototype.next (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5793:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
  at Subject.Rx.Subject.addProperties.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5908:19)
  at Subject.tryCatcher (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
  at AutoDetachObserverPrototype.next (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5793:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
  at Subject.Rx.Subject.addProperties.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5908:19)
  at AnonymousObserver._onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\clients\client-base.js:320:55)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1787:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
  at AnonymousObserver.tryCatcher (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
  at AutoDetachObserverPrototype.next (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5793:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
  at InnerObserver.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:3850:90)
  at Subject.Rx.Subject.addProperties.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5908:19)
  at AnonymousObserver._onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\clients\client-base.js:263:72)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1787:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
  at AnonymousObserver.tryCatcher (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
  at AutoDetachObserverPrototype.next (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5793:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
  at AnonymousObserver._onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.time.js:863:13)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1787:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
  at AsyncSubject.Rx.AsyncSubject.addProperties.onCompleted (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5995:17)
  at StdioDriver.handlePacketResponse (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:203:26)
  at StdioDriver.handlePacket (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:189:18)
  at StdioDriver.handleData (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:184:18)
  at Interface.<anonymous> (C:\Users\Andreas\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:126:54)
  at emitOne (events.js:77:13)
  at Interface.emit (events.js:169:7)
  at Interface._onLine (readline.js:209:10)
  at Interface.<anonymous> (readline.js:339:12)
  at Array.forEach (native)
  at Interface._normalWrite (readline.js:338:11)
  at Socket.ondata (readline.js:85:10)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:520:20)

```

### Commands

```
     -2:52.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-github-2014.theme-metro-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "metro-ui",
      "github-2014"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v7.5.1
atom-yeoman, v0.3.15
file-icons, v1.6.11
fonts, v0.7.0
github-2014, v3.10.1
json-schema, v0.1.15
language-csharp, v0.11.0
linter, v1.9.0
metro-ui, v2.2.2
minimap, v4.15.0
omnisharp-atom, v0.25.9
pdf-view, v0.34.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
I remember that issue, it should be solved now, if not feel free to reopen and we can go from there.
