### ISSUE TITLE
Uncaught TypeError: Cannot read property 'selectPane' of undefined

### ISSUE THREAD

**Issue by CrazyD0G** [OmniSharp/omnisharp-atom#55]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.9.5
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.1.6

### Stack Trace

Uncaught TypeError: Cannot read property 'selectPane' of undefined

```
At /Users/alexandr/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/find-usages.coffee:12

TypeError: Cannot read property 'selectPane' of undefined
  at atom-workspace.<anonymous> (/Users/alexandr/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/find-usages.coffee:12:32)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
     -2:26.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:10.7 omnisharp-atom:toggle (atom-text-editor.editor.is-focused)
     -1:53.3 timecop:view (atom-text-editor.editor.is-focused)
     -1:41.5 symbols-view:toggle-file-symbols (atom-text-editor.editor.is-focused)
     -1:35.9 core:confirm (atom-text-editor.editor.mini)
     -1:23.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.is-focused)
     -1:17.3 dev-live-reload:reload-all (atom-text-editor.editor.is-focused)
     -1:11.7 key-binding-resolver:toggle (atom-text-editor.editor.is-focused)
     -1:09.1 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:09.1 core:cancel (atom-text-editor.editor.is-focused)
     -0:59.3 markdown-preview:toggle (atom-text-editor.editor.is-focused)
  2x -0:52.8 minimap:toggle (atom-text-editor.editor.is-focused)
     -0:36.5 styleguide:show (atom-text-editor.editor.is-focused)
     -0:26.7 symbols-view:toggle-project-symbols (atom-text-editor.editor.is-focused)
  2x -0:13.6 omnisharp-atom:go-to-definition (atom-text-editor.editor)
     -0:03.6 omnisharp-atom:find-usages (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus-async, v0.22.0
language-csharp, v0.3.0
minimap, v3.5.6
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.1
monokai, v0.12.0
omnisharp-atom, v0.1.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by Mpdreamz** [comment]
@CrazyD0G you have to uninstall autocomplete-plus-async and install the latest `autocomplete-plus` package as well as update to `0.2.0` of our package. 

Find usages should work on the latest atom and latest version of our package.
