### ISSUE TITLE
Uncaught Error: request.ProjectPath  must not be null.

### ISSUE THREAD

**Issue by dinason** [OmniSharp/omnisharp-atom#550]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.25.9

### Stack Trace

Uncaught Error: request.ProjectPath  must not be null.

```
At /Users/Daiki/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:77

Error: request.ProjectPath  must not be null.
    at Solution.descriptor.value (/Users/Daiki/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/decorators.js:11:23)
    at Solution.descriptor.value [as packagesource] (/Users/Daiki/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/decorators.js:77:22)
    at AnonymousObserver._onNext (/Users/Daiki/.atom/packages/omnisharp-atom/lib/omni-sharp-server/view-model.js:64:23)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/Daiki/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1787:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Daiki/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
    at AnonymousObserver.tryCatcher (/Users/Daiki/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/Users/Daiki/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5793:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Daiki/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
    at InnerObserver.next (/Users/Daiki/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5669:29)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Daiki/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
    at Subject.Rx.Subject.addProperties.onNext (/Users/Daiki/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5908:19)
    at StdioDriver.handlePacketEvent (/Users/Daiki/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:220:36)
    at StdioDriver.handlePacket (/Users/Daiki/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:192:18)
    at StdioDriver.handleData (/Users/Daiki/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:184:18)
    at Interface.<anonymous> (/Users/Daiki/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:126:54)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:209:10)
    at Interface.<anonymous> (readline.js:339:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:338:11)
    at Socket.ondata (readline.js:85:10)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "omnisharp-atom": {
    "codeLens": false,
    "developerMode": true
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
file-icons, v1.6.11
japanese-wrap, v0.2.7
json-schema, v0.1.15
linter, v1.9.0
linter-mcs, v0.2.0
minimap, v4.15.0
omnisharp-atom, v0.25.9
unity-shader-files, v0.1.0
vim-mode, v0.61.0

# Dev
No dev packages
```

**Comment by Pondidum** [comment]
[Enter steps to reproduce below:]

1. open atom - last project selected is a solution directory
2. omnisharp asks for which sln to load (2x sln files in base directory)
3. select one of them, this error occurs.

**Atom Version**: 1.0.11
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.25.10


### Stack Trace

Uncaught Error: request.ProjectPath  must not be null.

```
At C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:77

Error: request.ProjectPath  must not be null.
    at Solution.descriptor.value (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\decorators.js:11:23)
    at Solution.descriptor.value [as packagesource] (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\decorators.js:77:22)
    at AnonymousObserver._onNext (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\lib\omni-sharp-server\view-model.js:64:23)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1787:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
    at AnonymousObserver.tryCatcher (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5793:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
    at InnerObserver.next (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5669:29)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1721:31)
    at Subject.Rx.Subject.addProperties.onNext (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5908:19)
    at StdioDriver.handlePacketEvent (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:220:36)
    at StdioDriver.handlePacket (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:192:18)
    at StdioDriver.handleData (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:184:18)
    at Interface.<anonymous> (C:\Users\AndrewDavies\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\stdio.js:126:54)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:166:7)
    at Interface._onLine (readline.js:195:10)
    at Interface.<anonymous> (readline.js:325:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:324:11)
    at Socket.ondata (readline.js:71:10)
```

### Commands

```
     -0:08.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "customFileTypes": {
      "source.sql": [
        "prc"
      ],
      "source": [
        "[object Object]"
      ]
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
autoclose-html, v0.19.0
copy-path, v0.1.1
file-types, v0.5.1
json-schema, v0.1.15
language-javascript-jsx, v0.3.7
language-lua, v0.9.4
language-vb, v0.1.0-pre1
linter, v1.10.0
omnisharp-atom, v0.25.10
pretty-json, v0.4.1
project-manager, v2.6.5
save-session, vundefined
tab-control, v0.6.8

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
I think in the latest version this has been solved, let me know though if there is a continuing problem!
