### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Changes' of null

### ISSUE THREAD

**Issue by dopare** [OmniSharp/omnisharp-atom#557]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.25.10

### Stack Trace

Uncaught TypeError: Cannot read property 'Changes' of null

```
At /Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:77

TypeError: Cannot read property 'Changes' of null
  at Object.applyChanges (/Users/Dopare/.atom/packages/omnisharp-atom/lib/omnisharp-atom/services/apply-changes.js:4:17)
  at AnonymousObserver._onNext (/Users/Dopare/.atom/packages/omnisharp-atom/lib/omnisharp-atom/features/code-format.js:46:73)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1787:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
  at AnonymousObserver.tryCatcher (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
  at InnerObserver.next (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:4585:41)
  at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
  at InnerObserver.tryCatcher (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
  at AutoDetachObserverPrototype.next (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5793:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
  at AnonymousObserver._onNext (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/contexts.js:49:30)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1787:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
  at AnonymousObserver.tryCatcher (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
  at AutoDetachObserverPrototype.next (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5793:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
  at FirstObserver.next (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.aggregates.js:945:19)
  at FirstObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
  at Subject.Rx.Subject.addProperties.onNext (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5908:19)
  at AnonymousObserver._onNext (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/clients/client-base.js:263:72)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1787:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
  at AnonymousObserver.tryCatcher (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
  at AutoDetachObserverPrototype.next (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5793:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
  at AnonymousObserver._onNext (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.time.js:863:13)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1787:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1721:31)
  at AsyncSubject.Rx.AsyncSubject.addProperties.onCompleted (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5995:17)
  at StdioDriver.handlePacketResponse (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:203:26)
  at StdioDriver.handlePacket (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:189:18)
  at StdioDriver.handleData (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:184:18)
  at Interface.<anonymous> (/Users/Dopare/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:126:54)
  at emitOne (events.js:77:13)
  at Interface.emit (events.js:169:7)
  at Interface._onLine (readline.js:209:10)
  at Interface.<anonymous> (readline.js:339:12)
  at Array.forEach (native)
  at Interface._normalWrite (readline.js:338:11)
  at Socket.ondata (readline.js:85:10)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:520:20)

```

### Commands

```
     -0:07.4.0 core:move-left (atom-text-editor.editor.omnisharp-editor.is-focused)
  2x -0:07.1.0 core:backspace (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:06.3.0 snippets:next-tab-stop (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:06.3.0 snippets:expand (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:06.3.0 editor:indent (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:05.5.0 core:backspace (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:04.9.0 core:save (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:02.3.0 core:backspace (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:02.1.0 omnisharp-atom:code-format-on-curly-brace (atom-text-editor.editor.omnisharp-editor.is-focused)
```

### Config

```json
{
  "core": {},
  "omnisharp-atom": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
json-schema, v0.1.15
linter, v1.10.0
omnisharp-atom, v0.25.10

# Dev
No dev packages
```

**Comment by Kollibri** [comment]
I am also getting this error while editing a c# file.

**Comment by Zappex** [comment]
Same here. Basically I get this error while writing ' ; ' at end of line or expression.
It would be nice to know how to fix it

**Comment by nitzanbueno** [comment]
I also get this error, and there's no IntelliSense either.

**Comment by david-driscoll** [comment]
This should be fixed the latest version, let me know if you see a problem again.
