### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Documentation' of undefined

### ISSUE THREAD

**Issue by prasannavl** [OmniSharp/omnisharp-atom#561]
[Enter steps to reproduce below:]

Happened on typing the "app.UseDeveloperExceptionPage" method's intellisense from the latest rc1 packages of ASP vNext.

**Atom Version**: 1.2.3
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.25.10

### Stack Trace

Uncaught TypeError: Cannot read property 'Documentation' of undefined

```
At C:\Users\PVL\.atom\packages\omnisharp-atom\node_modules\fastdom\index.js:260

TypeError: Cannot read property 'Documentation' of undefined
    at FastDom.<anonymous> (C:\Users\PVL\.atom\packages\omnisharp-atom\lib\omnisharp-atom\views\signature-help-view.js:168:61)
    at FastDom.run (C:\Users\PVL\.atom\packages\omnisharp-atom\node_modules\fastdom\index.js:318:17)
    at FastDom.flush (C:\Users\PVL\.atom\packages\omnisharp-atom\node_modules\fastdom\index.js:228:12)
    at FastDom.runBatch (C:\Users\PVL\.atom\packages\omnisharp-atom\node_modules\fastdom\index.js:249:12)
    at C:\Users\PVL\.atom\packages\omnisharp-atom\node_modules\fastdom\index.js:193:12
    at frame (C:\Users\PVL\.atom\packages\omnisharp-atom\node_modules\fastdom\index.js:364:15)
```

### Commands

```
  2x -0:24.1.0 fuzzy-finder:toggle-file-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:20.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:08.8.0 core:move-right (atom-text-editor.editor.is-focused.omnisharp-editor)
  2x -0:07.8.0 core:backspace (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:06.1.0 core:move-down (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:05.7.0 core:move-up (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:03.3.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused.omnisharp-editor)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "autocomplete-python",
      "go-find-references",
      "go-rename",
      "language-rust",
      "node-debugger",
      "quantum-shell",
      "script",
      "jshint"
    ]
  },
  "omnisharp-atom": {
    "autoAddExternalProjects": true,
    "autoAdjustTreeView": true,
    "signatureHelp": true,
    "codeLens": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-html-preview, v0.1.13
atom-jade, v0.3.0
atom-ternjs, v0.8.6
atom-typescript, vundefined
atom-yeoman, v0.3.15
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
autocomplete-clang, v0.8.8
color-picker, v2.0.13
highlight-line, v0.11.0
highlight-selected, v0.11.1
javascript-snippets, v1.0.0
json-schema, v0.1.15
language-javascript-jsx, v0.3.7
language-powershell, v2.1.0
last-cursor-position, v0.9.0
linter, v1.11.2
linter-eslint, v5.2.1
minimap, v4.16.1
minimap-find-and-replace, v4.3.2
minimap-highlight-selected, v4.3.1
omnisharp-atom, v0.25.10
pigments, v0.19.0
save-session, v0.15.7

# Dev
No dev packages
```

**Comment by wmeints** [comment]
Same is happening, Exception I'm running on OS X 10.10.
It only happens for the IApplicationBuilder methods.

**Comment by dill0wn** [comment]
I'm seeing the same thing.  I've got a hunch that it's related to the "signatureHelp" option.  I'm saying this because a bunch of these all blew up in a row after hitting enter to auto-complete `string.IsNullOrEmpty(string value)`.  It was showing:

![screenshot 2016-01-14 18 16 23](https://cloud.githubusercontent.com/assets/1267330/12340773/f19c50a8-baea-11e5-9ca1-3b74a6cd8fbb.png)

**Comment by david-driscoll** [comment]
It is signature help, I thought I had killed all those exceptions, but I
noticed one earlier today.

**Comment by Yantrio** [comment]
I get these too, and my atom freezes at the same time :(

**Comment by LouisTakePILLz** [comment]
I'd love to see this fixed; it's a usability-crippling bug.
