### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Dnx' of null

### ISSUE THREAD

**Issue by martinaware** [OmniSharp/omnisharp-atom#562]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.25.10

### Stack Trace

Uncaught TypeError: Cannot read property 'Dnx' of null

```
At C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:77

TypeError: Cannot read property 'Dnx' of null
    at C:\Users\t375678\.atom\packages\omnisharp-atom\lib\omni-sharp-server\view-model.js:116:52
    at tryCatcher (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at InnerObserver.next (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5619:49)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1752:31)
    at InnerObserver.tryCatcher (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5747:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1752:31)
    at Subject.Rx.Subject.addProperties.onNext (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5862:19)
    at Subject.tryCatcher (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5747:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1752:31)
    at Subject.Rx.Subject.addProperties.onNext (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5862:19)
    at AnonymousObserver._onNext (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\clients\client-base.js:282:113)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1818:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1752:31)
    at AnonymousObserver.tryCatcher (C:\Users\t375678\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
```

### Commands

```
     -1:59 omnisharp-atom:go-to-definition (atom-text-editor.editor.omnisharp-editor.is-focused)
     -1:36.9.0 omnisharp-atom:toggle-errors (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:24.8.0 omnisharp-atom:new-project (atom-text-editor.editor.omnisharp-editor.is-focused)
  2x -0:11.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, vundefined
atom-yeoman, v0.3.15
json-schema, v0.1.15
linter, v1.11.2
minimap, v4.16.1
minimap-git-diff, v4.1.8
omnisharp-atom, v0.25.10

# Dev
No dev packages
```

**Comment by schotime** [comment]
I'm getting this issue too.

**Comment by david-driscoll** [comment]
I think I have this solved with the latest release, let me know if you're still seeing it as an issue.
