### ISSUE TITLE
Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration faile...

### ISSUE THREAD

**Issue by dark0084** [OmniSharp/omnisharp-atom#577]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.26.1

### Stack Trace

Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'omnisharp-flame'. A type with that name is already registered.

```
At /Users/s840525/.atom/packages/omnisharp-atom/lib/views/status-bar-view.js:143

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'omnisharp-flame'. A type with that name is already registered.
    at Error (native)
    at Object.<anonymous> (/Users/s840525/.atom/packages/omnisharp-atom/lib/views/status-bar-view.js:143:33)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/s840525/.atom/packages/omnisharp-atom/lib/atom/status-bar.js:12:22)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at OmniSharpAtom.consumeStatusBar (/Users/s840525/.atom/packages/omnisharp-atom/lib/omnisharp-atom.js:390:21)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
     -2:57.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:06.3.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:44 editor:newline (atom-text-editor.editor.is-focused)
  8x -1:41.3.0 core:backspace (atom-text-editor.editor.is-focused)
 17x -1:09.3.0 core:move-left (atom-text-editor.editor.is-focused)
  7x -1:07.8.0 core:backspace (atom-text-editor.editor.is-focused)
 17x -1:06.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:03.3.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "line-ending-selector"
    ]
  },
  "omnisharp-atom": {
    "codeLens": false
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
auto-indent, v0.5.0
json-schema, v0.1.15
line-diff-details, v1.1.3
line-ending-converter, v1.3.2
linter, v1.11.3
omnisharp-atom, v0.26.1

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
That's very strange...  were you updating through the Atom UI?  That's my guess as to how that happened...

**Comment by chemitaxis** [comment]
I have the same problem, updated from the User Interface...

**Comment by 32graham** [comment]
This just happened to me right after adding kendo-ui to my project. Seems related to the fact that kendo-ui contains some HTML custom elements that would be using `document.registerElement`.

**Comment by breiter** [comment]
This just happened to me updating from within the Atom UI but appeared to be resolved after exiting and re-launching Atom.

**Comment by david-driscoll** [comment]
There is no API I'm aware of that lets us `unregister` a custom element that has been added, so probably the solution for this is just to restart atom after updating if it happens.
