### ISSUE TITLE
Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration faile...

### ISSUE THREAD

**Issue by saipuli** [OmniSharp/omnisharp-atom#587]
1. Update omnisharp-atom package.

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.26.6

### Stack Trace

Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'omnisharp-flame'. A type with that name is already registered.

```
At /Users/spuli/.atom/packages/omnisharp-atom/lib/views/status-bar-view.js:143

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'omnisharp-flame'. A type with that name is already registered.
    at Error (native)
    at Object.<anonymous> (/Users/spuli/.atom/packages/omnisharp-atom/lib/views/status-bar-view.js:143:33)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/spuli/.atom/packages/omnisharp-atom/lib/atom/status-bar.js:12:22)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at OmniSharpAtom.consumeStatusBar (/Users/spuli/.atom/packages/omnisharp-atom/lib/omnisharp-atom.js:390:21)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "omnisharp-atom": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, vundefined
atom-yeoman, v0.3.15
json-schema, v0.1.15
language-csharp, v0.11.0
language-cshtml, v0.1.1
linter, v1.11.3
omnisharp-atom, v0.26.6

# Dev
No dev packages
```

**Comment by jchannon** [comment]
Just got this upgrading to 0.26.7

**Comment by serialseb** [comment]
You and I
