### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by dill0wn** [OmniSharp/omnisharp-atom#616]
[Enter steps to reproduce below:]

1. I opened a c# file from Finder.  The file is a part of a project, and has a .git repo at its project root.

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.26.8

### Stack Trace

Uncaught ReferenceError: $ is not defined

```
At /Users/dillon/.atom/packages/omnisharp-atom/node_modules/fastdom/fastdom.js:192

ReferenceError: $ is not defined
    at omnisharp-output-list.scrollToItemView (/Users/dillon/.atom/packages/omnisharp-atom/lib/views/output-component.js:177:24)
    at /Users/dillon/.atom/packages/omnisharp-atom/lib/views/output-component.js:77:32
    at runTasks (/Users/dillon/.atom/packages/omnisharp-atom/node_modules/fastdom/fastdom.js:206:50)
    at flush (/Users/dillon/.atom/packages/omnisharp-atom/node_modules/fastdom/fastdom.js:181:5)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "bracket-matcher",
      "linter-flexpmd",
      "markdown-preview"
    ],
    "ignoredNames": [
      "*.swp",
      "*.swo",
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "tags",
      "*.taghl"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "omnisharp-atom": {
    "IgnoredCodeIssues": [
      "^Keyword 'private' is redundant. This is the default modifier.$",
      ".* should not separate words with an underscore.*",
      "^Redundant argument name specification$",
      "^Convert to '.*' expre.",
      "^Use 'var' keyword$",
      "^Name should have prefix.",
      "^Redundant ToString.",
      "^Initializing field by default value is redundant$",
      "^Parameter can be IComparable$",
      "^Convert to constant.*",
      "^Variable could be moved to a nested scope$",
      "^Method never reaches its end or a 'return' statement.$",
      ".* should start with an upper case letter. \\(Rule 'Enum Members'\\)$"
    ],
    "autoAdjustTreeView": true,
    "codeLens": false,
    "enableAdvancedFileNew": false,
    "enhancedHighlighting": true,
    "useLeftLabelColumnForSuggestions": true
  }
}
```

### Installed Packages

```coffee
# User
atom-cli-diff, v1.3.0
atom-yeoman, v0.3.15
highlight-line, v0.11.0
json-schema, v0.1.15
language-actionscript3, v0.3.0
linter, v1.11.3
linter-perl, v0.7.1
linter-xmllint, v1.3.0
markdown-preview-plus, v2.2.2
monokai, v0.18.0
omnisharp-atom, v0.26.8
pretty-json, v0.4.1
project-manager, v2.7.3
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by enkafan** [comment]
seeing the same thing with a fresh install of Atom 1.4 on Windows 10.

**Comment by david-driscoll** [comment]
I'll take a look tonight.

**Comment by ccbentlee** [comment]
yeah,just update ominsharp and got the same issue.Another problem is in settings the first line is 'undefined'.I don't know what this means.

**Comment by jguarShark** [comment]
I'm having the same problem, since updating, when I do pretty much anything having to do with a C# file.

**Comment by aivascu** [comment]
The issue is rather trivial. 
There is a missing reference to jQuery in the omnisharp-atom\lib\views\output-component.ts(.js). 
I fixed the issue by adding
var $ = require("jquery"); 
at the beginning of the js file.

**Comment by ertseyhan** [comment]
[Enter steps to reproduce below:]

1. Got this error after updating OmniSharp

**Atom Version**: 1.4.0
**System**: "Arch Linux"
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.26.8


### Stack Trace

Uncaught ReferenceError: $ is not defined

```
At /home/ertseyhan/.atom/packages/omnisharp-atom/node_modules/fastdom/fastdom.js:192

ReferenceError: $ is not defined
    at omnisharp-output-list.scrollToItemView (/home/ertseyhan/.atom/packages/omnisharp-atom/lib/views/output-component.js:177:24)
    at /home/ertseyhan/.atom/packages/omnisharp-atom/lib/views/output-component.js:77:32
    at runTasks (/home/ertseyhan/.atom/packages/omnisharp-atom/node_modules/fastdom/fastdom.js:206:50)
    at flush (/home/ertseyhan/.atom/packages/omnisharp-atom/node_modules/fastdom/fastdom.js:181:5)
```

### Commands

```
     -3:03.6.0 editor:select-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -3:02.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:00.8.0 editor:select-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -2:57.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:56.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:37.4.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:36.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:08.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:08.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:07.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:29.1.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:29 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:27.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.2.0 autocomplete-plus:confirm (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:05.2.0 autocomplete-plus:activate (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:04.8.0 core:backspace (atom-text-editor.editor.omnisharp-editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "dark-flat-ui",
      "outlander-syntax"
    ]
  },
  "omnisharp-atom": {
    "enhancedHighlighting": true
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
autoclose-html, v0.19.0
color-picker, v2.0.14
dark-flat-ui, v1.2.4
git-diff-details, v0.21.0
highlight-selected, v0.11.1
json-schema, v0.1.15
language-d, v3.2.2
linter, v1.11.3
markdown-preview-plus, v2.2.2
minimap, v4.19.0
minimap-codeglance, v0.4.5
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
minimap-split-diff, v0.3.0
omnisharp-atom, v0.26.8
open-recent, v4.0.1
outlander-syntax, v1.1.0
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
I believe I've solved this one, jquery is back in there!
