### ISSUE TITLE
Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by leocamello** [OmniSharp/omnisharp-atom#620]
Just clicked the omnisharp icon in the status bar

**Atom Version**: 1.4.0
**System**: Windows 10 Version
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.26.9

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At C:\Users\Leonardo\.atom\packages\omnisharp-atom\lib\atom\solution-information.js:113

TypeError: Cannot read property 'remove' of undefined
    at [object Object].action (C:\Users\Leonardo\.atom\packages\omnisharp-atom\lib\atom\solution-information.js:113:32)
    at [object Object].Disposable.dispose (C:\Users\Leonardo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:683:12)
    at [object Object].CompositeDisposablePrototype.dispose (C:\Users\Leonardo\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:666:31)
    at atom-workspace.<anonymous> (C:\Users\Leonardo\.atom\packages\omnisharp-atom\lib\atom\solution-information.js:47:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:160:19)
    at omnisharp-status-bar.toggleSolutionInformation (C:\Users\Leonardo\.atom\packages\omnisharp-atom\lib\views\status-bar-view.js:495:27)
    at omnisharp-project-count.projectCount.onclick (C:\Users\Leonardo\.atom\packages\omnisharp-atom\lib\views\status-bar-view.js:359:32)
```

### Commands

```
     -0:58.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:56.8.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:56.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:55.1.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:55.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:53 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:49.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:48.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:48.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:46.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:46 core:backspace (atom-text-editor.editor.is-focused)
     -0:44.7.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
  3x -0:39.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:38.2.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:07.3.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:06.2.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "projectHome": "C:\\Users\\Leonardo\\Documents\\GitHub"
  },
  "omnisharp-atom": {
    "autoAddExternalProjects": true,
    "autoAdjustTreeView": true,
    "developerMode": true,
    "enhancedHighlighting": true,
    "showDiagnosticsForAllSolutions": true,
    "useAdvancedFileNew": true,
    "useLeftLabelColumnForSuggestions": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.21
atom-yeoman, v0.3.15
json-schema, v0.1.15
language-lua, v0.9.4
language-powershell, v2.1.0
linter, v1.11.3
linter-flake8, v1.9.3
markdown-writer, v2.2.0
omnisharp-atom, v0.26.9

# Dev
No dev packages
```

**Comment by Tom1206** [comment]
+1 same problem
