### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by Stephn-R** [OmniSharp/omnisharp-atom#626]
1. Opened Atom with C# project from command line

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.2
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.26.9
### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of undefined

```
At /Users/strodrig/.atom/packages/omnisharp-atom/lib/atom/solution-information.js:113

TypeError: Cannot read property 'remove' of undefined
    at [object Object].action (/Users/strodrig/.atom/packages/omnisharp-atom/lib/atom/solution-information.js:113:32)
    at [object Object].Disposable.dispose (/Users/strodrig/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:683:12)
    at [object Object].CompositeDisposablePrototype.dispose (/Users/strodrig/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:666:31)
    at atom-workspace.<anonymous> (/Users/strodrig/.atom/packages/omnisharp-atom/lib/atom/solution-information.js:47:42)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at omnisharp-status-bar.toggleSolutionInformation (/Users/strodrig/.atom/packages/omnisharp-atom/lib/views/status-bar-view.js:495:27)
    at omnisharp-project-count.projectCount.onclick (/Users/strodrig/.atom/packages/omnisharp-atom/lib/views/status-bar-view.js:359:32)
```
### Commands

```
     -0:31.6.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-oceanic-next.theme-isotope-ui)
  2x -0:25.4.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-oceanic-next.theme-isotope-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "isotope-ui",
      "oceanic-next"
    ]
  },
  "omnisharp-atom": {
    "enhancedHighlighting": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-yeoman, v0.3.15
isotope-ui, v2.7.1
json-schema, v0.1.15
linter, v1.11.3
linter-cppcheck, v0.1.1
linter-pep8, v1.2.1
linter-sass-lint, v1.0.2
linter-tidy, v2.1.0
minimap, v4.19.0
oceanic-next, v0.1.2
omnisharp-atom, v0.26.9
pigments, v0.21.0

# Dev
No dev packages
```

**Comment by AStoker** [comment]
Same issue on my machine, FYI.

**Comment by paulopez78** [comment]
+1

**Comment by david-driscoll** [comment]
Has this happened to anyone lately?

**Comment by paulopez78** [comment]
I haven't got that problem again, for me it works again after updating both atom and omnisharp.
Thanks!
