### ISSUE TITLE
Uncaught TypeError: value.activate is not a function

### ISSUE THREAD

**Issue by woutervs** [OmniSharp/omnisharp-atom#628]
[Enter steps to reproduce below:]
1. Open Atom with omnisharp package
2. Instant crash since latest update.

**Atom Version**: 1.4.1
**System**: Microsoft Windows 10 Pro
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.26.9
### Stack Trace

Uncaught TypeError: value.activate is not a function

```
At C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:77

TypeError: value.activate is not a function
    at C:\Users\Wouter\.atom\packages\omnisharp-atom\lib\omnisharp-atom.js:311:35
    at Config.module.exports.Config.observeKeyPath (C:\Users\Wouter\AppData\Local\atom\app-1.4.1\resources\app.asar\src\config.js:604:7)
    at Config.module.exports.Config.observe (C:\Users\Wouter\AppData\Local\atom\app-1.4.1\resources\app.asar\src\config.js:141:21)
    at C:\Users\Wouter\.atom\packages\omnisharp-atom\lib\omnisharp-atom.js:290:55
    at OmniSharpAtom.activateFeature (C:\Users\Wouter\.atom\packages\omnisharp-atom\lib\omnisharp-atom.js:333:19)
    at Object.activate (C:\Users\Wouter\.atom\packages\omnisharp-atom\lib\omnisharp-atom.js:234:55)
    at C:\Users\Wouter\.atom\packages\omnisharp-atom\lib\omnisharp-atom.js:263:26
    at tryCatcher (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at InnerObserver.next (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5272:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1752:31)
    at InnerObserver.tryCatcher (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5747:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1752:31)
    at InnerObserver.next (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:3577:65)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1752:31)
    at InnerObserver.tryCatcher (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5747:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1752:31)
    at loopRecursive (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:2661:11)
    at [object Object].scheduleWork [as action] (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:985:11)
    at [object Object].ScheduledItem.invokeCore (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:896:33)
    at [object Object].ScheduledItem.invoke (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:884:40)
    at runTrampoline (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1125:37)
    at tryCatcher (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at CurrentThreadScheduler.schedule (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1141:45)
    at FromObservable.Rx.ObservableBase.ObservableBase._subscribe (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:2085:32)
    at FromObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:2024:19)
    at MergeObserver.handleSubscribe (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:3555:28)
    at MergeObserver.next (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:3561:14)
    at MergeObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1752:31)
    at MergeObserver.tryCatcher (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5747:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1752:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:2135:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1752:31)
    at InnerObserver.tryCatcher (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5747:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1752:31)
    at InnerObserver.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:2536:62)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at InnerObserver.tryCatcher (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5761:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at MergeObserver.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:3567:106)
    at MergeObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at MergeObserver.tryCatcher (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5761:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:2140:61)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at InnerObserver.tryCatcher (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5761:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at InnerObserver.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5631:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at InnerObserver.tryCatcher (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5761:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at InnerObserver.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5282:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at InnerObserver.tryCatcher (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5761:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at InnerObserver.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5631:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at InnerObserver.tryCatcher (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5761:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at InnerObserver.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:3800:71)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at InnerObserver.tryCatcher (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5761:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at InnerObserver.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5282:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at InnerObserver.tryCatcher (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.completed (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5761:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:1772:14)
    at AsyncSubject.Rx.AsyncSubject.addProperties.onCompleted (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.js:5950:17)
    at handler (C:\Users\Wouter\.atom\packages\omnisharp-atom\node_modules\rx\dist\rx.async.js:341:7)
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -0:52.5.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:44.2.0 autocomplete-plus:confirm (atom-text-editor.editor.omnisharp-editor.is-focused)
  4x -0:44.2.0 autocomplete-plus:activate (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:41.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.omnisharp-editor.is-focused)
  2x -0:41.2.0 core:backspace (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:40 core:save (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:33.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.omnisharp-editor)
  2x -0:33.3.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:32 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:31.8.0 core:backspace (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:31.6.0 core:save (atom-text-editor.editor.is-focused.omnisharp-editor)
     -0:17.3.0 omnisharp-atom:settings (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {},
  "omnisharp-atom": {
    "codeLens": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-yeoman, v0.3.15
json-schema, v0.1.15
language-csharp, v0.11.0
linter, v1.11.3
omnisharp-atom, v0.26.9

# Dev
No dev packages
```

**Comment by spboyer** [comment]
+1

**Comment by Danielhu229** [comment]
I meet the same problem

**Comment by paulopez78** [comment]
+1

**Comment by Maloric** [comment]
+1, except that mine doesn't happen on startup, but when I check the first setting in Omnisharp settings.  I'm guessing it shouldn't have a label of "undefined":

![image](https://cloud.githubusercontent.com/assets/6311802/13109123/4e7f0e5c-d56f-11e5-9894-97393f6842ac.png)

**Atom Version**: 1.5.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.26.11


### Stack Trace

Uncaught TypeError: value.activate is not a function

```
At C:\Users\Jamie Morris\.atom\packages\omnisharp-atom\lib\omnisharp-atom.js:305

TypeError: value.activate is not a function
    at C:\Users\Jamie Morris\.atom\packages\omnisharp-atom\lib\omnisharp-atom.js:305:35
    at C:\Users\Jamie Morris\AppData\Local\atom\app-1.5.3\resources\app.asar\src\config.js:614:16
    at C:\Users\Jamie Morris\AppData\Local\atom\app-1.5.3\resources\app.asar\src\config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Jamie Morris\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Jamie Morris\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\Jamie Morris\AppData\Local\atom\app-1.5.3\resources\app.asar\src\config.js:816:29)
    at Config.module.exports.Config.setRawValue (C:\Users\Jamie Morris\AppData\Local\atom\app-1.5.3\resources\app.asar\src\config.js:608:19)
    at Config.module.exports.Config.set (C:\Users\Jamie Morris\AppData\Local\atom\app-1.5.3\resources\app.asar\src\config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (C:\Users\Jamie Morris\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:196:28)
    at setNewValue (C:\Users\Jamie Morris\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:138:28)
    at HTMLInputElement.<anonymous> (C:\Users\Jamie Morris\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:144:22)
    at HTMLInputElement.jQuery.event.dispatch (C:\Users\Jamie Morris\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (C:\Users\Jamie Morris\AppData\Local\atom\app-1.5.3\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
  2x -5:05.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:05.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:05.3.0 settings-view:view-installed-packages (atom-text-editor.editor.omnisharp-editor)
  2x -4:58.9.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -4:47.8.0 core:backspace (atom-text-editor.editor.omnisharp-editor.is-focused)
     -4:46.5.0 autocomplete-plus:confirm (atom-text-editor.editor.omnisharp-editor.is-focused)
     -4:46.5.0 autocomplete-plus:activate (atom-text-editor.editor.omnisharp-editor.is-focused)
     -2:51.6.0 go-to-line:toggle (atom-text-editor.editor.omnisharp-editor)
  2x -2:48.8.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:30.4.0 omnisharp-atom:settings (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  7x -1:01.4.0 core:backspace (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:58.4.0 autocomplete-plus:confirm (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:58.4.0 autocomplete-plus:activate (atom-text-editor.editor.omnisharp-editor.is-focused)
  2x -0:49.7.0 core:backspace (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:49.3.0 autocomplete-plus:confirm (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:49.2.0 autocomplete-plus:activate (atom-text-editor.editor.omnisharp-editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "project-manager",
      "terminal-plus"
    ]
  },
  "omnisharp-atom": {
    "topMenu": false
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
clipboard-plus, v0.5.1
emmet, v2.4.1
file-icons, v1.6.14
git-log, v0.4.1
grunt-runner, v0.13.6
highlight-selected, v0.11.2
jshint, v1.8.3
json-schema, v0.1.15
linter, v1.11.3
minimap, v4.19.0
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
omnisharp-atom, v0.26.11
pigments, v0.24.0
symbols-tree-view, v0.11.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by rlauer** [comment]
+1 - Same issue happening on Ubuntu 14.04 with omnisharp-atom v0.28.0.

**Comment by fsacer** [comment]
+1

**Comment by ladace** [comment]
+1

System: OSX 10.11.5

**Comment by justice3120** [comment]
+1

**Comment by RCDane** [comment]
+1

**Comment by woutervs** [comment]
Issue from 2016 closing
