### ISSUE TITLE
Uncaught TypeError: pane.getPath is not a function

### ISSUE THREAD

**Issue by GarethLowe** [OmniSharp/omnisharp-atom#640]
### Steps to reproduce
1. Have the browser-plus package installed and running in a pane
2. Click to focus on the browser-plus pane and omnisharp-atom throws the error

**Atom Version**: 1.4.3
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.26.11

### Stack Trace

Uncaught TypeError: pane.getPath is not a function

```
At C:\Users\loweg\.atom\packages\omnisharp-atom\lib\server\omni.js:112

TypeError: pane.getPath is not a function
    at C:\Users\loweg\.atom\packages\omnisharp-atom\lib\server\omni.js:112:61
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\loweg\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\loweg\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\loweg\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane-container.js:333:27
    at Pane.module.exports.Pane.observeActiveItem (C:\Users\loweg\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane.js:196:7)
    at C:\Users\loweg\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane-container.js:331:42
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\loweg\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\loweg\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.setActivePane (C:\Users\loweg\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane-container.js:196:22)
    at Pane.module.exports.Pane.activate (C:\Users\loweg\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane.js:623:15)
    at Pane.module.exports.Pane.focus (C:\Users\loweg\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane.js:207:21)
    at atom-pane.<anonymous> (C:\Users\loweg\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane-element.js:50:23)
```

### Commands

```
     -8:27 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:38.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -7:36.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -7:36.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:36.6.0 browser-plus:open (atom-text-editor.editor)
     -0:10.6.0 fuzzy-finder:toggle-file-finder (atom-pane.pane)
  6x -0:08.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:07.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:07.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:06.9.0 command-palette:toggle (atom-pane.pane)
     -0:05.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
  2x -0:05.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
browser-plus, v0.0.54
json-schema, v0.1.15
language-haskell, v1.5.2
linter, v1.11.3
omnisharp-atom, v0.26.11
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
publishing fix now :)
