### ISSUE TITLE
Cannot upgrade to 0.26.11; no-trailing-comma error

### ISSUE THREAD

**Issue by shadowmint** [OmniSharp/omnisharp-atom#657]
This error seems to occur when you install the atom-omnisharp package:

```
/private/var/folders/29/0695l4fj26j64kp4p8vwqq5h0000gn/T/apm-install-dir-116120-5543-rgu91a/node_modules/omnisharp-atom/node_modules/tslint/lib/ruleLoader.js:29
        throw new Error(errorMessage);
              ^
Error: Could not find the following rules specified in the configuration:
no-trailing-comma
```

It appears to be related to some typescript thing?

Full error log:

```
Installing omnisharp-atom@0.26.11 to /Users/doug/.atom/packages ✗

> omnisharp-atom@0.26.11 postinstall /private/var/folders/29/0695l4fj26j64kp4p8vwqq5h0000gn/T/apm-install-dir-116120-5543-rgu91a/node_modules/omnisharp-atom
> gulp npm-postinstall

[12:26:42] Using gulpfile /private/var/folders/29/0695l4fj26j64kp4p8vwqq5h0000gn/T/apm-install-dir-116120-5543-rgu91a/node_modules/omnisharp-atom/gulpfile.js
[12:26:42] Starting 'clean:lib'...
[12:26:42] Starting 'clean:spec'...
[12:26:42] Finished 'clean:lib' after 14 ms
[12:26:42] Finished 'clean:spec' after 12 ms
[12:26:42] Starting 'clean'...
[12:26:42] Finished 'clean' after 3.9 μs
[12:26:42] Starting 'typescript'...

npm WARN deprecated tsd@0.6.5: TSD is deprecated in favor of Typings (https://github.com/typings/typings) - see https://github.com/DefinitelyTyped/tsd/issues/269 for more information
npm WARN engine omnisharp-client@3.3.6: wanted: {"node":">=0.12.0","iojs":">=1.0.0","atom":">=0.194.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN engine escodegen@1.8.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

/private/var/folders/29/0695l4fj26j64kp4p8vwqq5h0000gn/T/apm-install-dir-116120-5543-rgu91a/node_modules/omnisharp-atom/node_modules/tslint/lib/ruleLoader.js:29
        throw new Error(errorMessage);
              ^
Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (/private/var/folders/29/0695l4fj26j64kp4p8vwqq5h0000gn/T/apm-install-dir-116120-5543-rgu91a/node_modules/omnisharp-atom/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/private/var/folders/29/0695l4fj26j64kp4p8vwqq5h0000gn/T/apm-install-dir-116120-5543-rgu91a/node_modules/omnisharp-atom/node_modules/tslint/lib/tslint.js:24:44)
    at /private/var/folders/29/0695l4fj26j64kp4p8vwqq5h0000gn/T/apm-install-dir-116120-5543-rgu91a/node_modules/omnisharp-atom/node_modules/gulp-tslint/index.js:96:34
    at respond (/private/var/folders/29/0695l4fj26j64kp4p8vwqq5h0000gn/T/apm-install-dir-116120-5543-rgu91a/node_modules/omnisharp-atom/node_modules/gulp-tslint/node_modules/rcloader/index.js:73:7)
    at respond (/private/var/folders/29/0695l4fj26j64kp4p8vwqq5h0000gn/T/apm-install-dir-116120-5543-rgu91a/node_modules/omnisharp-atom/node_modules/gulp-tslint/node_modules/rcloader/node_modules/rcfinder/index.js:140:7)
    at /private/var/folders/29/0695l4fj26j64kp4p8vwqq5h0000gn/T/apm-install-dir-116120-5543-rgu91a/node_modules/omnisharp-atom/node_modules/gulp-tslint/node_modules/rcloader/node_modules/rcfinder/index.js:124:17
    at /private/var/folders/29/0695l4fj26j64kp4p8vwqq5h0000gn/T/apm-install-dir-116120-5543-rgu91a/node_modules/omnisharp-atom/node_modules/gulp-tslint/node_modules/rcloader/node_modules/rcfinder/index.js:77:13
    at process._tickCallback (node.js:448:13)
npm ERR! Darwin 15.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/doug/.atom/.apm/.apmrc" "--userconfig" "/Users/doug/.atom/.apmrc" "install" "/private/var/folders/29/0695l4fj26j64kp4p8vwqq5h0000gn/T/d-116120-5543-1ozvijh/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! omnisharp-atom@0.26.11 postinstall: `gulp npm-postinstall`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the omnisharp-atom@0.26.11 postinstall script 'gulp npm-postinstall'.
npm ERR! This is most likely a problem with the omnisharp-atom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp npm-postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls omnisharp-atom
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/29/0695l4fj26j64kp4p8vwqq5h0000gn/T/apm-install-dir-116120-5543-rgu91a/npm-debug.log
```

**Comment by shadowmint** [comment]
NB. I see 0.26.12 on the release list, but `apm` doesn't seem to aware of it.
