### ISSUE TITLE
Failed Omnisharp installation on atom 1.5.3

### ISSUE THREAD

**Issue by lem0nify** [OmniSharp/omnisharp-atom#658]
I have the same problem that guys in this thread: https://github.com/OmniSharp/omnisharp-atom/issues/511

As I can see, they solved their problem theirselves. But difference between me and them is that I don't know how node.js works (and don't want to know). I am just user who wants to use atom with omnisharp to code his C# projects.

Let's start from the beginning. I don't have external node.js installed on my windows pc. I installed Atom with windows installer downloaded from atom.io official site. Then I tryed to install omnisharp-atom package using command line:

> C:\Users\Konstantin>apm install omnisharp-atom
> Installing omnisharp-atom to C:\Users\Konstantin\.atom\packages failed
> 
> > omnisharp-atom@0.26.11 postinstall C:\Users\KONSTA~1\AppData\Local\Temp\apm-in
> stall-dir-116120-6280-154jpxx\node_modules\omnisharp-atom
> > gulp npm-postinstall
> 
> [20:44:45] Using gulpfile C:\Users\KONSTA~1\AppData\Local\Temp\apm-install-dir-1
> 16120-6280-154jpxx\node_modules\omnisharp-atom\gulpfile.js
> [20:44:45] Starting 'clean:lib'...
> [20:44:45] Starting 'clean:spec'...
> [20:44:45] Finished 'clean:lib' after 14 ms
> [20:44:45] Finished 'clean:spec' after 14 ms
> [20:44:45] Starting 'clean'...
> [20:44:45] Finished 'clean' after 3.52 ?s
> [20:44:45] Starting 'typescript'...
> 
> npm WARN deprecated tsd@0.6.5: TSD is deprecated in favor of Typings (https://gi
> thub.com/typings/typings) - see https://github.com/DefinitelyTyped/tsd/issues/26
> 9 for more information
> npm WARN engine omnisharp-client@3.3.6: wanted: {"node":">=0.12.0","iojs":">=1.0
> .0","atom":">=0.194.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
> npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fai
> l on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possibl
> e.
> npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade
>  to lodash@^4.0.0.
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fai
> l on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possibl
> e.
> npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fai
> l on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possibl
> e.
> npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"}
> (current: {"node":"0.10.40","npm":"2.13.3"})
> npm WARN engine escodegen@1.8.0: wanted: {"node":">=0.12.0"} (current: {"node":"
> 0.10.40","npm":"2.13.3"})
> 
> C:\Users\KONSTA~1\AppData\Local\Temp\apm-install-dir-116120-6280-154jpxx\node_mo
> dules\omnisharp-atom\node_modules\tslint\lib\ruleLoader.js:29
>         throw new Error(errorMessage);
>               ^
> Error: Could not find the following rules specified in the configuration:
> no-trailing-comma
>     at Object.loadRules (C:\Users\KONSTA~1\AppData\Local\Temp\apm-install-dir-11
> 6120-6280-154jpxx\node_modules\omnisharp-atom\node_modules\tslint\lib\ruleLoader
> .js:29:15)
>     at Linter.lint (C:\Users\KONSTA~1\AppData\Local\Temp\apm-install-dir-116120-
> 6280-154jpxx\node_modules\omnisharp-atom\node_modules\tslint\lib\tslint.js:24:44
> )
>     at C:\Users\KONSTA~1\AppData\Local\Temp\apm-install-dir-116120-6280-154jpxx\
> node_modules\omnisharp-atom\node_modules\gulp-tslint\index.js:96:34
>     at respond (C:\Users\KONSTA~1\AppData\Local\Temp\apm-install-dir-116120-6280
> -154jpxx\node_modules\omnisharp-atom\node_modules\gulp-tslint\node_modules\rcloa
> der\index.js:73:7)
>     at respond (C:\Users\KONSTA~1\AppData\Local\Temp\apm-install-dir-116120-6280
> -154jpxx\node_modules\omnisharp-atom\node_modules\gulp-tslint\node_modules\rcloa
> der\node_modules\rcfinder\index.js:140:7)
>     at C:\Users\KONSTA~1\AppData\Local\Temp\apm-install-dir-116120-6280-154jpxx\
> node_modules\omnisharp-atom\node_modules\gulp-tslint\node_modules\rcloader\node_
> modules\rcfinder\index.js:124:17
>     at C:\Users\KONSTA~1\AppData\Local\Temp\apm-install-dir-116120-6280-154jpxx\
> node_modules\omnisharp-atom\node_modules\gulp-tslint\node_modules\rcloader\node_
> modules\rcfinder\index.js:77:13
>     at process._tickCallback (node.js:448:13)
> npm ERR! Windows_NT 6.2.9200
> npm ERR! argv "C:\\Users\\Konstantin\\AppData\\Local\\atom\\app-1.5.3\\resources
> \\app\\apm\\bin\\node.exe" "C:\\Users\\Konstantin\\AppData\\Local\\atom\\app-1.5
> .3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C
> :\\Users\\Konstantin\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Konstantin
> \\.atom\\.apmrc" "install" "C:\\Users\\KONSTA~1\\AppData\\Local\\Temp\\d-116120-
> 6280-evii6t\\package.tgz" "--target=0.34.5" "--arch=ia32" "--msvs_version=2013"
> npm ERR! node v0.10.40
> npm ERR! npm  v2.13.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! omnisharp-atom@0.26.11 postinstall: `gulp npm-postinstall`
> npm ERR! Exit status 8
> npm ERR!
> npm ERR! Failed at the omnisharp-atom@0.26.11 postinstall script 'gulp npm-posti
> nstall'.
> npm ERR! This is most likely a problem with the omnisharp-atom package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     gulp npm-postinstall
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls omnisharp-atom
> npm ERR! There is likely additional logging output above.

I am interested in two things:
1) What specifically should I do (step-by-step) to make it work?
2) Issue #511 was closed on 25 Sep 2015. Now it's 20 Feb 2016. So why didn't u fix the bug yet?

**Comment by david-driscoll** [comment]
Iooks like the deprecation for tsd is causing issues, I just ran into it myself with a different machine, fixing shortly...

**Comment by leocamello** [comment]
Hi, I am having the same issue here.

@lem0nify Have you solved it on your machine? Needed to install tslint?

**Comment by lem0nify** [comment]
@leocamello No, I didn't and just continued to use Visual Studio. I don't have enough time now to play with atom and node.

**Comment by ddieppa** [comment]
my **Atom** version is **1.6.0** and today when I opened it, showed me that I had some updates, so I proceed and then got this error:

```
Updating to “omnisharp-atom@0.27.0” failed.Hide output…

npm WARN engine omnisharp-client@4.0.3: wanted: {"node":">=0.12.0","iojs":">=1.0.0","atom":">=0.194.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN engine safefs@4.0.1: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine editions@1.1.1: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine escodegen@1.8.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\ddieppa\\AppData\\Local\\atom\\app-1.6.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\ddieppa\\AppData\\Local\\atom\\app-1.6.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\ddieppa\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\ddieppa\\.atom\\.apmrc" "install" "C:\\Users\\ddieppa\\AppData\\Local\\Temp\\d-116229-17120-zd9x4d\\package.tgz" "--target=0.34.5" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! path C:\Users\ddieppa\.atom\.apm\loose-envify\1.1.0\package\package.json
npm ERR! code EPERM
npm ERR! errno 50

npm ERR! Error: EPERM, rename 'C:\Users\ddieppa\.atom\.apm\loose-envify\1.1.0\package\package.json'
npm ERR!  { [Error: EPERM, rename 'C:\Users\ddieppa\.atom\.apm\loose-envify\1.1.0\package\package.json']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Users\\ddieppa\\.atom\\.apm\\loose-envify\\1.1.0\\package\\package.json',
npm ERR!   parent: 'invariant' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

```

And here are my **node **and **npm **version:

```
$ node -v
v0.12.2
```

```
$ npm -v
3.3.9
```

**Comment by david-driscoll** [comment]
@ddieppa that's a really strange error, can you try from the command line...

```cmd
apm uninstall omnisharp-atom
apm install omnisharp-atom
```

There may also be another issue #699 #700 #701 #702 that I'll be resolving today with #703

**Comment by ddieppa** [comment]
this is what I got now:

[Enter steps to reproduce below:]

1. Just click on update package

**Atom Version**: 1.6.1
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.28.0


### Stack Trace

Uncaught TypeError: Cannot read property 'processes' of undefined

```
At C:\Users\ddieppa\.atom\packages\omnisharp-atom\lib\views\status-bar-view.js:414

TypeError: Cannot read property 'processes' of undefined
    at omnisharp-status-bar.attachedCallback (C:\Users\ddieppa\.atom\packages\omnisharp-atom\lib\views\status-bar-view.js:414:70)
    at status-bar.StatusBarView.addLeftTile (C:\Users\ddieppa\AppData\Local\atom\app-1.6.1\resources\app.asar\node_modules\status-bar\lib\status-bar-view.js:72:22)
    at StatusBar._attach (C:\Users\ddieppa\.atom\packages\omnisharp-atom\lib\atom\status-bar.js:58:39)
    at StatusBar.attach (C:\Users\ddieppa\.atom\packages\omnisharp-atom\lib\atom\status-bar.js:48:22)
    at result (C:\Users\ddieppa\.atom\packages\omnisharp-atom\lib\omnisharp-atom.js:334:40)
    at SafeSubscriber._next (C:\Users\ddieppa\.atom\packages\omnisharp-atom\lib\omnisharp-atom.js:270:24)
    at SafeSubscriber.__tryOrSetError (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:179:16)
    at SafeSubscriber.next (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:121:27)
    at Subscriber._next (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:74:26)
    at Subscriber.next (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:51:18)
    at DoSubscriber._next (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\do.js:45:24)
    at DoSubscriber.Subscriber.next (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:51:18)
    at MergeMapSubscriber.notifyNext (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\mergeMap.js:92:30)
    at InnerSubscriber._next (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\InnerSubscriber.js:18:21)
    at InnerSubscriber.Subscriber.next (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:51:18)
    at Object.subscribeToResult (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\util\subscribeToResult.js:26:25)
    at MergeMapSubscriber._innerSub (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\mergeMap.js:79:38)
    at MergeMapSubscriber._tryNext (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\mergeMap.js:76:14)
    at MergeMapSubscriber._next (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:51:18)
    at DoSubscriber._next (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\do.js:50:30)
    at DoSubscriber.Subscriber.next (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:51:18)
    at ToArraySubscriber._complete (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\toArray.js:35:26)
    at ToArraySubscriber.Subscriber.complete (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:63:18)
    at FilterSubscriber.Subscriber._complete (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:81:26)
    at FilterSubscriber.Subscriber.complete (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:63:18)
    at MapSubscriber.Subscriber._complete (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:81:26)
    at MapSubscriber.Subscriber.complete (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:63:18)
    at MergeMapSubscriber._complete (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\mergeMap.js:84:30)
    at MergeMapSubscriber.Subscriber.complete (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:63:18)
    at ToArraySubscriber._complete (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\toArray.js:36:26)
    at ToArraySubscriber.Subscriber.complete (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:63:18)
    at MergeMapSubscriber._complete (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\mergeMap.js:84:30)
    at MergeMapSubscriber.Subscriber.complete (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:63:18)
    at Notification.observe (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\Notification.js:17:54)
    at FutureAction.DelaySubscriber.dispatch [as work] (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\delay.js:83:40)
    at FutureAction.execute (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\scheduler\FutureAction.js:23:22)
    at AsyncScheduler.QueueScheduler.flush (C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\scheduler\QueueScheduler.js:20:20)
    at C:\Users\ddieppa\.atom\packages\omnisharp-atom\node_modules\rxjs\scheduler\FutureAction.js:88:23
```

### Commands

```
     -9:46 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {},
  "omnisharp-atom": {
    "codeLens": false
  }
}
```

### Installed Packages

```coffee
# User
angular2-snippets, v0.3.0
angularjs, v0.3.4
atom-alignment, v0.12.1
atom-typescript, v8.4.0
atom-yeoman, v0.3.15
autoclose-html, v0.23.0
column-select, v0.2.0
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.6.19
json-schema, v0.1.15
linter, v1.11.4
linter-csslint, v1.3.2
linter-eslint, v7.1.3
linter-htmlhint, v1.1.1
linter-tslint, v0.9.1
omnisharp-atom, v0.28.0

# Dev
No dev packages
```

**Comment by Zireael07** [comment]
@david-driscoll: I tried installing (fresh, first time user) on 1.7.0. and got the exact same error as @ddieppa above.

And before it spit up the error, node almost maxed my CPU nearly freezing things I was doing otherwise.

**Comment by aolba** [comment]
I'm also use apm install omnisharp-atom but get the fail message. This is after trying to install with Atom. Omnisharp just quit working one night. It was complicated to make it work at the begining, and after all the work, it was pointless. I manage to install it with npm (I download the zip file) but then I get the "Uncaught ObjectUnsubscribedError" So I give up. I'm not sure if it was Atom or Omnisharp. I also try with older versions and clean instalations.

**Comment by jruizaranguren** [comment]
Same error when installing `omnisharp-atom 0.29.3` on `atom 1.7.3`
