### ISSUE TITLE
Uncaught TypeError: Cannot read property 'temp' of null

### ISSUE THREAD

**Issue by vypr** [OmniSharp/omnisharp-atom#663]
I had just created a normal ConsoleApplication project and this occurred.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.4
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.26.13

### Stack Trace

Uncaught TypeError: Cannot read property 'temp' of null

```
At /Users/elliott/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:77

TypeError: Cannot read property 'temp' of null
    at SolutionInstanceManager._setupEditorWithContext (/Users/elliott/.atom/packages/omnisharp-atom/lib/server/solution-manager.js:321:46)
    at SolutionInstanceManager._getSolutionForEditor (/Users/elliott/.atom/packages/omnisharp-atom/lib/server/solution-manager.js:370:22)
    at SolutionInstanceManager.getSolutionForEditor (/Users/elliott/.atom/packages/omnisharp-atom/lib/server/solution-manager.js:302:25)
    at OmniManager.request (/Users/elliott/.atom/packages/omnisharp-atom/lib/server/omni.js:336:67)
    at CodeLens.updateCodeLens (/Users/elliott/.atom/packages/omnisharp-atom/lib/features/code-lens.js:129:31)
    at /Users/elliott/.atom/packages/omnisharp-atom/lib/features/code-lens.js:69:34
    at tryCatcher (/Users/elliott/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/Users/elliott/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2130:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/elliott/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1752:31)
    at InnerObserver.tryCatcher (/Users/elliott/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/Users/elliott/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5864:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/elliott/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1752:31)
    at /Users/elliott/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.time.js:366:55
    at schedule (/Users/elliott/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1312:53)
```

### Commands

```
  2x -1:56.1.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-light-syntax.theme-one-light-ui)
     -1:43.2.0 core:close (atom-text-editor.editor.omnisharp-editor.is-focused)
     -1:43.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-light-syntax.theme-one-light-ui)
     -1:42.5.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:42.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-light-syntax.theme-one-light-ui)
     -1:37.9.0 tree-view:remove (li.file.entry.list-item.selected)
     -1:28.2.0 omnisharp-atom:new-project (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:21.2.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-light-syntax.theme-one-light-ui)
  2x -1:21.2.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-light-syntax.theme-one-light-ui)
     -1:15 omnisharp-atom:new-project (atom-text-editor.editor.mini)
     -1:08.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:08.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:06.6.0 omnisharp-atom:new-project (atom-pane.pane.active)
     -0:53.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:53.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-light-syntax.theme-one-light-ui)
     -0:51.7.0 omnisharp-atom:restart-server (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-light-syntax.theme-one-light-ui)
```

### Config

```json
{
  "core": {
    "followSymlinks": false,
    "projectHome": "/Users/elliott/Desktop/code",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Parinfer, v1.14.0
atom-dlang, v1.1.2
atom-jade, v0.3.0
atom-ternjs, v0.13.2
atom-yeoman, v0.3.15
autocomplete-bibtex, v0.6.2
autocomplete-cmake, v0.3.1
autocomplete-ctags, v0.4.0
autocomplete-emojis, v2.2.2
autocomplete-glsl, v0.2.3
autocomplete-go, v0.2.0
autocomplete-love, v0.2.0
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-python, v1.6.1
autocomplete-ruby, v0.1.0
color-picker, v2.1.1
environment, v1.1.1
esformatter, v1.22.0
file-icons, v1.6.16
go-config, v0.3.3
go-get, v0.1.1
gpp-compiler, v2.0.2
haskell-pointfree, v0.1.3
hyperclick, v0.0.35
hyperclick-love, v0.2.0
javascript-snippets, v1.2.1
json-schema, v0.1.15
language-arm, v1.2.2
language-brainfuck, v0.2.0
language-cpp14, v0.6.0
language-dots, v0.0.4
language-glsl, v2.0.1
language-haskell, v1.7.0
language-javascript-better, v1.7.1
language-lua, v0.9.4
language-rust, v0.4.6
language-scheme, v1.4.0
language-x86, v0.1.0
linter, v1.11.3
linter-cpplint, v1.0.1
linter-gcc, v0.6.8
linter-golinter, v1.2.0
linter-lua, v1.0.1
linter-luaparse, v0.2.0
linter-ruby, v1.2.2
linter-rust, v0.4.1
love-ide, v0.8.0
minimap, v4.19.0
omnisharp-atom, v0.26.13
pigments, v0.24.1
python-tools, v0.6.7
racer, v0.18.0
ruby-block, v0.3.5
run-in-terminal, v0.6.0
rust-api-docs-helper, v0.5.1
synced-sidebar, v0.4.3
terminal-panel, v1.14.1
tool-bar, v0.2.1
tool-bar-main, v0.0.9
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by gonzamvita** [comment]
Hello Vypr,

Did you find any solution for that? Trying right now, in MacOSX aswell and I'm getting the same issue.

Regards.

**Comment by vypr** [comment]
I didn't, it's something that has to be fixed in the code.

**Comment by david-driscoll** [comment]
I'm working on some stuff tonight, I'll see if I can find the source.
