### ISSUE TITLE
Uncaught TypeError: Cannot read property 'solution' of null

### ISSUE THREAD

**Issue by nicka101** [OmniSharp/omnisharp-atom#682]
[Enter steps to reproduce below:]

1. Upgrade to 0.26.14
2. Error thrown, no other actions taken

**Atom Version**: 1.5.4
**System**: Ubuntu 15.10
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.26.14

### Stack Trace

Uncaught TypeError: Cannot read property 'solution' of null

```
At /home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:77

TypeError: Cannot read property 'solution' of null
    at /home/nicka101/.atom/packages/omnisharp-atom/lib/server/omni.js:61:36
    at tryCatcher (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2130:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1752:31)
    at InnerObserver.tryCatcher (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:5864:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1752:31)
    at /home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1893:71
    at tryCatcher (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
    at scheduleMethod (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1918:31)
    at [object Object].invokeRecImmediate [as action] (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:967:7)
    at [object Object].ScheduledItem.invokeCore (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:896:33)
    at [object Object].ScheduledItem.invoke (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:884:40)
    at runTrampoline (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1125:37)
    at tryCatcher (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:63:31)
    at CurrentThreadScheduler.schedule (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:1141:45)
    at FilterObservable.Rx.ObservableBase.ObservableBase._subscribe (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2085:32)
    at FilterObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/home/nicka101/.atom/packages/omnisharp-atom/node_modules/rx/dist/rx.js:2024:19)
    at FrameworkSelector._attach (/home/nicka101/.atom/packages/omnisharp-atom/lib/atom/framework-selector.js:84:16)
    at FrameworkSelector.setup (/home/nicka101/.atom/packages/omnisharp-atom/lib/atom/framework-selector.js:38:22)
    at OmniSharpAtom.consumeStatusBar (/home/nicka101/.atom/packages/omnisharp-atom/lib/omnisharp-atom.js:397:33)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
     -4:24.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-gcc"
    ]
  },
  "omnisharp-atom": {
    "ExcludeClassifications": false,
    "altGotoDefinition": true,
    "enhancedHighlighting": true
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
autocomplete-clang, v0.8.9
autocomplete-cmake, v0.3.1
build-tools, v4.3.4
json-schema, v0.1.15
language-cmake, v0.1.4
linter, v1.11.3
omnisharp-atom, v0.26.14

# Dev
No dev packages
```

**Comment by skmelendez** [comment]
Has there been any movement on this issue? I am experiencing it with v0.29.4. Here is my stack trace:

Uncaught TypeError: Cannot read property 'config' of null
/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/QueueScheduler.js:24
Hide Stack Trace
TypeError: Cannot read property 'config' of null
    at /home/smelendez/.atom/packages/omnisharp-atom/lib/server/omni.js:88:36
    at FilterSubscriber._next (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/filter.js:81:37)
    at FilterSubscriber.Subscriber.next (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at MergeAllSubscriber.OuterSubscriber.notifyNext (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/OuterSubscriber.js:19:26)
    at InnerSubscriber._next (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at DeferSubscriber.OuterSubscriber.notifyNext (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/OuterSubscriber.js:19:26)
    at InnerSubscriber._next (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at IteratorObservable._subscribe (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/observable/IteratorObservable.js:98:32)
    at IteratorObservable.Observable.subscribe (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/Observable.js:56:27)
    at Object.subscribeToResult (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/util/subscribeToResult.js:21:27)
    at DeferSubscriber._callFactory (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/observable/DeferObservable.js:88:42)
    at DeferSubscriber.tryDefer (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/observable/DeferObservable.js:79:18)
    at new DeferSubscriber (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/observable/DeferObservable.js:75:14)
    at DeferObservable._subscribe (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/observable/DeferObservable.js:65:16)
    at DeferObservable.Observable.subscribe (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/Observable.js:56:27)
    at Object.subscribeToResult (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/util/subscribeToResult.js:21:27)
    at MergeAllSubscriber._next (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/mergeAll.js:85:42)
    at MergeAllSubscriber.Subscriber.next (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at ArrayObservable._subscribe (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/observable/ArrayObservable.js:114:28)
    at ArrayObservable.Observable.subscribe (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/Observable.js:56:27)
    at Observable._subscribe (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/Observable.js:114:28)
    at MergeAllOperator.call (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/mergeAll.js:63:23)
    at Observable.subscribe (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/Observable.js:53:22)
    at Observable._subscribe (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/Observable.js:114:28)
    at FilterOperator.call (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/filter.js:58:23)
    at Observable.subscribe (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/Observable.js:53:22)
    at FutureAction.SubscribeOnObservable.dispatch (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/observable/SubscribeOnObservable.js:38:23)
    at FutureAction.execute (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/FutureAction.js:28:22)
    at AsyncScheduler.QueueScheduler.flush (/home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/QueueScheduler.js:21:20)
    at /home/smelendez/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/FutureAction.js:93:23

**Comment by Yantrio** [comment]
I'm getting this too :(

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.4
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.29.4


### Stack Trace

Uncaught TypeError: Cannot read property 'solution' of null

```
At /Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/QueueScheduler.js:24

TypeError: Cannot read property 'solution' of null
    at SwitchMapSubscriber.project (/Users/james/.atom/packages/omnisharp-atom/lib/server/omni.js:67:36)
    at SwitchMapSubscriber._next (/Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/switchMap.js:87:27)
    at SwitchMapSubscriber.Subscriber.next (/Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at FilterSubscriber._next (/Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/filter.js:88:30)
    at FilterSubscriber.Subscriber.next (/Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at RefCountSubscriber.Subscriber._next (/Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at RefCountSubscriber.Subscriber.next (/Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at ReplaySubject.Subject.next (/Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/Subject.js:55:25)
    at ReplaySubject.next (/Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/ReplaySubject.js:28:31)
    at ConnectableSubscriber.Subscriber._next (/Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at ConnectableSubscriber.Subscriber.next (/Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at DebounceTimeSubscriber.debouncedNext (/Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/debounceTime.js:98:30)
    at FutureAction.dispatchNext (/Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/debounceTime.js:114:16)
    at FutureAction.execute (/Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/FutureAction.js:28:22)
    at AsyncScheduler.QueueScheduler.flush (/Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/QueueScheduler.js:21:20)
    at /Users/james/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/FutureAction.js:93:23
```

### Commands

```
     -2:55.5.0 core:cancel (atom-text-editor.editor.omnisharp-editor.is-focused)
  2x -1:38.5.0 core:backspace (atom-text-editor.editor.omnisharp-editor.is-focused)
     -1:37.9.0 core:save (atom-text-editor.editor.omnisharp-editor.is-focused)
     -1:37.7.0 editor:consolidate-selections (atom-text-editor.editor.omnisharp-editor.is-focused)
     -1:37.7.0 core:cancel (atom-text-editor.editor.omnisharp-editor.is-focused)
     -1:36.6.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.use-animations.theme-gruvbox.theme-atom-material-ui)
  3x -1:17.6.0 omnisharp-atom:settings (atom-workspace.workspace.scrollbars-visible-always.use-animations.theme-gruvbox.theme-atom-material-ui)
     -1:11.9.0 command-palette:toggle (div.package-detail.panels-item)
     -1:06.6.0 omnisharp-atom:restart-server (div.package-detail.panels-item)
     -0:22.3.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -0:22.3.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:15.7.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.use-animations.theme-gruvbox.theme-atom-material-ui)
     -0:13 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:09.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:07.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.6.0 omnisharp-atom:restart-server (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "followSymlinks": false,
    "themes": [
      "atom-material-ui",
      "gruvbox"
    ]
  },
  "omnisharp-atom": {
    "altGotoDefinition": true,
    "enableAdvancedFileNew": true,
    "enhancedHighlighting": true,
    "showDiagnosticsForAllSolutions": true,
    "showHiddenDiagnostics": false,
    "signatureHelp": true,
    "useAdvancedFileNew": true,
    "useLeftLabelColumnForSuggestions": true,
    "wantMetadata": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
atom-material-ui, v1.2.13
atom-ternjs, v0.14.1
atom-yeoman, v0.3.15
autocomplete-go, v1.1.0
builder-go, v1.0.0
editorconfig, v1.4.1
environment, v1.2.0
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
gruvbox, v1.0.5
ionide-fake, v1.2.2
ionide-fsharp, v1.9.1
ionide-fsi, v2.0.1
ionide-installer, v1.3.0
ionide-paket, v2.2.6
ionide-webview, v1.0.3
ionide-yeoman, v1.0.2
json-schema, v0.1.15
language-docker, v1.1.6
language-javascript-jsx, v0.3.7
linter, v1.11.4
markdown-preview-plus, v2.4.0
markdown-writer, v2.3.3
navigator-godef, v1.0.3
omnisharp-atom, v0.29.4
project-manager, v2.9.7
react, v0.15.0
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by david-driscoll** [comment]
What kind of actions are you doing when this happens?  I'll try and dig into it this weekend.

I should also have more time to work on things, as I won't be working 2 jobs for much longer.

**Comment by Yantrio** [comment]
I opened a cs file in atom. that's it.

**Comment by skmelendez** [comment]
Same here. Just opened a cs file.

**Comment by nicka101** [comment]
Indeed, as the others have stated, I too was just opening a cs file
