### ISSUE TITLE
Failed to load the omnisharp-atom package: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by lngr** [OmniSharp/omnisharp-atom#722]
The following error happens on a fresh install of omnisharp-atom on Mac OS X:

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.2
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.28.0

### Stack Trace

Failed to load the omnisharp-atom package

```
At Super expression must either be null or a function, not undefined

TypeError: Super expression must either be null or a function, not undefined
  at _inherits (/Users/alex/.atom/packages/omnisharp-atom/lib/server/solution.js:28:113)
  at /Users/alex/.atom/packages/omnisharp-atom/lib/server/solution.js:31:5
  at Object.<anonymous> (/Users/alex/.atom/packages/omnisharp-atom/lib/server/solution.js:176:2)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/alex/.atom/packages/omnisharp-atom/lib/server/solution-manager.js:24:18)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/alex/.atom/packages/omnisharp-atom/lib/server/omni.js:14:24)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/alex/.atom/packages/omnisharp-atom/lib/omnisharp-atom.js:21:13)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.3.0
docblockr, v0.7.3
editorconfig, v1.2.4
file-icons, v1.6.18
language-jade, v0.6.3
linter, v1.11.3
omnisharp-atom, v0.28.0
project-manager, v2.7.6
vim-mode, v0.65.0
vim-mode-visual-block, v0.2.15
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by Murriouz** [comment]
Same here

**Comment by Cr4ck3rs** [comment]
I'm having the same issue, although it is a different error (Atom still tells me this is the issue I should check so I'll copy the error I'm having)

**Atom Version**: 1.7.3
**System**: Unknown Windows Version (It's Windows 7)
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.29.3


### Stack Trace

Failed to load the omnisharp-atom package

```
At Cannot find module './add/operator/windowCount'

Error: Cannot find module './add/operator/windowCount'
  at Module._resolveFilename (module.js:338:15)
  at Function.Module._resolveFilename (C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:289:25)
  at Module.require (module.js:366:17)
  at require (C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
  at Object.<anonymous> (C:\Users\jaguero\.atom\packages\omnisharp-atom\node_modules\rxjs\Rx.js:112:1)
  at Module._compile (C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
  at Object.<anonymous> (C:\Users\jaguero\.atom\packages\omnisharp-atom\lib\omnisharp-atom.js:9:13)
  at Module._compile (C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:715:27)
  at C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:117:28
  at Package.module.exports.Package.measure (C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:92:15)
  at Package.module.exports.Package.load (C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:457:14)
  at C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:402:19
  at Config.module.exports.Config.transact (C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:397:19)
  at C:\Users\jaguero\AppData\Local\atom\app-1.7.3\resources\app.asar\src\atom-environment.js:743:28

```

### Commands

```
     -0:34.9.0 atom-terminal-panel:toggle-autocompletion (div.panels)
     -0:34.9.0 settings-view:open (div.panels)
  2x -0:11.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:09.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
angularjs, v0.3.4
atom-jasmine, v0.8.1
atom-react-native-autocomplete, v0.0.24
atom-terminal-panel, v4.4.4
atom-tfs-auto, v0.2.0
autoclose-html, v0.23.0
autocomplete-html-entities, v0.1.0
autocomplete-js-import, v1.0.1
autocomplete-json, v1.9.1
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.2
clipboard-plus, v0.5.1
docblock-format-helper, v0.3.0
docblockr, v0.7.3
easy-motion-redux, v1.1.0
emmet, v2.4.3
file-icons, v1.7.8
fold-functions, v0.4.3
git-diff-details, v1.3.0
git-log, v0.4.1
glowing-cursor, v0.1.1
highlight-selected, v0.11.2
imdone-atom, v1.3.29
javascript-snippets, v1.2.1
language-asp-html, v0.2.0
language-aspx, v0.4.0
language-cshtml, v0.1.1
language-gitignore, v0.2.0
language-javascript-jsx, v0.3.7
language-vb, v0.1.0-pre1
less-than-slash, v0.13.0
linter, v1.11.4
linter-coffeelint, v1.1.2
linter-csslint, v1.3.2
linter-eslint, v7.2.2
linter-htmlhint, v1.1.4
linter-jshint, v2.1.0
linter-markdown, v1.5.0
linter-pylint, v1.2.0
linter-sass-lint, v1.4.2
merge-conflicts, v1.4.2
minimap, v4.23.2
minimap-bookmarks, v0.3.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.0
minimap-selection, v4.4.0
neon-selection, v0.3.2
omnisharp-atom, v0.29.3
open-recent, v5.0.0
pigments, v0.26.0
regex-railroad-diagram, v0.7.4
rest-client, v1.1.0
save-session, v0.15.7
tree-view-git-status, v0.2.3

# Dev
No dev packages
```

**Comment by Cr4ck3rs** [comment]
Also when running apm install from the omnisharp package folder I get this:

Installing modules failed
> omnisharp-atom@0.29.3 postinstall C:\Users\jaguero\.atom\packages\omnisharp-at
om
> gulp npm-postinstall


npm WARN package.json Dependency 'babel-plugin-transform-es2015-modules-commonjs
' exists in both dependencies and devDependencies, using 'babel-plugin-transform
-es2015-modules-commonjs@^6.3.13' from dependencies
npm WARN package.json Dependency 'babel-preset-es2015' exists in both dependenci
es and devDependencies, using 'babel-preset-es2015@^6.3.13' from dependencies
npm WARN package.json Dependency 'babel-preset-stage-3' exists in both dependenc
ies and devDependencies, using 'babel-preset-stage-3@^6.3.13' from dependencies

module.js:340
    throw err;
          ^
Error: Cannot find module 'escape-string-regexp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\jaguero\.atom\packages\omnisharp-atom\node_m
odules\gulp-util\node_modules\chalk\index.js:2:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\jaguero\\AppData\\Local\\atom\\app-0.200.0\\resources\
\app\\apm\\bin\\\\node.exe" "C:\\Users\\jaguero\\AppData\\Local\\atom\\app-0.200
.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C
:\\Users\\jaguero\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\jaguero\\.ato
m\\.apmrc" "install" "--target=0.22.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! omnisharp-atom@0.29.3 postinstall: `gulp npm-postinstall`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the omnisharp-atom@0.29.3 postinstall script 'gulp npm-postin
stall'.
npm ERR! This is most likely a problem with the omnisharp-atom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp npm-postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls omnisharp-atom
npm ERR! There is likely additional logging output above.

**Comment by Cr4ck3rs** [comment]
By the way, I managed to get it working.

1.- I uninstalled OmniSharp
2.- Installed latest version of node.js
3.- Install via apm -> apm install omnisharp-atom
4.- It failed at installing 2 dependencies (atom-json-schema and atom-yeoman)
Installed them via package installer in settings.
5.- Omnisharp is working, yay

**Comment by asbjornu** [comment]
This just happened to me too. I've never seen it before, though, so it's not a recurring problem. Atom version 1.8.0 with `omnisharp-atom` version 0.30.4 on OS X 10.11.5.

**Comment by zzm2q** [comment]
same here.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.30.4


### Stack Trace

Failed to load the omnisharp-atom package

```
At /Users/mifunstudio/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/node_modules/strip-bom/index.js:2
module.exports = x => {
                   ^^
Unexpected token =>

/Users/mifunstudio/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/node_modules/strip-bom/index.js:2
module.exports = x => {
                   ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:411:25)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/mifunstudio/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/contexts.js:16:16)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "seti-icons"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
file-icons, v1.7.17
json-schema, v0.1.15
linter, v1.11.14
minimap, v4.24.7
omnisharp-atom, v0.30.4

# Dev
No dev packages
```
