### ISSUE TITLE
Uncaught TypeError: Cannot read property 'solution' of null

### ISSUE THREAD

**Issue by gjmveloso** [OmniSharp/omnisharp-atom#743]
### Opening based in the following

1. Open a directory with VS 2013 solution inside
2. Disable and enable Omnisharp server twice from the bottom toolbar

**Atom Version**: 1.7.4
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.29.4

### Stack Trace

Uncaught TypeError: Cannot read property 'solution' of null

```
At C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\scheduler\QueueScheduler.js:24

TypeError: Cannot read property 'solution' of null
    at SwitchMapSubscriber.project (C:\Users\.atom\packages\omnisharp-atom\lib\server\omni.js:62:36)
    at SwitchMapSubscriber._next (C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\switchMap.js:87:27)
    at SwitchMapSubscriber.Subscriber.next (C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at FilterSubscriber._next (C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\filter.js:88:30)
    at FilterSubscriber.Subscriber.next (C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at RefCountSubscriber.Subscriber._next (C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:125:26)
    at RefCountSubscriber.Subscriber.next (C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at ReplaySubject.Subject.next (C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\Subject.js:55:25)
    at ReplaySubject.next (C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\ReplaySubject.js:28:31)
    at ConnectableSubscriber.Subscriber._next (C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:125:26)
    at ConnectableSubscriber.Subscriber.next (C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at DebounceTimeSubscriber.debouncedNext (C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\debounceTime.js:98:30)
    at FutureAction.dispatchNext (C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\debounceTime.js:114:16)
    at FutureAction.execute (C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\scheduler\FutureAction.js:28:22)
    at AsyncScheduler.QueueScheduler.flush (C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\scheduler\QueueScheduler.js:21:20)
    at C:\Users\.atom\packages\omnisharp-atom\node_modules\rxjs\scheduler\FutureAction.js:93:23
```

### Commands

```
     -9:34.3.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -9:30 omnisharp-atom:restart-server (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -9:08.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -9:08.8.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "omnisharp-atom": {
    "altGotoDefinition": true,
    "codeLens": false,
    "enhancedHighlighting": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
atom-yeoman, v0.3.15
autoclose-html, v0.23.0
autocomplete-paths, v1.0.2
file-icons, v1.7.13
json-schema, v0.1.15
keyboard-localization, v1.4.18
linter, v1.11.4
linter-eslint, v7.2.2
merge-conflicts, v1.4.3
minimap, v4.24.3
omnisharp-atom, v0.29.4
pigments, v0.29.1
react, v0.15.0

# Dev
No dev packages
```

**Comment by marcodiniz** [comment]
Same Error Here

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.0-beta0
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.29.4


### Stack Trace

Uncaught TypeError: Cannot read property 'solution' of null

```
At C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\scheduler\QueueScheduler.js:24

TypeError: Cannot read property 'solution' of null
    at SwitchMapSubscriber.project (C:\Users\msn\.atom\packages\omnisharp-atom\lib\server\omni.js:62:36)
    at SwitchMapSubscriber._next (C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\switchMap.js:87:27)
    at SwitchMapSubscriber.Subscriber.next (C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at FilterSubscriber._next (C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\filter.js:88:30)
    at FilterSubscriber.Subscriber.next (C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at RefCountSubscriber.Subscriber._next (C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:125:26)
    at RefCountSubscriber.Subscriber.next (C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at ReplaySubject.Subject.next (C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\Subject.js:55:25)
    at ReplaySubject.next (C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\ReplaySubject.js:28:31)
    at ConnectableSubscriber.Subscriber._next (C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:125:26)
    at ConnectableSubscriber.Subscriber.next (C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at DebounceTimeSubscriber.debouncedNext (C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\debounceTime.js:98:30)
    at FutureAction.dispatchNext (C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\debounceTime.js:114:16)
    at FutureAction.execute (C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\scheduler\FutureAction.js:28:22)
    at AsyncScheduler.QueueScheduler.flush (C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\scheduler\QueueScheduler.js:21:20)
    at C:\Users\msn\.atom\packages\omnisharp-atom\node_modules\rxjs\scheduler\FutureAction.js:93:23
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "omnisharp-atom": {
    "enableAdvancedFileNew": true,
    "enhancedHighlighting": true
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.3 (active)
atom-beautify, v0.29.8 (inactive)
atom-monokai, v0.10.4 (inactive)
atom-typescript, v8.11.0 (active)
atom-yeoman, vundefined (active)
autoclose-html, v0.23.0 (active)
autocomplete-modules, v1.5.1 (active)
autocomplete-paths, v1.0.2 (active)
file-icons, v1.7.15 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
json-schema, v0.1.15 (active)
language-cshtml, v0.2.1 (active)
linter, v1.11.10 (inactive)
minimap, v4.24.6 (active)
minimap-highlight-selected, v4.4.0 (active)
monokai, v0.18.0 (active)
monokai-slate, v0.5.0 (inactive)
omnisharp-atom, v0.29.4 (active)
pigments, v0.29.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by asbjornu** [comment]
This just happened to me as well. I didn't do anything but close a tab and then click inside another.
