### ISSUE TITLE
Uncaught TypeError: Cannot read property 'CodeActions' of null

### ISSUE THREAD

**Issue by asbjornu** [OmniSharp/omnisharp-atom#789]
**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.30.4

### Stack Trace

Uncaught TypeError: Cannot read property 'CodeActions' of null

```
At /Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:227

TypeError: Cannot read property 'CodeActions' of null
    at /Users/aul/.atom/packages/omnisharp-atom/dist/features/code-action.js:69:40
    at FilterSubscriber._next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/filter.js:81:37)
    at FilterSubscriber.Subscriber.next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at FilterSubscriber._next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/filter.js:88:30)
    at FilterSubscriber.Subscriber.next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at RefCountSubscriber.Subscriber._next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at RefCountSubscriber.Subscriber.next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at Subject.next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subject.js:55:25)
    at ConnectableSubscriber.Subscriber._next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at ConnectableSubscriber.Subscriber.next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at SwitchMapSubscriber.notifyNext (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/switchMap.js:123:30)
    at InnerSubscriber._next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at MergeAllSubscriber.OuterSubscriber.notifyNext (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/OuterSubscriber.js:19:26)
    at InnerSubscriber._next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at FilterSubscriber._next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/filter.js:88:30)
    at FilterSubscriber.Subscriber.next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at Subject.next (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subject.js:55:25)
    at SafeSubscriber._error (/Users/aul/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/reactive/reactive-client.js:185:32)
    at SafeSubscriber.__tryOrUnsub (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:223:16)
    at SafeSubscriber.error (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:184:26)
    at Subscriber._error (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:128:26)
    at Subscriber.error (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:102:18)
    at TimeoutSubscriber._error (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/timeout.js:90:26)
    at TimeoutSubscriber.Subscriber.error (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:102:18)
    at AsyncSubject.Subject.error (/Users/aul/.atom/packages/omnisharp-atom/node_modules/rxjs/Subject.js:70:21)
    at StdioDriver.handlePacketResponse (/Users/aul/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:280:30)
    at StdioDriver.handlePacket (/Users/aul/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:264:22)
    at StdioDriver.handleData (/Users/aul/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:257:22)
    at Interface.<anonymous> (/Users/aul/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/stdio.js:152:31)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:169:7)
    at Interface._onLine (readline.js:210:10)
    at Interface.<anonymous> (readline.js:340:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:339:11)
    at Socket.ondata (readline.js:86:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

### Commands

```
  4x -0:06.0 core:move-up (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:05.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:03.9.0 core:save (atom-text-editor.editor.omnisharp-editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "atom-sharp",
      "autosave",
      "json-schema"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-beautify, vundefined
atom-yeoman, v0.3.15
autocomplete-clang, v0.9.4
clang-format, v1.25.0
editor-settings, v1.1.0
filesize, v0.4.2
language-antlr4, v0.1.0
language-bnf, v1.1.0
language-fsharp, v0.8.4
language-plantuml, v0.2.0
language-powershell, v2.1.1
line-ending-converter, v1.3.2
linter, v1.11.14
markdown-scroll-sync, v2.1.2
omnisharp-atom, v0.30.4
plantuml-viewer, v0.7.0
set-syntax, v0.3.0
sync-settings, v0.7.2
tabs-to-spaces, v1.0.2
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by krzeznicki** [comment]
The same error here
**Atom Version:** 1.8.0
**System:** Mac OS 10.12.5
*Thrown From:* omnisharp-atom package, v0.31.2

It's my first attempt to C# and unity3D (ver. 2017.1). The default script editor is not very well so I decided to try with Atom but I can't because of this error :(

**Comment by lucasrumney94** [comment]
I am having this issue too. 
Windows 7. Trying to use C# and Unity3D, it would be great to have this fixed.
