### ISSUE TITLE
Uncaught TypeError: Cannot read property 'silentRetokenizeLines' of undefined

### ISSUE THREAD

**Issue by Murriouz** [OmniSharp/omnisharp-atom#793]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.30.4

### Stack Trace

Uncaught TypeError: Cannot read property 'silentRetokenizeLines' of undefined

```
At /Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/Observable.js:61

TypeError: Cannot read property 'silentRetokenizeLines' of undefined
    at /Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/dist/features/highlight-v1.9.js:138:43
    at SafeSubscriber._next (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/dist/server/omni.js:499:17)
    at SafeSubscriber.__tryOrSetError (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:232:16)
    at SafeSubscriber.next (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:174:27)
    at Subscriber._next (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at FilterSubscriber._next (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/operator/filter.js:88:30)
    at FilterSubscriber.Subscriber.next (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at RefCountSubscriber.Subscriber._next (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at RefCountSubscriber.Subscriber.next (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at ReplaySubject._subscribe (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/ReplaySubject.js:38:24)
    at ReplaySubject.Observable.subscribe (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/Observable.js:56:27)
    at ConnectableObservable._subscribe (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/observable/ConnectableObservable.js:23:34)
    at ConnectableObservable.Observable.subscribe (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/Observable.js:56:27)
    at Observable._subscribe (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/Observable.js:114:28)
    at RefCountOperator.call (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/observable/ConnectableObservable.js:91:35)
    at Observable.subscribe (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/Observable.js:53:22)
    at Observable._subscribe (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/Observable.js:114:28)
    at FilterOperator.call (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/operator/filter.js:58:23)
    at Observable.subscribe (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/node_modules/rxjs/Observable.js:53:22)
    at OmniManager.switchActiveEditor (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/dist/server/omni.js:488:16)
    at Highlight.activate (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/dist/features/highlight-v1.9.js:136:28)
    at /Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/dist/omnisharp-atom.js:307:35
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:614:16
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at HTMLSpanElement.view.onclick (/Users/Murriouz/Dropbox/Preferences/Atom/packages/omnisharp-atom/dist/atom/feature-buttons.js:102:36)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "spell-check",
      "metrics",
      "background-tips",
      "atom-typescript",
      "react",
      "file-type-icons",
      "unfancy-file-icons",
      "advanced-open-file",
      "atom-yeoman",
      "json-schema"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.meta"
    ],
    "projectHome": "/Users/Murriouz/Developer",
    "themes": [
      "dark-bint-ui",
      "dark-bint-syntax"
    ]
  },
  "omnisharp-atom": {
    "enhancedHighlighting": true,
    "signatureHelp": true,
    "useLeftLabelColumnForSuggestions": true,
    "enhancedHighlighting19": true
  }
}
```

### Installed Packages

```coffee
# User
atom-formatter-jsbeautify, v1.1.2
atom-ternjs, v0.14.2
autocomplete-paths, v1.0.2
dark-bint-syntax, v0.8.9
dark-bint-ui, v0.5.2
formatter, v2.12.3
language-babel, v2.29.2
linter, v1.11.14
linter-eslint, v7.2.4
minimap, v4.24.6
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.1
minimap-selection, v4.4.0
omnisharp-atom, v0.30.4
pigments, v0.30.0
selection-highlight, v0.1.5
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by Cr4ck3rs** [comment]
I'm havint eh same issue on a net core project

**Comment by joedof** [comment]
Same here

> Starting OmniSharp server (pid:undefined)
> OmniSharp Location: /home/edo/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/omnisharp-ubuntu-x64-netcoreapp1.0/OmniSharp
> Change the location that OmniSharp is loaded from by setting the OMNISHARP environment variable
> OmniSharp Path: /home/edo/IO/Test/Test/Test.sln
> Failed to initialize CoreCLR, HRESULT: 0x80131500

```
Uncaught TypeError: Cannot read property 'silentRetokenizeLines' of undefined


TypeError: Cannot read property 'silentRetokenizeLines' of undefined
    at /home/edo/.atom/packages/omnisharp-atom/dist/features/highlight-v1.9.js:138:43
    at SafeSubscriber._next (/home/edo/.atom/packages/omnisharp-atom/dist/server/omni.js:499:17)
    at SafeSubscriber.__tryOrUnsub (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:223:16)
    at SafeSubscriber.next (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:172:22)
    at Subscriber._next (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at FilterSubscriber._next (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/filter.js:88:30)
    at FilterSubscriber.Subscriber.next (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at RefCountSubscriber.Subscriber._next (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at RefCountSubscriber.Subscriber.next (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at ReplaySubject.Subject.next (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/Subject.js:55:25)
    at ReplaySubject.next (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/ReplaySubject.js:28:31)
    at ConnectableSubscriber.Subscriber._next (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at ConnectableSubscriber.Subscriber.next (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at MapSubscriber._next (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/map.js:82:26)
    at MapSubscriber.Subscriber.next (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at DebounceTimeSubscriber.debouncedNext (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/debounceTime.js:98:30)
    at FutureAction.dispatchNext (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/debounceTime.js:114:16)
    at FutureAction.execute (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/FutureAction.js:28:22)
    at AsyncScheduler.QueueScheduler.flush (/home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/QueueScheduler.js:21:20)
    at /home/edo/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/FutureAction.js:93:23
```
