### ISSUE TITLE
Omnisharp-atom MSBuildProjectSystem error on OSX 10.11

### ISSUE THREAD

**Issue by jinl14** [OmniSharp/omnisharp-atom#796]
I recently updated a bunch of atom packages including an Omnisharp update to 0.30.4. I am now regretting this. The omnisharp console output is throwing an MSBuildProjectSystem exception and a NuGet unhandled exception. Versions are as follows:

Atom:   1.9.0-beta0
Omnisharp-atom:   0.30.4
OSX:   10.11.4

Omnisharp Output:
```
The project system 'MSBuildProjectSystem' threw exception during initialisation.
The type initializer for 'Crypto' threw an exception.
   at Interop.Crypto.EvpMd5()
   at Internal.Cryptography.HashProviderDispenser.CreateHashProvider(String hashAlgorithmId)
   at System.Security.Cryptography.MD5.Implementation..ctor()
   at OmniSharp.MSBuild.MSBuildProjectSystem.UnityTypeGuid(String projectName) in /Users/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.MSBuild/MSBuildProjectSystem.cs:line 187
   at OmniSharp.MSBuild.MSBuildProjectSystem.Initalize(IConfiguration configuration) in /Users/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.MSBuild/MSBuildProjectSystem.cs:line 68
   at OmniSharp.Startup.Configure(IApplicationBuilder app, IServiceProvider serviceProvider, IOmnisharpEnvironment env, ILoggerFactory loggerFactory, ISharedTextWriter writer, IOmnisharpAssemblyLoader loader, IOptions`1 optionsAccessor) in /Users/travis/build/OmniSharp/omnisharp-roslyn/src/OmniSharp.Host/Startup.cs:line 183
Configuration finished.
```

Attempts to solve the MSBuildProjectSystem error have been made by typing the following into terminal:
```
brew install openssl
brew link --force openssl
```
This caused a missing .NET 3.5 reference assembly warning. In desperation, I unlinked the above and attempted to downgrade Omnisharp-atom to 0.30.0 or lower. This threw an error of:
 ../node_modules/font-awesome/less/font-awesome.less wasn't found

I am now going to continue working on my project without Intellisense but its a real pain to do so. Any advice would be greatly appreciated. Thank you in advance.

**Comment by dapetcu21** [comment]
Experiencing the same issue. I also found a similar issue opened on the omnisharp-vscode repo:
https://github.com/OmniSharp/omnisharp-vscode/issues/461

**Comment by jinl14** [comment]
As per https://github.com/OmniSharp/omnisharp-vscode/issues/410 workaround, attempted the following again:
```
brew install openssl
brew link --force openssl
```
On first glance, IntelliSense for Unity seems to be restored. However the following warning and error can be seen within the omnisharp console:
```
The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
An unhandled exception has occurred: NuGet does not support /packagesource
```
The .NET reference assemblies warning has also been seen within the workaround with the same behaviour of IntelliSense not working for .NET assemblies such as Linq and System.Diagnostics. So it would seem that Omnisharp fails to detect the .NET version Unity is using.

**Comment by ccbentlee** [comment]
Same issue here. Omnisharp 0.30.7 .

**Comment by nfantone** [comment]
Same here, Mac OSX, 0.30.7. Unity project not loading.

```
The reference assemblies for framework ".NETFramework,Version=v2.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
Failed to process project file '/Users/nfantone/my-project/Assembly-CSharp.csproj'.
```

**Comment by Lechuzza** [comment]
Same issue, anyone found a workaround?

**Comment by nfantone** [comment]
@Lechuzza Move to vscode?

**Comment by echorebel** [comment]
Same issue on my end, any1 got an idea?

**Comment by tmunro** [comment]
I'm having the same issues. I'd be happy to help if anyone wants to point me in the right direction.

**Comment by hex3r** [comment]
Same here.

**Comment by nfantone** [comment]
Project's dead, folks. Move along. 

https://www.reactiongifs.com/r/330f.gif

**Comment by ccbentlee** [comment]
Already move to VSCode, Unity 5.5.0 beta is now support VSCode without any extensions.It's great.

**Comment by Danielhu229** [comment]
Well, two month later~

**Comment by jinl14** [comment]
If your using Unity, move to VSCode. You will have the added benefit of having a debugger, you can also customise VSCode with similar extensions to atom. Open source projects are great but ultimately I have no idea how much testing they go through before someone decides to publish updates. Hence you will always be cautious when updating extensions.
