### ISSUE TITLE
Uncaught TypeError: Cannot read property '_buildTokenizedLineForRowWithText' of undefined

### ISSUE THREAD

**Issue by mathuin** [OmniSharp/omnisharp-atom#803]
[Enter steps to reproduce below:]
1. Install omnisharp-atom and dependencies on Atom.
2. Opened ProbeControlRoom.cs from https://github.com/tabakhase/KSP-ProbeControlRoom

Sorry for the lame steps, this is my very first time trying C#/Mono/etc.

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.30.4
### Stack Trace

Uncaught TypeError: Cannot read property '_buildTokenizedLineForRowWithText' of undefined

```
At /home/jmt/.files/atom/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/QueueScheduler.js:24

TypeError: Cannot read property '_buildTokenizedLineForRowWithText' of undefined
    at augmentEditor (/home/jmt/.files/atom/.atom/packages/omnisharp-atom/dist/features/highlight-v1.9.js:200:32)
    at Highlight.setupEditor (/home/jmt/.files/atom/.atom/packages/omnisharp-atom/dist/features/highlight-v1.9.js:159:13)
    at /home/jmt/.files/atom/.atom/packages/omnisharp-atom/dist/features/highlight-v1.9.js:131:23
    at SafeSubscriber._next (/home/jmt/.files/atom/.atom/packages/omnisharp-atom/dist/server/omni.js:574:17)
    at SafeSubscriber.__tryOrUnsub (/home/jmt/.files/atom/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:223:16)
    at SafeSubscriber.next (/home/jmt/.files/atom/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:172:22)
    at Subscriber._next (/home/jmt/.files/atom/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (/home/jmt/.files/atom/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at FilterSubscriber._next (/home/jmt/.files/atom/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/filter.js:88:30)
    at FilterSubscriber.Subscriber.next (/home/jmt/.files/atom/.atom/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at Notification.observe (/home/jmt/.files/atom/.atom/packages/omnisharp-atom/node_modules/rxjs/Notification.js:32:50)
    at FutureAction.ObserveOnSubscriber.dispatch (/home/jmt/.files/atom/.atom/packages/omnisharp-atom/node_modules/rxjs/operator/observeOn.js:50:22)
    at FutureAction.execute (/home/jmt/.files/atom/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/FutureAction.js:28:22)
    at AsyncScheduler.QueueScheduler.flush (/home/jmt/.files/atom/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/QueueScheduler.js:21:20)
    at /home/jmt/.files/atom/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/FutureAction.js:93:23
```
### Commands

```
     -0:27 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
  6x -0:23.5.0 omnisharp-atom:start-server (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "omnisharp-atom": {
    "enhancedHighlighting19": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-django, v0.3.2
atom-yeoman, v0.3.15
autocomplete-go, v1.1.0
builder-go, v1.0.0
environment, v1.2.0
go-config, v1.2.1
go-get, v1.0.3
go-plus, v4.1.0
go-rename, v0.3.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
json-schema, v0.1.15
language-docker, v1.1.6
language-latex, v0.6.1
language-lua, v0.9.4
language-opencl, v0.1.1
language-r, v0.4.1
language-restructuredtext, v1.0.0
linter, v1.11.14
linter-flake8, v1.13.2
merge-conflicts, v1.4.4
minimap, v4.24.7
navigator-godef, v1.0.3
omnisharp-atom, v0.30.4
package-sync, v1.1.0
tester-go, v1.0.4
travis-ci-status, v1.1.1

# Dev
No dev packages
```

**Comment by mathuin** [comment]
I no longer use omnisharp so I'm closing this issue.
