### ISSUE TITLE
_omnisharpClient.CompositeDisposable is not a constructor

### ISSUE THREAD

**Issue by nfantone** [OmniSharp/omnisharp-atom#829]
[Enter steps to reproduce below:]

1. Install `omnisharp-atom` package.
2. Re-load atom and open any C# project.

**Atom Version**: 1.11.0-dev-89c638a
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.30.5

### Stack Trace

Failed to activate the omnisharp-atom package

```
At _omnisharpClient.CompositeDisposable is not a constructor

TypeError: _omnisharpClient.CompositeDisposable is not a constructor
    at OmniSharpAtom.activate (/Users/nfantone/.atom/packages/omnisharp-atom/lib/omnisharp-atom.js:123:31)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:779:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "spacegray-dark-ui",
      "base16-ocean-dark-spacegray"
    ]
  },
  "omnisharp-atom": {
    "wantMetadata": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.5 (inactive)
angularjs-styleguide-snippets, v0.7.3 (inactive)
atom-beautify, v0.29.10 (inactive)
atom-soda-dark-ui, v1.1.0 (inactive)
atom-typescript, v10.1.6 (inactive)
autoclose-html, v0.23.0 (inactive)
base16-ocean-dark-spacegray, v0.12.0 (inactive)
base16-ocean-dark-syntax-theme, v0.1.9 (inactive)
docblockr, v0.8.3 (inactive)
duotone-dark-space-syntax, v1.0.0 (inactive)
duotone-dark-syntax, v1.0.0 (inactive)
editorconfig, v1.4.1 (inactive)
emmet, v2.4.3 (inactive)
file-icons, v1.7.18 (inactive)
fonts, v1.6.0 (inactive)
git-plus, v5.16.2 (inactive)
highlight-line, v0.11.1 (inactive)
highlight-selected, v0.11.2 (inactive)
linter, v1.11.16 (inactive)
linter-eslint, v7.2.4 (inactive)
linter-jsonlint, v1.3.0 (inactive)
linter-tslint, v0.11.1 (inactive)
merge-conflicts, v1.4.4 (inactive)
minimap, v4.24.7 (inactive)
minimap-highlight-selected, v4.4.0 (inactive)
minimap-pigments, v0.2.1 (inactive)
npm-install, v4.0.3 (inactive)
oceanic-next, v0.2.0 (inactive)
omnisharp-atom, v0.30.5 (inactive)
pigments, v0.32.0 (inactive)
spacegray-dark-ui, v0.12.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.6.0 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.41.1 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.58.3 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.65.0 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.209.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

Some other people here #578 have been experiencing the same, but since the issue is closed (and a year old), I figure I should open a new one.

**Comment by nfantone** [comment]
This seems to be related to `*Disposables` objects being moved to a different package: [ts-disposables](https://npmjs.org/ts-disposables).

To workaround the issue,

1. Install `ts-disposables` as a dependency

```sh
cd ~/.atom/packages/omnisharp-atom
npm i --save ts-disposables
```

2. Now, change every `*.ts` file with an import of `xxxDisposable` (like `CompositeDisposable`) from `"omnisharp-client"` to `"ts-disposable"`. For instance,

```js
import {Disposable, CompositeDisposable, IDisposable} from "omnisharp-client";
// changes to '... from "ts-disposables";'
```

3. Run `npm i` on the package root directory.

```sh
cd ~/.atom/packages/omnisharp-atom
npm i
```

4. Restart atom. Now the package loads correctly (see screenshot below).

<img width="754" alt="screen shot 2016-08-23 at 1 13 01 pm" src="https://cloud.githubusercontent.com/assets/476069/17891392/62f1b85a-6933-11e6-8f5a-5e3023feb256.png">


Sadly, while this fixes this issue, it seems like Omnisharp still does nothing more apart from loading. I got no intellisense, no autocomplete, no code format, zero warnings or errors.

Seems like this whole project needs a big update.
