### ISSUE TITLE
Uncaught TypeError: Cannot read property 'run' of undefined

### ISSUE THREAD

**Issue by vicky08** [OmniSharp/omnisharp-atom#837]
[Enter steps to reproduce below:]

1. Packages -> Omnisharp
2. New Project

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.30.7

### Stack Trace

Uncaught TypeError: Cannot read property 'run' of undefined

```
At C:\Users\ing04833\.atom\packages\omnisharp-atom\dist\atom\generator-aspnet.js:87

TypeError: Cannot read property 'run' of undefined
    at GeneratorAspnet.run (C:\Users\ing04833\.atom\packages\omnisharp-atom\dist\atom\generator-aspnet.js:87:34)
    at GeneratorAspnet.newProject (C:\Users\ing04833\.atom\packages\omnisharp-atom\dist\atom\generator-aspnet.js:78:41)
    at atom-workspace.<anonymous> (C:\Users\ing04833\.atom\packages\omnisharp-atom\dist\atom\generator-aspnet.js:42:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\ing04833\AppData\Local\atom\app-1.10.0\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\ing04833\AppData\Local\atom\app-1.10.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\ing04833\AppData\Local\atom\app-1.10.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\ing04833\AppData\Local\atom\app-1.10.0\resources\app.asar\src\atom-environment.js:1109:28)
    at EventEmitter.outerCallback (C:\Users\ing04833\AppData\Local\atom\app-1.10.0\resources\app.asar\src\application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

### Commands

```
     -7:07.8.0 settings-view:open (atom-pane.pane.active)
 11x -7:06.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -7:03.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 19x -5:48.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -5:33.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 17x -4:29.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:00.1.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
     -0:49.7.0 core:backspace (atom-text-editor#editor.tabLength.editor.mini.is-focused)
     -0:49.1.0 core:confirm (atom-text-editor#editor.tabLength.editor.mini.is-focused)
     -0:32.2.0 tree-view:toggle (button.btn.btn-default.icon.icon-link-external)
     -0:16.7.0 omnisharp-atom:toggle (ul.list-inline.tab-bar.inset-panel)
     -0:15.2.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:10.3.0 omnisharp-atom:new-project (button.btn.btn-default.btn-fix.selected)
```

### Config

```json
{
  "omnisharp-atom": {
    "developerMode": true
  }
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.11.2 (active)
language-fsharp, v0.8.4 (active)
linter, v1.11.16 (active)
minimap, v4.25.0 (active)
omnisharp-atom, v0.30.7 (active)
open-recent, v5.0.0 (active)
vim-mode, v0.65.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Nokel81** [comment]
This is also happening on macOS even with the latest version on mono and .NET installed

**Comment by hahnrobert** [comment]
Same for me. Latest mono & .Net Core

**Comment by sunkin351** [comment]
I am having the same issue...
Might I add that I get this every time I try to make a new project?

**Comment by sunkin351** [comment]
Maybe this should be in another issue, but for me, I dont think the server is starting... At least its not running when I go to look for it. Appears to crash after it reports its working directory.

**Comment by tobi-the-fraggel** [comment]
Same issue here. I actually just installed atom with a bunch of coding packages while omnisharp is just one of them. I am running Win7-64bit with .NET4.5.2
Could that be an issue? I mean, is omnisharp not compatible with more recent .NET versions?

**Comment by ZeroCool2u** [comment]
[See](https://github.com/OmniSharp/omnisharp-atom/issues/175)

**Comment by lednhatkhanh** [comment]
I don't have those packages installed and still error.

**Comment by Dmaisano404** [comment]
I recently formatted my computer and have dotnet core as well as mono install on Windows *64 bit* and am getting the same errors. On mac I am able to run Omnisharp fine without any issues. Any solutions to this?

[https://gyazo.com/fa7dddce6c98c3168d1aa8ee0fadfa36](url)

**Comment by ktsarlz** [comment]
How to fix this? I'm fairly new to this omnisharp with atom. I can't get anything to work, even a simple console app from visual studio. the server won't turn on. And when creating a new package this error pops up.

**Comment by rheaney** [comment]
Would there happen to be any solution to this? Running into it on a new install on macOS using the latest version of everything.

**Comment by karthik-bhat** [comment]
After installing atom-yeoman the error popup seems to go but omnisharp server still doesn't seem to start. Any idea how to get around this? 
I have latest version on .net and atom and i'm working on windows 64 bit.
I'm relatively new to Omnisharp and Atom if anyone is able to fix the issue please share your inputs.

**Comment by ZeroCool2u** [comment]
I really don't have too much experience in TS/JS, but I looked into this for a couple hours today. I thought this was related to the undefined parameter passed in the run command at first, but after spending some time looking into this deeper, it seems like the generator isn't initialized yet for some reason, which is weird, because it looks like it is at the end of the file. 

Honestly, I'm just not experienced enough with large TS/JS projects to know, but I've had a few friends try installing this as well and they've all encountered the same error. Perhaps @david-driscoll can shed some light.

**Comment by gfpl001** [comment]
Same problem on mac Os Sierra with a clean install :(

**Comment by Liam-Hinzman** [comment]
I'm having the same error on Ubuntu 16.04

**Comment by mateuszlewko** [comment]
Same error on macOS Sierra.  Mono installed and working, omnisharp server not starting.
Will this issue be ever fixed?

**Comment by danwad** [comment]
@david-driscoll & team haven't committed for 3 months. Omnisharp chatroom link on the official website goes to a broken page. I tried reaching out to Omnisharp about it on twitter but got no response. Their official twitter account hasn't been active since March 2016.

I guess they need more volunteers.

**Comment by Liam-Hinzman** [comment]
Is there an alternative to Omnisharp for Atom? I really need something with C# support for Unity development

**Comment by mateuszlewko** [comment]
I don't know any alternatives for Atom but you can u can try Visual Studio
Code. It works very well with c# out of the box.

**Comment by Hivemind9000** [comment]
I'm having the same problems (server won't start for existing C#/sln projects, New Project throws exception).

Noticed the builds are failing for this project. Is anyone home?

**Comment by aschuhardt** [comment]
Still getting this issue.  Stack trace below.

```
TypeError: Cannot read property 'run' of undefined
    at GeneratorAspnet.run (/home/user/.atom/packages/omnisharp-atom/dist/atom/generator-aspnet.js:87:34)
    at GeneratorAspnet.newProject (/home/user/.atom/packages/omnisharp-atom/dist/atom/generator-aspnet.js:78:41)
    at atom-workspace.<anonymous> (/home/user/.atom/packages/omnisharp-atom/dist/atom/generator-aspnet.js:42:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1175:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:319:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by sufyanghazali** [comment]
I'm having the same problem. Is there any way to fix it? 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2


### Stack Trace

Uncaught TypeError: Cannot read property 'run' of undefined

```
At C:\Users\sufya\.atom\packages\omnisharp-atom\dist\atom\generator-aspnet.js:87

TypeError: Cannot read property 'run' of undefined
    at GeneratorAspnet.run (/packages/omnisharp-atom/dist/atom/generator-aspnet.js:87:34)
    at GeneratorAspnet.newProject (/packages/omnisharp-atom/dist/atom/generator-aspnet.js:78:41)
    at /packages/omnisharp-atom/dist/atom/generator-aspnet.js:42:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -1:37.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-base16-syntax.theme-one-dark-ui)
  3x -1:21.6.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.theme-base16-syntax.theme-one-dark-ui)
     -1:16.4.0 omnisharp-atom:new-project (div.tool-panel.tree-view)
     -1:07.5.0 omnisharp-atom:toggle (a.btn-issue.btn.btn-error)
     -0:32.2.0 omnisharp-atom:new-project (input.hidden-input)
  2x -0:17.4.0 omnisharp-atom:solution-status (atom-workspace.workspace.scrollbars-visible-always.theme-base16-syntax.theme-one-dark-ui)
     -0:16.3.0 omnisharp-atom:toggle-dock (atom-workspace.workspace.scrollbars-visible-always.theme-base16-syntax.theme-one-dark-ui)
     -0:12.3.0 linter-ui-default:toggle-panel (atom-workspace.workspace.scrollbars-visible-always.theme-base16-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
base16-syntax 1.8.1 
busy-signal 1.4.3 
dracula-syntax 2.0.5 
dracula-ui 0.6.0 
file-icons 2.1.8 
firewatch-green-syntax 1.1.0 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.2 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
omnisharp-atom 0.31.2 
open-recent 5.0.0 
pigments 0.39.1 
script 3.15.0 
simple-drag-drop-text 0.3.4 
todo-show 1.11.0 
```
`

**Comment by JosueOlivero** [comment]
So...does anyone knows how to fix it?

**Comment by Lrss** [comment]
Same problem on Arch (x86_64 Linux 4.12.12-1-ARCH)

**Comment by ronanamsterdam** [comment]
trying to run debugger with Ruby. Getting this thing with latest vsc (1.18.0).
No idea what's wrong cuz the error is so informative :/

**Comment by JustinCann** [comment]
You need to install https://github.com/OmniSharp/generator-aspnet

**Comment by devprophet** [comment]
Same problem on Mac OS High Sierra 10.13.1 (17B1003) ...

**Comment by galactose310** [comment]
And so do I...

**Comment by ryoppippi** [comment]
Same

**Comment by amargolis** [comment]
Having the same issue on 10.13.2 High Sierra and Atom 1.23.3

**Comment by fireagentk** [comment]
Having issue Windows 8.1 Pro latest atom version

**Comment by vahlo** [comment]
Same on mac.
Any fix to this or is this project dead?!

**Comment by michaelharmonart** [comment]
Same issue here.

**Comment by koxu1996** [comment]
Project is dead. Do not waste time on it.
