### ISSUE TITLE
server wont auto start and ctrl-alt-o or menu toggle dont work

### ISSUE THREAD

**Issue by JMPSequeira** [OmniSharp/omnisharp-atom#885]
Hello, 

I'm using atom on sp4 running windows 10 pro and I've installed omnisharp, but it does nothing. I've tried to get it running by all the accessible means and nada, zippo.

Any help would be appreciated
![nogo](https://cloud.githubusercontent.com/assets/23178601/19873854/48b2a2e4-9fb9-11e6-86d3-4ed3b67a8c33.png)

**Comment by AdamWolanski** [comment]
@JMPSequeira Same here - server not responding. I'm running atom on windows 10 x64, .net 4.6.1. I also tried on windows 7 x84 and the same problem occured.

**Comment by TAGC** [comment]
Same here, on Mac Sierra 10.12.1. I don't see anything appear in the Omnisharp console and I can't do anything to enable it.

**Comment by LeftRight92** [comment]
Same, following is thrown when trying to start the server manually:

**Atom Version**: 1.12.2
**Electron Version**: 1.3.6
**System**: Microsoft Windows 10 Home
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package, v0.30.7


### Stack Trace

Uncaught TypeError: Cannot read property 'connect' of undefined

```
At C:\Users\Michael\.atom\packages\omnisharp-atom\dist\atom\solution-information.js:63

TypeError: Cannot read property 'connect' of undefined
    at atom-workspace.<anonymous> (C:\Users\Michael\.atom\packages\omnisharp-atom\dist\atom\solution-information.js:63:86)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Michael\AppData\Local\atom\app-1.12.2\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\Michael\AppData\Local\atom\app-1.12.2\resources\app.asar\src\command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Michael\AppData\Local\atom\app-1.12.2\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Michael\AppData\Local\atom\app-1.12.2\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-li.<anonymous> (C:\Users\Michael\AppData\Local\atom\app-1.12.2\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:139:19)
    at HTMLOListElement.dispatch (C:\Users\Michael\AppData\Local\atom\app-1.12.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (C:\Users\Michael\AppData\Local\atom\app-1.12.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -5:44.9.0 core:undo (atom-text-editor.editor.is-focused)
     -5:43.2.0 application:open-folder (atom-text-editor.editor.is-focused)
     -5:37.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -5:34 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:34 linter:toggle (atom-text-editor.editor)
     -5:31.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -5:28.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:27.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:27.3.0 linter:toggle (atom-text-editor.editor)
     -5:24.8.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
     -5:22.2.0 core:cancel (div.panels-item)
     -5:06.1.0 omnisharp-atom:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -5:01.2.0 omnisharp-atom:new-project (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:14.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:04.1.0 omnisharp-atom:start-server (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "git-diff"
    ],
    "ignoredNames": [
      "*.meta"
    ],
    "telemetryConsent": "no"
  },
  "omnisharp-atom": {
    "autoAdjustTreeView": true
  }
}
```

**Comment by atrauzzi** [comment]
Experiencing this as well.  Server doesn't start, no sign of life from omnisharp.

**Comment by RegisFrey** [comment]
Similar here, on Mac El Capitan 10.11.5, nothing appears in the Omnisharp-atom console, flame never turns green, and I can't find any way to enable it.

I have mono v4.6.2 installed and dotnet 1.0.0-preview2-1-003177.

**Comment by danwad** [comment]
Same here with Windows 10. Reproduced on 3 separate machines.

**Comment by Kaari** [comment]
Same here on Debian 8, with mono 4.6.2 & atom 1.11.2.

```
[15186:1120/154312:INFO:CONSOLE(728)] "getPackageDirPaths: /home/kaari/.atom/packages", source: /home/kaari/.atom/packages/omnisharp-atom/dist/server/omni.js (728)
[15186:1120/154312:INFO:CONSOLE(730)] "packagePath /home/kaari/.atom/packages exists: true", source: /home/kaari/.atom/packages/omnisharp-atom/dist/server/omni.js (730)
[15186:1120/154314:INFO:CONSOLE(158)] "Activating omnisharp-atom solution tracking...", source: /home/kaari/.atom/packages/omnisharp-atom/dist/omnisharp-atom.js (158)
[15186:1120/154314:INFO:CONSOLE(94)] "Omni Project Candidates: Searching /home/kaari/MonoProjects for global.json,*.sln", source: /home/kaari/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/candidate-finder.js (94)
# ...
# ...
[15186:1120/154320:INFO:CONSOLE(65)] "Omni Project Candidates: Found /home/kaari/MonoProjects", source: /home/kaari/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/candidate-finder.js (65)
[15186:1120/154320:INFO:CONSOLE(49)] "PRETTY_NAME="Debian GNU/Linux 8 (jessie)",NAME="Debian GNU/Linux",VERSION_ID="8",VERSION="8 (jessie)",ID=debian,HOME_URL="http://www.debian.org/",SUPPORT_URL="http://www.debian.org/support",BUG_REPORT_URL="https://bugs.debian.org/",", source: /home/kaari/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/helpers/platform.js (49)
[15186:1120/154320:INFO:CONSOLE(50)] "getValue("ID")", source: /home/kaari/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/helpers/platform.js (50)
[15186:1120/154321:INFO:CONSOLE(49)] "PRETTY_NAME="Debian GNU/Linux 8 (jessie)",NAME="Debian GNU/Linux",VERSION_ID="8",VERSION="8 (jessie)",ID=debian,HOME_URL="http://www.debian.org/",SUPPORT_URL="http://www.debian.org/support",BUG_REPORT_URL="https://bugs.debian.org/",", source: /home/kaari/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/helpers/platform.js (49)
[15186:1120/154321:INFO:CONSOLE(50)] "getValue("ID")", source: /home/kaari/.atom/packages/omnisharp-atom/node_modules/omnisharp-client/lib/helpers/platform.js (50)
[15186:1120/154321:INFO:CONSOLE(307)] "Uncaught (in promise) TypeError: baseCodecheck.map(...).cache is not a function", source: /home/kaari/.atom/packages/omnisharp-atom/dist/server/view-model.js (307)
[15186:1120/154322:INFO:CONSOLE(197)] "Loading feature "atom/dock.js"...", source: /home/kaari/.atom/packages/omnisharp-atom/dist/omnisharp-atom.js (197)
# ...
# ...
```
Relevant ?

**Comment by L4D15** [comment]
Same problem here on Windows 10, server won't start and Omnisharp output is empty. Lates version of Atom and Omnisharp.

I tried compiling and starting the omnishar-roslyn server my self, but omnisharp-atom does not find that server either (that one is actually running).
