### ISSUE TITLE
buildPlaceholderTokenizedLinesForRows is not a Function

### ISSUE THREAD

**Issue by ChristopherFunk** [OmniSharp/omnisharp-atom#957]
Got this today, on Windows 10 (Enterprise) 64-bit, will try and test at home on Ubuntu 16.04 when I get home. Using latest Atom (1.14.0 ia32). EDIT: Can confirm happens on latest atom on Ubuntu 16.04 x64
Uncaught TypeError: this.buildPlaceholderTokenizedLinesForRows is not a function
...\atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:227
The error was thrown from the omnisharp-atom package. You can help by creating an issue. Please explain what actions triggered this error.

Stacktrace: 
TypeError: this.buildPlaceholderTokenizedLinesForRows is not a function
    at TokenizedBuffer.editor.tokenizedBuffer.silentRetokenizeLines.leading (...\.atom\packages\omnisharp-atom\dist\features\highlight-v1.9.js:214:40)
    at invokeFunc (...\.atom\packages\omnisharp-atom\node_modules\lodash\lodash.js:10350:23)
    at leadingEdge (...\.atom\packages\omnisharp-atom\node_modules\lodash\lodash.js:10360:26)
    at TokenizedBuffer.debounced [as silentRetokenizeLines] (...\.atom\packages\omnisharp-atom\node_modules\lodash\lodash.js:10425:20)
    at SafeSubscriber._next (...\.atom\packages\omnisharp-atom\dist\features\highlight-v1.9.js:131:68)
    at SafeSubscriber.__tryOrUnsub (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:223:16)
    at SafeSubscriber.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:172:22)
    at Subscriber._next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:125:26)
    at Subscriber.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at SwitchMapSubscriber.notifyNext (...\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\switchMap.js:124:30)
    at InnerSubscriber._next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at DeferSubscriber.OuterSubscriber.notifyNext (...\.atom\packages\omnisharp-atom\node_modules\rxjs\OuterSubscriber.js:19:26)
    at InnerSubscriber._next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at RefCountSubscriber.Subscriber._next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:125:26)
    at RefCountSubscriber.Subscriber.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at ReplaySubject.Subject.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subject.js:55:25)
    at ReplaySubject.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\ReplaySubject.js:31:31)
    at ConnectableSubscriber.Subscriber._next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:125:26)
    at ConnectableSubscriber.Subscriber.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at DoSubscriber._next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\do.js:88:30)
    at DoSubscriber.Subscriber.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at CombineLatestSubscriber._tryProject (...\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\combineLatest.js:147:26)
    at CombineLatestSubscriber.notifyNext (...\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\combineLatest.js:131:22)
    at InnerSubscriber._next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at RefCountSubscriber.Subscriber._next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:125:26)
    at RefCountSubscriber.Subscriber.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at Subject.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subject.js:55:25)
    at ConnectableSubscriber.Subscriber._next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:125:26)
    at ConnectableSubscriber.Subscriber.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at DoSubscriber._next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\do.js:88:30)
    at DoSubscriber.Subscriber.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at DoSubscriber._next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\operator\do.js:88:30)
    at DoSubscriber.Subscriber.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subscriber.js:89:18)
    at AsyncSubject.Subject.next (...\.atom\packages\omnisharp-atom\node_modules\rxjs\Subject.js:55:25)
    at AsyncSubject.complete (...\.atom\packages\omnisharp-atom\node_modules\rxjs\AsyncSubject.js:46:35)
    at StdioDriver._handlePacketResponse (...\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\StdioDriver.js:243:26)
    at StdioDriver._handlePacket (...\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\StdioDriver.js:228:18)
    at StdioDriver._handleData (...\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\StdioDriver.js:223:18)
    at Interface.<anonymous> (...\.atom\packages\omnisharp-atom\node_modules\omnisharp-client\lib\drivers\StdioDriver.js:170:54)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
    at Interface.<anonymous> (readline.js:365:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:364:11)
    at Socket.ondata (readline.js:100:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)

**Comment by eminogrande** [comment]
Same here.

**Comment by ChristopherFunk** [comment]
Duplicate of https://github.com/OmniSharp/omnisharp-atom/issues/963
