### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scopeName' of undefined

### ISSUE THREAD

**Issue by CascadeGabiS** [OmniSharp/omnisharp-atom#961]
[Enter steps to reproduce:]

1. Install Markdown Preview Plus
2. Create a Markdown file with any text formatted inside
3. Load it inside Atom using Markdown Preview Plus
4. Try to switch to the preview tab by clicking or using CTRL+TAB

**Atom**: 1.14.3 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.1

### Stack Trace

Uncaught TypeError: Cannot read property 'scopeName' of undefined

```
At C:\Users\gsasu\.atom\packages\omnisharp-atom\dist\server\omni.js:524

TypeError: Cannot read property 'scopeName' of undefined
    at OmniManager.isValidGrammar (/packages/omnisharp-atom/dist/server/omni.js:524:73)
    at /packages/omnisharp-atom/dist/server/omni.js:114:74
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.activateNextRecentlyUsedItem (/app.asar/src/pane.js:359:21)
    at /app.asar/src/register-default-commands.js:13:48)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:30.9.0 application:add-project-folder (input.hidden-input)
     -0:17.9.0 markdown-preview:preview-file (span.name.icon.icon-file-text)
     -0:13.2.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:13 pane:move-active-item-to-top-of-stack (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:12.2.0 pane:show-next-recently-used-item (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:11.1.0 pane:move-active-item-to-top-of-stack (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
atom-beautify 0.29.17 
atom-runner 2.7.1 
atom-sharp 0.1.0 
atom-yeoman 0.3.15 
autocomplete-clang 0.10.0 
autocomplete-xml 0.9.4 
build 0.67.0 
build-powershell 0.10.0 
busy 0.7.0 
chary-tree-view 0.2.3 
clang-format 1.28.0 
code-peek 1.4.16 
color-picker 2.2.5 
data-atom 0.24.1 
format-sql 0.3.0 
gcc-make-run 0.2.9 
gherkin-autocomplete 2.0.0 
git-control 0.8.2 
git-plus 7.3.2 
git-time-machine 1.5.6 
gpp-compiler 3.0.7 
ionide-fsharp undefined 
json-schema 0.1.15 
language-aspx 0.5.0 
language-cpp14 0.6.2 
language-fsharp 0.8.4 
language-ini 1.18.0 
language-powershell 4.0.0 
linter 1.11.23 
linter-cpplint 1.0.1 
linter-gcc 0.7.1 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.5 
markdown-writer 2.6.4 
minimap 4.26.8 
omnisharp-atom 0.31.1 
platformio-ide-terminal 2.2.3 
qolor 0.4.1 
script 3.14.1 
tool-bar 1.0.1 
tool-bar-main 0.0.10 
wakatime 6.0.13 
```

**Comment by Kampfmoehre** [comment]
Have the same issue but haven't installed Markdiwn preview plus. I updated a package and viewed it's changelog over the package settings page. Had to restart atom due to the package update. After restart the error popped up.

**Comment by johnrizzo1** [comment]
I had the same problem as @Kampfmoehre 

![image](https://user-images.githubusercontent.com/126500/29842964-74d90748-8cd8-11e7-9458-930fc02942ae.png)
