### ISSUE TITLE
Uncaught TypeError: this.buildPlaceholderTokenizedLinesForRows is not a function

### ISSUE THREAD

**Issue by 12C0DE** [OmniSharp/omnisharp-atom#963]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.1

### Stack Trace

Uncaught TypeError: this.buildPlaceholderTokenizedLinesForRows is not a function

```
At /Users/AAPG/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/AsyncScheduler.js:45

TypeError: this.buildPlaceholderTokenizedLinesForRows is not a function
    at TokenizedBuffer.editor.tokenizedBuffer.silentRetokenizeLines.leading (/packages/omnisharp-atom/dist/features/highlight-v1.9.js:214:40)
    at invokeFunc (/packages/omnisharp-atom/node_modules/lodash/lodash.js:10350:23)
    at leadingEdge (/packages/omnisharp-atom/node_modules/lodash/lodash.js:10360:26)
    at /packages/omnisharp-atom/node_modules/lodash/lodash.js:10425:20)
    at /packages/omnisharp-atom/dist/features/highlight-v1.9.js:137:68
    at SafeSubscriber._next (/packages/omnisharp-atom/dist/server/omni.js:420:17)
    at SafeSubscriber.__tryOrUnsub (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:234:16)
    at SafeSubscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:183:22)
    at Subscriber._next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at FilterSubscriber._next (/packages/omnisharp-atom/node_modules/rxjs/operator/filter.js:88:30)
    at FilterSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at RefCountSubscriber.Subscriber._next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at RefCountSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at ReplaySubject.Subject.next (/packages/omnisharp-atom/node_modules/rxjs/Subject.js:55:25)
    at ReplaySubject.next (/packages/omnisharp-atom/node_modules/rxjs/ReplaySubject.js:31:31)
    at ConnectableSubscriber.Subscriber._next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at ConnectableSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at MapSubscriber._next (/packages/omnisharp-atom/node_modules/rxjs/operator/map.js:83:26)
    at MapSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at DebounceTimeSubscriber.debouncedNext (/packages/omnisharp-atom/node_modules/rxjs/operator/debounceTime.js:98:30)
    at AsyncAction.dispatchNext (/packages/omnisharp-atom/node_modules/rxjs/operator/debounceTime.js:114:16)
    at AsyncAction._execute (/packages/omnisharp-atom/node_modules/rxjs/scheduler/AsyncAction.js:111:18)
    at AsyncAction.execute (/packages/omnisharp-atom/node_modules/rxjs/scheduler/AsyncAction.js:86:26)
    at AsyncScheduler.flush (/packages/omnisharp-atom/node_modules/rxjs/scheduler/AsyncScheduler.js:36:32)
```

### Commands

```
```

### Non-Core Packages

```
linter 1.11.23 
omnisharp-atom 0.31.1 
qolor 0.4.1 
```

**Comment by bhison** [comment]
Disabling linter does not prevent the error

**Comment by cbellino** [comment]
I'm also having this issue, i'm adding more informations to help reproduce:
1. Open the package settings
2. Enable the `Enhanced Highlighting` option

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.1

Feel free to ask if you need more infos :)

Hope this helps.

**Comment by tezine** [comment]
Any solution for this issue?

**Comment by blaztinn** [comment]
__Atom__: 1.15.0 x64
__Electron__: 1.3.13
__OS__: Fedora 25
__Thrown From__: omnisharp-atom package 0.31.2

The error comes from using a private/not documented function from atom that was removed in atom/atom@ea80483cbe6e97a668f720f42f9538267bc52d7f. I tried to replace the call with what that function did, there was no error afterwards but I think the `Enhanced Highlightin` feature still didn't work.

**Comment by yougotwill** [comment]
**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: omnisharp-atom package package 0.31.2

Same error as noted above. It occured similarly when `Enhanced Highlighting` was activated.


### Stack Trace

Uncaught TypeError: this.buildPlaceholderTokenizedLinesForRows is not a function

```
At /Users/William/.atom/packages/omnisharp-atom/node_modules/rxjs/scheduler/AsyncScheduler.js:45

TypeError: this.buildPlaceholderTokenizedLinesForRows is not a function
    at TokenizedBuffer.editor.tokenizedBuffer.silentRetokenizeLines.leading (/packages/omnisharp-atom/dist/features/highlight-v1.9.js:214:40)
    at invokeFunc (/packages/omnisharp-atom/node_modules/lodash/lodash.js:10350:23)
    at leadingEdge (/packages/omnisharp-atom/node_modules/lodash/lodash.js:10360:26)
    at /packages/omnisharp-atom/node_modules/lodash/lodash.js:10425:20)
    at /packages/omnisharp-atom/dist/features/highlight-v1.9.js:137:68
    at SafeSubscriber._next (/packages/omnisharp-atom/dist/server/omni.js:420:17)
    at SafeSubscriber.__tryOrUnsub (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:185:22)
    at Subscriber._next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at FilterSubscriber._next (/packages/omnisharp-atom/node_modules/rxjs/operator/filter.js:88:30)
    at FilterSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at RefCountSubscriber.Subscriber._next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at RefCountSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at ReplaySubject.Subject.next (/packages/omnisharp-atom/node_modules/rxjs/Subject.js:55:25)
    at ReplaySubject.next (/packages/omnisharp-atom/node_modules/rxjs/ReplaySubject.js:31:31)
    at ConnectableSubscriber.Subscriber._next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:125:26)
    at ConnectableSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at MapSubscriber._next (/packages/omnisharp-atom/node_modules/rxjs/operator/map.js:83:26)
    at MapSubscriber.Subscriber.next (/packages/omnisharp-atom/node_modules/rxjs/Subscriber.js:89:18)
    at DebounceTimeSubscriber.debouncedNext (/packages/omnisharp-atom/node_modules/rxjs/operator/debounceTime.js:98:30)
    at AsyncAction.dispatchNext (/packages/omnisharp-atom/node_modules/rxjs/operator/debounceTime.js:114:16)
    at AsyncAction._execute (/packages/omnisharp-atom/node_modules/rxjs/scheduler/AsyncAction.js:111:18)
    at AsyncAction.execute (/packages/omnisharp-atom/node_modules/rxjs/scheduler/AsyncAction.js:86:26)
    at AsyncScheduler.flush (/packages/omnisharp-atom/node_modules/rxjs/scheduler/AsyncScheduler.js:36:32)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.9.1 
busy-signal 1.4.3 
dracula-syntax 2.0.5 
intentions 1.1.2 
linter 2.2.0 
linter-ui-default 1.6.2 
omnisharp-atom 0.31.2 
open-recent 5.0.0 
platformio-ide-terminal 2.5.1 
sync-settings 0.8.2 
```
