### ISSUE TITLE
Uncaught Error: Server is not connected, erroring out

### ISSUE THREAD

**Issue by erikcholakhyan** [OmniSharp/omnisharp-atom#972]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.1

### Stack Trace

Uncaught Error: Server is not connected, erroring out

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:823

Error: Server is not connected, erroring out
    at StdioDriver.request (/packages/omnisharp-atom/node_modules/omnisharp-client/lib/drivers/StdioDriver.js:101:44)
    at Solution.ReactiveClient._handleResult (/packages/omnisharp-atom/node_modules/omnisharp-client/lib/reactive/ReactiveClient.js:223:29)
    at /packages/omnisharp-atom/node_modules/lodash/lodash.js:4968:19)
    at Observable._subscribe (/packages/omnisharp-atom/node_modules/omnisharp-client/lib/helpers/QueueProcessor.js:45:64)
    at Observable._trySubscribe (/packages/omnisharp-atom/node_modules/rxjs/Observable.js:57:25)
    at Observable.subscribe (/packages/omnisharp-atom/node_modules/rxjs/Observable.js:45:27)
    at Observable.ConnectableObservable.connect (/packages/omnisharp-atom/node_modules/rxjs/observable/ConnectableObservable.js:37:18)
    at RefCountOperator.call (/packages/omnisharp-atom/node_modules/rxjs/observable/ConnectableObservable.js:101:49)
    at Observable.subscribe (/packages/omnisharp-atom/node_modules/rxjs/Observable.js:42:22)
    at OmniManager.request (/packages/omnisharp-atom/dist/server/omni.js:313:24)
    at /packages/omnisharp-atom/dist/features/code-format.js:40:36
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/text-editor.js:1122:25
    at /app.asar/src/text-editor.js:1156:28
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:818:18)
    at TextEditor.module.exports.TextEditor.transact (/app.asar/src/text-editor.js:1589:26)
    at /app.asar/src/text-editor.js:1150:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/app.asar/src/text-editor.js:2563:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/app.asar/src/text-editor.js:2529:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/app.asar/src/text-editor.js:1148:19)
    at TextEditor.module.exports.TextEditor.insertText (/app.asar/src/text-editor.js:1114:19)
    at /app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/app.asar/src/text-editor-component.js:478:26)
    at /app.asar/src/text-editor-component.js:3:59)
```

### Commands

```
     -2:52.5.0 core:confirm (input.hidden-input)
 10x -2:42 core:backspace (input.hidden-input)
     -2:36.6.0 core:confirm (input.hidden-input)
  3x -1:18.3.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:36.1.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:32.9.0 core:backspace (input.hidden-input)
     -0:30.7.0 core:confirm (input.hidden-input)
     -0:12.6.0 core:backspace (input.hidden-input)
     -0:12.3.0 autocomplete-plus:confirm (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:12 core:save (input.hidden-input)
  3x -0:09.8.0 autocomplete-plus:confirm (atom-text-editor.editor.omnisharp-editor.is-focused)
     -0:08.4.0 core:backspace (input.hidden-input)
  2x -0:07.1.0 autocomplete-plus:confirm (atom-text-editor.editor.omnisharp-editor.is-focused)
```

### Non-Core Packages

```
language-sln 0.1.0 
omnisharp-atom 0.31.1 
```

**Comment by funfood** [comment]
Same here!

**Comment by Amseamle** [comment]
Also here on Mac
